"""Build the committed synthetic eDLT firmware packages used by update-plan tests.

Contents are generated bytes with a Cortex-M-shaped vector table; no vendor
image is read. ZipCrypto archives use Info-ZIP ``zip -P``; the AES archive
uses pyzipper. The password below is a synthetic test value only.
"""
from __future__ import annotations
import argparse
import hashlib
import os
from pathlib import Path
import struct
import subprocess
import tempfile

TEST_PASSWORD = b'cbus-synthetic-fixture'
TIMESTAMP = 1_600_000_000  # fixed mtime; encryption salts still differ per build


def image(name, size, address=None):
    seed = hashlib.sha256(name.encode()).digest()
    body = (seed * (size // len(seed) + 1))[:size]
    if address is None:
        return body
    return struct.pack('<II', 0x20008000, address + 0x101) + body[8:]


PACKAGES = {
    # Same entry order and naming style as the Toolkit 1.18 1.7.0 archive.
    'eDLTFirmware_1.7.0.zip': ('zipcrypto', [('edlt_fontdata_1.0.0.bin', 3000, None),
        ('edlt_main_hwv1_1_7_0.bin', 1500, 0x2000), ('edlt_main_hwv2_1_7_0.bin', 1700, 0x4000),
        ('edlt_main_hwv3_1_7_0.bin', 2100, 0x4000)]),
    # AES entries like the 1.3.0-1.5.0 archives; no Tiva/NCC image.
    'eDLTFirmware_1.5.0.zip': ('aes', [('edlt_fontdata_1.0.0.bin', 3000, None),
        ('edlt_main_hwv1_1.5.0.bin', 1300, 0x2000), ('edlt_main_hwv2_1.5.0.bin', 1400, 0x4000)]),
    # A version outside FontData1Versions installs fonts without --force-font.
    'eDLTFirmware_1.8.0.zip': ('zipcrypto', [('notes.txt', 40, None), ('edlt_fontdata_1.1.0.bin', 70000, None),
        ('edlt_main_hwv1_1_8_0.bin', 1200, 0x2000), ('edlt_main_hwv2_1_8_0.bin', 1250, 0x4000),
        ('edlt_main_hwv3_1_8_0.bin', 1350, 0x4000)]),
}


def build(output):
    output.mkdir(parents=True, exist_ok=True)
    for package, (method, entries) in PACKAGES.items():
        target = output / package
        if target.exists():
            target.unlink()
        with tempfile.TemporaryDirectory() as folder:
            paths = []
            for name, size, address in entries:
                path = Path(folder, name)
                path.write_bytes(image(name, size, address))
                os.utime(path, (TIMESTAMP, TIMESTAMP))
                paths.append(path)
            if method == 'aes':
                import pyzipper
                with pyzipper.AESZipFile(target, 'w', compression=pyzipper.ZIP_DEFLATED,
                                         encryption=pyzipper.WZ_AES) as archive:
                    archive.setpassword(TEST_PASSWORD)
                    for path in paths:
                        archive.write(path, path.name)
            else:
                subprocess.run(['zip', '-q', '-j', '-X', '-P', TEST_PASSWORD.decode(), str(target),
                                *map(str, paths)], check=True)
        print(package, hashlib.sha256(target.read_bytes()).hexdigest())


if __name__ == '__main__':
    parser = argparse.ArgumentParser()
    parser.add_argument('--output', type=Path, default=Path(__file__).with_name('fixtures') / 'firmware-update-packages')
    build(parser.parse_args().output)
