//! Port of `cbus/constants.py`: timings and thresholds.

pub const CONFIRMATION_TIMEOUT_SECONDS: f64 = 30.0;
pub const MAX_PACKET_RETRIES: u32 = 3;
pub const PACKET_RETRY_INTERVAL_SECONDS: f64 = 1.0;
pub const PENDING_CONFIRMATION_WARNING_THRESHOLD: usize = 20;
pub const CONFIRMATION_CODE_FORCE_CLEANUP_THRESHOLD: f64 = 0.9;
pub const CONFIRMATION_CODE_FORCE_CLEANUP_PERCENTAGE: f64 = 0.25;

pub const PACKET_SEND_DELAY_SECONDS: f64 = 0.1;
pub const DEFAULT_TIMESYNC_FREQUENCY_SECONDS: u64 = 10;
pub const DEFAULT_THROTTLE_PERIOD_SECONDS: f64 = 0.2;

pub const STATUS_REQUEST_BLOCK_SIZE: u16 = 32;
pub const MAX_GROUP_ADDRESS: u16 = 255;

pub const MAX_PENDING_CONFIRMATIONS: usize = 50;

pub const MQTT_DEFAULT_TLS_PORT: u16 = 8883;
pub const MQTT_DEFAULT_PLAIN_PORT: u16 = 1883;
pub const MQTT_DEFAULT_KEEPALIVE_SECONDS: u16 = 60;
