//! P3e: `cbus-selected-serial-plan-v1` compatibility vectors.
//!
//! The committed jsonl is the source of truth: one valid plan document
//! (generated by the Python coordinator against its synthetic simulator
//! fixture, ports normalized to 61001, timings frozen to fixed finite
//! constants) plus invalid mutations mirroring the seven Python mutations
//! and file-level guards. Journal/apply/verify orchestration is out of
//! scope; this tests pure document validation only (no I/O, no clock).

use cbus_transport::plan::{validate_plan_document, MAX_PLAN_BYTES};
use std::collections::HashMap;

fn load_vectors() -> Vec<serde_json::Value> {
    let text = include_str!("../../testdata/vectors/selected_serial_plan.jsonl");
    text.lines()
        .filter(|line| !line.trim().is_empty())
        .map(|line| serde_json::from_str(line).expect("vector line must be JSON"))
        .collect()
}

#[test]
fn selected_serial_plan_vectors() {
    let vectors = load_vectors();
    assert_eq!(vectors.len(), 14, "expected 14 vector lines");
    let mut seen: HashMap<String, String> = HashMap::new();
    for entry in &vectors {
        let id = entry["id"].as_str().unwrap().to_string();
        let kind = entry["kind"].as_str().unwrap();
        let expect = entry["expect"].as_str().unwrap();
        let want_reason = entry["reason"].as_str().map(str::to_string);
        let result = match kind {
            "plan" => {
                let doc = entry["document"].to_string();
                validate_plan_document(doc.as_bytes())
            }
            "raw" => validate_plan_document(entry["raw"].as_str().unwrap().as_bytes()),
            "oversize" => {
                // Built at test time so the vector file stays small; the
                // bound is MAX_PLAN_BYTES (4MiB) of raw document bytes.
                let big = " ".repeat(MAX_PLAN_BYTES + 1);
                validate_plan_document(big.as_bytes())
            }
            "canonical_oversize" => {
                // Python renders each compact `1e-7` token as `1e-07` when
                // enforcing its second, canonical-representation size bound.
                let mut raw = Vec::with_capacity(3_500_001);
                raw.push(b'[');
                for index in 0..700_000 {
                    if index != 0 {
                        raw.push(b',');
                    }
                    raw.extend_from_slice(b"1e-7");
                }
                raw.push(b']');
                validate_plan_document(&raw)
            }
            other => panic!("unknown vector kind {other}"),
        };
        match expect {
            "accept" => {
                let plan = result.unwrap_or_else(|e| panic!("{id} must accept: {e:?}"));
                assert_eq!(plan.serial, "101136.1558", "{id} serial");
                assert_eq!(plan.destination, 6, "{id} destination");
                assert_eq!(
                    plan.request_hex, "5c30354646303030463030313842313036313630363135670d",
                    "{id} request bytes"
                );
                assert!(want_reason.is_none());
            }
            "reject" => {
                let err = result.unwrap_err();
                assert_eq!(
                    Some(err.reason().to_string()),
                    want_reason,
                    "{id} reason class"
                );
            }
            other => panic!("unknown expectation {other}"),
        }
        seen.insert(id, expect.to_string());
    }
    assert!(seen.contains_key("plan-valid"));
    for id in [
        "plan-mut-expected",
        "plan-mut-raw",
        "plan-mut-serial",
        "plan-mut-local",
        "plan-mut-options",
        "plan-mut-unknown",
        "plan-mut-source",
        "plan-mut-mmi-trailing",
        "file-non-object",
        "file-nan",
        "file-duplicate",
        "file-oversize",
        "file-canonical-oversize",
    ] {
        assert_eq!(seen.get(id).map(String::as_str), Some("reject"), "{id}");
    }
}
