//! P3e: `cbus-selected-serial-plan-v1` compatibility vectors.
//!
//! The committed jsonl is the source of truth: one valid plan document
//! (generated by the Python coordinator against its synthetic simulator
//! fixture, ports normalized to 61001, timings frozen to fixed finite
//! constants) plus invalid mutations mirroring the seven Python mutations
//! and file-level guards. Appended rows cover the optional routed
//! `route`/`project_sha256` schema and pin routed attempt IDs. Accepted routed
//! rows embed routed far-network captures (generated by the Python
//! coordinator against scripted Reply Network peers, ports normalized to
//! 61001); rejections pin direct/routed evidence swaps and foreign Reply
//! Networks. The Python suite consumes the same rows. Journal/apply/verify orchestration is out of
//! scope; this tests pure document validation only (no I/O, no clock).

use cbus_transport::apply::attempt_identity_path;
use cbus_transport::plan::{validate_plan_document, MAX_PLAN_BYTES};
use std::collections::HashMap;

/// Attempt-marker file name for one plan, via the public Rust API.
fn marker_name(raw: &[u8]) -> String {
    let path = attempt_identity_path(raw, &std::env::temp_dir().join("vector-probe.json"))
        .expect("accepted vector must have an attempt identity");
    path.file_name().unwrap().to_str().unwrap().to_string()
}

fn load_vectors() -> Vec<serde_json::Value> {
    let text = include_str!("../../testdata/vectors/selected_serial_plan.jsonl");
    text.lines()
        .filter(|line| !line.trim().is_empty())
        .map(|line| serde_json::from_str(line).expect("vector line must be JSON"))
        .collect()
}

#[test]
fn selected_serial_plan_vectors() {
    let vectors = load_vectors();
    assert_eq!(vectors.len(), 40, "expected 40 vector lines");
    let mut seen: HashMap<String, String> = HashMap::new();
    for entry in &vectors {
        let id = entry["id"].as_str().unwrap().to_string();
        let kind = entry["kind"].as_str().unwrap();
        let expect = entry["expect"].as_str().unwrap();
        let want_reason = entry["reason"].as_str().map(str::to_string);
        let result = match kind {
            "plan" => {
                let doc = entry["document"].to_string();
                validate_plan_document(doc.as_bytes())
            }
            "raw" => validate_plan_document(entry["raw"].as_str().unwrap().as_bytes()),
            "oversize" => {
                // Built at test time so the vector file stays small; the
                // bound is MAX_PLAN_BYTES (4MiB) of raw document bytes.
                let big = " ".repeat(MAX_PLAN_BYTES + 1);
                validate_plan_document(big.as_bytes())
            }
            "canonical_oversize" => {
                // Python renders each compact `1e-7` token as `1e-07` when
                // enforcing its second, canonical-representation size bound.
                let mut raw = Vec::with_capacity(3_500_001);
                raw.push(b'[');
                for index in 0..700_000 {
                    if index != 0 {
                        raw.push(b',');
                    }
                    raw.extend_from_slice(b"1e-7");
                }
                raw.push(b']');
                validate_plan_document(&raw)
            }
            other => panic!("unknown vector kind {other}"),
        };
        match expect {
            "accept" => {
                let plan = result.unwrap_or_else(|e| panic!("{id} must accept: {e:?}"));
                assert_eq!(plan.serial, "101136.1558", "{id} serial");
                assert_eq!(plan.destination, 6, "{id} destination");
                assert!(want_reason.is_none());
                let route = entry.get("route").map(|route| {
                    route
                        .as_array()
                        .unwrap()
                        .iter()
                        .map(|bridge| bridge.as_u64().unwrap() as u8)
                        .collect::<Vec<u8>>()
                });
                let expected_request = match &route {
                    Some(bridges) => cbus_protocol::serial_address::encode_serial_address_routed(
                        "101136.1558",
                        6,
                        bridges,
                        plan.command_checksum,
                        b'g',
                    )
                    .unwrap(),
                    None => b"\\05FF000F0018B106160615g\r".to_vec(),
                };
                assert_eq!(plan.request_bytes, expected_request, "{id} request bytes");
                assert_eq!(plan.route, route, "{id} route");
                assert_eq!(
                    plan.project_sha256.as_deref(),
                    entry.get("project_sha256").and_then(|sha| sha.as_str()),
                    "{id} project binding"
                );
                if let Some(attempt_id) = entry.get("attempt_id").and_then(|id| id.as_str()) {
                    let doc = entry["document"].to_string();
                    assert_eq!(
                        marker_name(doc.as_bytes()),
                        format!(
                            ".cbus-selected-serial-attempt-{}.json",
                            attempt_id.replace(':', "-")
                        ),
                        "{id} pinned attempt marker"
                    );
                }
            }
            "reject" => {
                let err = result.unwrap_err();
                assert_eq!(
                    Some(err.reason().to_string()),
                    want_reason,
                    "{id} reason class"
                );
            }
            other => panic!("unknown expectation {other}"),
        }
        seen.insert(id, expect.to_string());
    }
    assert!(seen.contains_key("plan-valid"));
    for id in [
        "plan-mut-expected",
        "plan-mut-raw",
        "plan-mut-serial",
        "plan-mut-local",
        "plan-mut-options",
        "plan-mut-unknown",
        "plan-mut-source",
        "plan-mut-mmi-trailing",
        "file-non-object",
        "file-nan",
        "file-duplicate",
        "file-oversize",
        "file-canonical-oversize",
        "plan-routed-invalid-empty",
        "plan-routed-invalid-seven-bridges",
        "plan-routed-invalid-duplicate-bridge",
        "plan-routed-invalid-bool",
        "plan-routed-unbound",
        "plan-direct-sha256-without-route",
        "plan-routed-local-first-bridge",
        "plan-routed-direct-evidence",
        "plan-direct-routed-evidence",
        "plan-routed-foreign-serial-reply-network",
        "plan-routed-foreign-mmi-reply-network",
    ] {
        assert_eq!(seen.get(id).map(String::as_str), Some("reject"), "{id}");
    }
    for id in [
        "plan-routed-one-bridge",
        "plan-routed-six-bridges",
        "plan-routed-local-address-later-hop",
        "plan-routed-one-bridge-checksum",
    ] {
        assert_eq!(seen.get(id).map(String::as_str), Some("accept"), "{id}");
    }
}

/// Optional route fields must not perturb direct plans: the direct vector
/// keeps its canonical attempt marker, and routed rows differ from it.
#[test]
fn direct_plan_fingerprint_is_unchanged_by_the_routed_schema() {
    let vectors = load_vectors();
    let direct = vectors[0]["document"].to_string();
    let plan = validate_plan_document(direct.as_bytes()).unwrap();
    assert!(!plan.is_routed());
    assert_eq!(plan.project_sha256, None);
    assert_eq!(
        marker_name(direct.as_bytes()),
        ".cbus-selected-serial-attempt-sha256-55af93616aaeacb668e4b52f284a90cba1ccd7792fc77491caf22c44942b98cf.json"
    );
    let routed = vectors
        .iter()
        .find(|entry| entry["id"] == "plan-routed-one-bridge")
        .unwrap();
    assert_ne!(
        marker_name(routed["document"].to_string().as_bytes()),
        marker_name(direct.as_bytes())
    );
}
