"""Literal classic-key/Neo conversion vectors, with no vendor files or endpoints.

Expected values below are transcribed from the recovered original instructions,
not generated by the production transformer or the native acceptance model.
"""
from copy import deepcopy
from dataclasses import FrozenInstanceError, replace
import unittest
from unittest.mock import Mock

from cbus_toolkit import toolkit_conversion_tweakers as tweakers
from cbus_toolkit.toolkit_conversion_key_to_neo import (
    NEOPRO_HOOK_IMMUTABLE, TWEAKER_IMMUTABLE, apply_key_hooks, key_assignments,
)
from cbus_toolkit.unitspec import ParameterSpec, UnitSpec


CLASSIC_TYPES = ('KEY1', 'KEY2', 'KEY4', 'KEYIR1', 'KEYIR4')
COMMON_TARGETS = (
    'KEYB2', 'KEYB4', 'KEYB6', 'KEYH1', 'KEYH2', 'KEYH3', 'KEYH4',
    'KEYM2', 'KEYM4', 'KEYM8', 'KEYA1', 'KEYA3', 'KEYA6', 'KEYA8', 'KEYAV2', 'KEYAV4',
)
ADMITTED_PAIRS = tuple((source, target) for source in CLASSIC_TYPES for target in COMMON_TARGETS) + (
    ('KEY1', 'KEYC1'), ('KEY1', 'KEYC2'), ('KEY1', 'KEYC4'),
    ('KEY2', 'KEYC1'), ('KEY2', 'KEYC2'), ('KEY2', 'KEYC4'),
    ('KEY4', 'KEYC1'), ('KEY4', 'KEYC2'), ('KEY4', 'KEYC4'),
    ('KEYIR1', 'KEYCIR1'), ('KEYIR1', 'KEYCIR4'),
    ('KEYIR4', 'KEYCIR1'), ('KEYIR4', 'KEYCIR4'),
)
REFUSED_COUPLER_PAIRS = (
    ('KEYBC2', 'BCN2B'), ('KEYBC2', 'BCN4B'), ('KEYBC4', 'BCN2B'),
    ('KEYBC4', 'BCN4B'), ('DINAUX4', 'BCI4A'),
)

# Source has eight native group bytes. Slots 5..7 deliberately differ from the
# fifth byte so accidental tail preservation cannot satisfy the expected vector.
SOURCE_GROUPS = '0 10 254 255 173 81 82 83'
EXPECTED_GROUPS = '0x00 0x0A 0xFE 0xFF 0xFF 0xFF 0xFF 0xFF 0xAD'
SOURCE_INDICATORS = '0 1 2 3'
EXPECTED_INDICATORS = '0 2 2 1 '

# Constructor order recovered through inherited calls and the IRBank rename.
# These are constructor flags; BeforeUnitConversionSave later changes brightness
# and LearnedFlag independently of the raw PP default values.
CLASSIC_ATTRIBUTES = (
    ('Application', True), ('FirmwareVersion', False), ('Project', True), ('SerialNo', False),
    ('State', False), ('UnitAddress', True), ('UnitName', True), ('UnitType', False),
    ('LearnAnyApp', True), ('LearnMode', True), ('LearnedFlag', True),
    ('AreaGroupAddress', True), ('StatusReportInterval', True), ('GroupAddress', True),
    ('DebounceTime', True), ('IndicatorBrightness', False), ('LongPressTime', True),
    ('EEPROMLevelStore', True), ('LightIndex', True), ('LightLevel', True),
    ('LightLevelStore1', True), ('LightLevelStore2', True), ('RampRate', True),
    ('InfraRedBank', True), ('JPCommand', True), ('SRCommand', True), ('LPCommand', True),
    ('LRCommand', True), ('BlockAllocation', True), ('IndicatorBlockAssignment', True),
    ('IndicatorFunction', True), ('TimerHighByte', True), ('TimerLowByte', True),
    ('TimerExpiryCommand', True), ('GAVBroadcastFlag', False),
)
NEO_ADDITIONS = (
    'ControlAppGroupAddress', 'EnableNightlight', 'EnableNightlightControl', 'DisableTimerFlash',
    'FirstKeyThrowAway', 'IndicatorPressedLevel', 'TimerDuration', 'PatchEnable',
    'SceneKeySelector', 'SceneTable', 'SceneTablePointer', 'DisableIR',
    'IDBacklightIllumination', 'EnableNightlightOnPCx', 'EnableNightlightOnPA6', 'PrimaryColour',
    'DisableIRNEC', 'KeyDisableGroup', 'KeyDisableGroupInvert', 'CorridorLinkEnable',
    'CorridorMasterGroup', 'CorridorGroupBlock', 'CorridorOfficeGroupBlock',
    'JoinPrimaryApplication', 'JoinSecondaryApplication', 'DualJoinPrimaryApplication',
    'DualJoinSecondaryApplication', 'SecondApplicationBlocks', 'NightlightColour',
)
EXPECTED_TWEAKER_SUPPRESSIONS = (
    'InfraRedBank', 'EnableNightlight', 'EnableNightlightControl', 'DisableTimerFlash',
    'FirstKeyThrowAway', 'IndicatorPressedLevel', 'TimerDuration', 'IDBacklightIllumination',
    'PrimaryColour', 'EnableNightlightOnPCx', 'EnableNightlightOnPA6', 'DisableIR', 'DisableIRNEC',
    'ControlAppGroupAddress', 'PatchEnable', 'SceneKeySelector', 'SceneTable', 'SceneTablePointer',
)
EXPECTED_NEOPRO_SUPPRESSIONS = (
    'DisableIR', 'DisableIRNEC', 'KeyDisableGroup', 'KeyDisableGroupInvert', 'CorridorLinkEnable',
    'CorridorMasterGroup', 'CorridorGroupBlock', 'CorridorOfficeGroupBlock',
    'JoinPrimaryApplication', 'DualJoinPrimaryApplication', 'JoinSecondaryApplication',
    'DualJoinSecondaryApplication', 'SecondApplicationBlocks',
)


def source_values():
    return {
        'Application': '0x38 0xff', 'FirmwareVersion': '0x01 0x02 0x43',
        'Project': 'SYNTH', 'SerialNo': '1 2 3 4', 'State': '3',
        'UnitAddress': '0x14', 'UnitName': 'SRC', 'UnitType': 'KEY4',
        'GroupAddress': SOURCE_GROUPS, 'IndicatorFunction': SOURCE_INDICATORS,
        'IndicatorBrightness': '0xa5', 'LearnAnyApp': '1', 'LearnMode': '1',
        'LearnedFlag': '1', 'DebounceTime': '0x1f', 'LongPressTime': '19',
        'InfraRedBank': '7', 'UnknownNativeOnly': '255',
    }


def plan_for(source=None, *, source_type='KEY4', target_type='KEYB4', target_parameters=None):
    source = source_values() if source is None else source
    parameters = set(source) if target_parameters is None else target_parameters
    return tweakers.plan_writes(source_type, target_type, source, parameters, target_firmware='2.5.00')


def written(plan):
    return {name: value for name, value, _origin in plan.writes}


def synthetic_spec(unit_type, *, source):
    """Public PP shapes required by the bounded constructor, not vendor data."""
    shapes = {
        'Application': ('int', 2, 8), 'GroupAddress': ('int', 8 if source else 9, 8),
        'IndicatorFunction': ('int', 4 if source else 8, 2),
        'IndicatorBrightness': ('int', 1, 8), 'LearnAnyApp': ('bit', 1, 8),
        'LearnMode': ('bit', 1, 8), 'LearnedFlag': ('bit', 1, 8),
    }
    filename = unit_type + '.xml'
    firmware = '1.2.67' if source else '2.5.00'
    return UnitSpec(filename, {'Type': unit_type, 'MinVersion': firmware, 'MaxVersion': firmware},
                    (filename,), {
                        name: ParameterSpec(name, kind, filename, {'ArraySize': str(size), 'BitSize': str(bits)})
                        for name, (kind, size, bits) in shapes.items()
                    })


class NoIO:
    def command(self, *_args, **_kwargs):
        raise AssertionError('validation must fail before C-Gate I/O')

    command_document = command


class KeyToNeoConstructorTests(unittest.TestCase):
    def test_original_constructor_order_and_initial_flags(self):
        expected_neo = tuple(('IRBank' if name == 'InfraRedBank' else name, mutable)
                             for name, mutable in CLASSIC_ATTRIBUTES[:-1]) + tuple(
                                 (name, True) for name in NEO_ADDITIONS)
        self.assertEqual(len(CLASSIC_ATTRIBUTES), 35)
        self.assertEqual(len(expected_neo), 63)
        for unit_type in CLASSIC_TYPES:
            with self.subTest(source=unit_type):
                self.assertEqual(tweakers.AGENT_ATTRIBUTES[unit_type], CLASSIC_ATTRIBUTES)
        for unit_type in (*COMMON_TARGETS, 'KEYC1', 'KEYC2', 'KEYC4', 'KEYCIR1', 'KEYCIR4'):
            with self.subTest(target=unit_type):
                self.assertEqual(tweakers.AGENT_ATTRIBUTES[unit_type], expected_neo)

    def test_literal_suppression_inventories_and_final_mutable_state(self):
        self.assertEqual(TWEAKER_IMMUTABLE, EXPECTED_TWEAKER_SUPPRESSIONS)
        self.assertEqual(NEOPRO_HOOK_IMMUTABLE, EXPECTED_NEOPRO_SUPPRESSIONS)
        values = source_values()
        mutable = {name: True for name in (*EXPECTED_TWEAKER_SUPPRESSIONS, *EXPECTED_NEOPRO_SUPPRESSIONS)}
        mutable.update(LearnedFlag=True, LearnAnyApp=False, LearnMode=False, IndicatorBrightness=False,
                       GroupAddress=True, IndicatorFunction=True, Unrelated=True)
        origin, not_written = {}, {}
        apply_key_hooks(values, mutable, origin, not_written)
        for name in (*EXPECTED_TWEAKER_SUPPRESSIONS, *EXPECTED_NEOPRO_SUPPRESSIONS, 'LearnedFlag'):
            self.assertFalse(mutable[name], name)
            self.assertIn(name, not_written)
        for name in ('LearnAnyApp', 'LearnMode', 'IndicatorBrightness', 'Unrelated'):
            self.assertTrue(mutable[name], name)
            self.assertNotIn(name, not_written)
        self.assertEqual(values['GroupAddress'], EXPECTED_GROUPS)
        self.assertEqual(values['IndicatorFunction'], EXPECTED_INDICATORS)


class KeyToNeoLiteralTests(unittest.TestCase):
    def test_original_tweaker_then_hook_order_and_exact_format(self):
        assignments = key_assignments(source_values())
        self.assertEqual([(name, value) for name, value, _origin in assignments], [
            ('IndicatorFunction', '0 2 2 1 '),
            ('GroupAddress', '0x00 0x0A 0xFE 0xFF 0xFF 0xFF 0xFF 0xFF 0xAD'),
        ])

    def test_independent_boundary_vectors(self):
        vectors = (
            ('0 0 0 0 0 0 0 0', '0 0 0 0',
             '0x00 0x00 0x00 0x00 0xFF 0xFF 0xFF 0xFF 0x00', '0 0 0 0 '),
            ('255 255 255 255 255 255 255 255', '3 3 3 3',
             '0xFF 0xFF 0xFF 0xFF 0xFF 0xFF 0xFF 0xFF 0xFF', '1 1 1 1 '),
            ('254 17 128 1 0 33 34 35', '3 2 1 0',
             '0xFE 0x11 0x80 0x01 0xFF 0xFF 0xFF 0xFF 0x00', '1 2 2 0 '),
            ('$00 0x0a $fe 0xFF $ad 0x51 $52 0x53', '$00 0x01 $02 0x03',
             '0x00 0x0A 0xFE 0xFF 0xFF 0xFF 0xFF 0xFF 0xAD', '0 2 2 1 '),
        )
        for groups, indicators, expected_groups, expected_indicators in vectors:
            with self.subTest(groups=groups, indicators=indicators):
                values = {**source_values(), 'GroupAddress': groups, 'IndicatorFunction': indicators}
                result = written(plan_for(values))
                self.assertEqual(result['GroupAddress'], expected_groups)
                self.assertEqual(result['IndicatorFunction'], expected_indicators)

    def test_all_93_registered_classic_pairs_use_the_literal_vector(self):
        self.assertEqual(len(ADMITTED_PAIRS), 93)
        for source_type, target_type in ADMITTED_PAIRS:
            with self.subTest(source=source_type, target=target_type):
                self.assertEqual(tweakers.admitted(source_type.lower(), target_type.lower()), 'TTweakerKeyToNeo')
                result = written(plan_for(source_type=source_type, target_type=target_type))
                self.assertEqual(result['GroupAddress'], EXPECTED_GROUPS)
                self.assertEqual(result['IndicatorFunction'], EXPECTED_INDICATORS)

    def test_source_and_untransformed_pp_strings_are_preserved(self):
        values = source_values()
        before = deepcopy(values)
        plan = plan_for(values)
        result = written(plan)
        self.assertEqual(values, before)
        for name in ('Application', 'Project', 'UnitAddress', 'UnitName', 'IndicatorBrightness',
                     'LearnAnyApp', 'LearnMode', 'DebounceTime', 'LongPressTime'):
            self.assertEqual(result[name], values[name], name)
        self.assertNotIn('UnknownNativeOnly', result)
        self.assertNotIn('InfraRedBank', result)
        self.assertNotIn('LearnedFlag', result)
        for name in ('FirmwareVersion', 'SerialNo', 'State', 'UnitType'):
            self.assertEqual(plan.not_written[name], 'initially immutable agent attribute', name)
        self.assertIn('LearnedFlag', plan.not_written)
        with self.assertRaises(TypeError):
            plan.not_written['LearnedFlag'] = 'mutable'
        with self.assertRaises(FrozenInstanceError):
            plan.target_type = 'KEY4'

    def test_native_parameter_gate_keeps_the_other_transform(self):
        values = source_values()
        for missing, retained, expected in (
            ('GroupAddress', 'IndicatorFunction', EXPECTED_INDICATORS),
            ('IndicatorFunction', 'GroupAddress', EXPECTED_GROUPS),
        ):
            with self.subTest(missing=missing):
                plan = plan_for(values, target_parameters=set(values) - {missing})
                self.assertNotIn(missing, written(plan))
                self.assertEqual(written(plan)[retained], expected)
                self.assertIn('no native target parameter', plan.not_written[missing])

    def test_empty_untransformed_attribute_does_not_gain_a_write(self):
        plan = plan_for({**source_values(), 'DebounceTime': '', 'LongPressTime': ''})
        for name in ('DebounceTime', 'LongPressTime'):
            self.assertNotIn(name, written(plan))
            self.assertIn('empty source value', plan.not_written[name])

    def test_constructor_pp_order_differs_from_original_transform_setter_order(self):
        plan = plan_for()
        self.assertEqual([name for name, _value, _origin in plan.writes], [
            'Application', 'Project', 'UnitAddress', 'UnitName', 'LearnAnyApp', 'LearnMode',
            'GroupAddress', 'DebounceTime', 'IndicatorBrightness', 'LongPressTime', 'IndicatorFunction',
        ])

    def test_renamed_irbank_and_neo_only_values_keep_the_fresh_target(self):
        values = {**source_values(), 'IRBank': '6', 'NightlightColour': '7', 'SceneTable': '88',
                  'KeyDisableGroup': '51', 'GAVBroadcastFlag': '1'}
        plan = plan_for(values)
        result = written(plan)
        for name in ('IRBank', 'InfraRedBank', 'NightlightColour', 'SceneTable', 'KeyDisableGroup',
                     'GAVBroadcastFlag'):
            self.assertNotIn(name, result)
        for name in ('IRBank', 'NightlightColour'):
            self.assertIn('no source agent attribute', plan.not_written[name])

    def test_four_indicator_results_preserve_the_unwritten_target_tail(self):
        spec = synthetic_spec('KEYB4', source=False)
        defaults = {
            'Application': '1 2', 'GroupAddress': '9 9 9 9 9 9 9 9 9',
            'IndicatorFunction': '3 3 3 3 1 2 3 0', 'IndicatorBrightness': '17',
            'LearnAnyApp': '0', 'LearnMode': '0', 'LearnedFlag': '0',
        }
        before = deepcopy(defaults)
        plan = plan_for(target_parameters=set(spec.parameters))
        expected = tweakers.expected_values(spec, defaults, plan)
        self.assertEqual(expected['GroupAddress'], (0, 10, 254, 255, 255, 255, 255, 255, 173))
        self.assertEqual(expected['IndicatorFunction'], (0, 2, 2, 1, 1, 2, 3, 0))
        self.assertEqual(expected['IndicatorBrightness'], (165,))
        self.assertEqual(expected['LearnAnyApp'], (1,))
        self.assertEqual(expected['LearnMode'], (1,))
        self.assertEqual(expected['LearnedFlag'], (0,))
        self.assertEqual(defaults, before)

    def test_missing_partial_malformed_and_out_of_range_consumed_values_are_refused(self):
        malformed = (
            ('GroupAddress', ''), ('GroupAddress', '0 1 2 3 4 5 6'),
            ('GroupAddress', '0 1 2 3 4 5 6 7 8'), ('GroupAddress', '-1 1 2 3 4 5 6 7'),
            ('GroupAddress', '256 1 2 3 4 5 6 7'), ('GroupAddress', '0.0 1 2 3 4 5 6 7'),
            ('GroupAddress', 'oops 1 2 3 4 5 6 7'), ('GroupAddress', [0] * 8),
            ('IndicatorFunction', ''), ('IndicatorFunction', '0 1 2'),
            ('IndicatorFunction', '0 1 2 3 0'), ('IndicatorFunction', '0 1 2 4'),
            ('IndicatorFunction', '0 1 2 -1'), ('IndicatorFunction', '0 1 2 1.0'),
            ('IndicatorFunction', '0 1 2 oops'), ('IndicatorFunction', (0, 1, 2, 3)),
        )
        for name, value in malformed:
            with self.subTest(parameter=name, value=value):
                with self.assertRaises(tweakers.TweakerConversionError):
                    plan_for({**source_values(), name: value})
        for name in ('GroupAddress', 'IndicatorFunction'):
            with self.subTest(missing=name):
                values = source_values()
                del values[name]
                with self.assertRaises(tweakers.TweakerConversionError):
                    plan_for(values)


class KeyToNeoGuardTests(unittest.TestCase):
    def test_five_registered_coupler_pairs_reject_the_classic_target_profile(self):
        for source_type, target_type in REFUSED_COUPLER_PAIRS:
            with self.subTest(source=source_type, target=target_type):
                self.assertEqual(tweakers.lookup(source_type, target_type), 'TTweakerKeyToNeo')
                with self.assertRaises(tweakers.TweakerConversionError):
                    tweakers.plan_writes(source_type, target_type, source_values(), set(source_values()),
                                         target_firmware='2.5.00')

    def test_recovered_key_rules_do_not_broaden_other_hooks_or_unregistered_pairs(self):
        for source_type, target_type in (
            ('KEYIR1', 'KEY2'), ('KEYC1', 'KEY1'), ('KEY1', 'KEYDL4'),
            ('KEYM2', 'KEYDL4'), ('SENPIRSS', 'SENPIRIA'), ('PC_DAL2', 'PC_DAL2B'),
            ('KEY1', 'KEYCIR1'), ('KEYIR1', 'KEYC1'), ('KEY1', 'KEYM6'),
        ):
            with self.subTest(source=source_type, target=target_type):
                with self.assertRaises(tweakers.TweakerRefused):
                    tweakers.ToolkitTweakerConversion(NoIO(), source_type, None, target_type, None)

    def test_pure_plan_requires_the_exact_fresh_target_firmware(self):
        values = source_values()
        for firmware in (None, '', '2.4.00', '2.5.0', '2.5.01', '3.0.00'):
            with self.subTest(firmware=firmware):
                with self.assertRaises(tweakers.TweakerConversionError):
                    tweakers.plan_writes('KEY4', 'KEYB4', values, set(values), target_firmware=firmware)

    def test_matching_bounded_specs_construct_without_io(self):
        for source_type, target_type in ADMITTED_PAIRS:
            with self.subTest(source=source_type, target=target_type):
                converter = tweakers.ToolkitTweakerConversion(
                    NoIO(), source_type, synthetic_spec(source_type, source=True),
                    target_type, synthetic_spec(target_type, source=False))
                self.assertEqual(converter.tweaker, 'TTweakerKeyToNeo')

    def test_missing_wrong_type_filename_firmware_or_parameter_shape_is_refused_before_io(self):
        for source in (True, False):
            unit_type = 'KEY4' if source else 'KEYB4'
            valid = synthetic_spec(unit_type, source=source)
            invalid = [
                None,
                replace(valid, filename='other.xml'),
                replace(valid, metadata={**valid.metadata, 'Type': 'KEY2' if source else 'KEYB2'}),
                replace(valid, metadata={**valid.metadata, 'MinVersion': '9.0.00', 'MaxVersion': '9.0.00'}),
            ]
            for name, parameter in valid.parameters.items():
                invalid.append(replace(valid, parameters={key: item for key, item in valid.parameters.items()
                                                          if key != name}))
                for field, value in (('ArraySize', '17'), ('BitSize', '16')):
                    changed = replace(parameter, fields={**parameter.fields, field: value})
                    invalid.append(replace(valid, parameters={**valid.parameters, name: changed}))
                invalid.append(replace(valid, parameters={**valid.parameters,
                                                          name: replace(parameter, type='sixbit')}))
            for index, spec in enumerate(invalid):
                with self.subTest(source=source, case=index):
                    source_spec = spec if source else synthetic_spec('KEY4', source=True)
                    target_spec = synthetic_spec('KEYB4', source=False) if source else spec
                    with self.assertRaises(tweakers.TweakerConversionError):
                        tweakers.ToolkitTweakerConversion(NoIO(), 'KEY4', source_spec, 'KEYB4', target_spec)


class ScriptedSession:
    """Record staging while supplying independent source/default/readback images."""
    def __init__(self, values, *, set_error=None):
        self.current = dict(values)
        self.set_error = set_error
        self.sets = []
        self.saves = 0

    def __enter__(self):
        return self

    def __exit__(self, *_args):
        return False

    def values(self):
        return dict(self.current)

    def set(self, name, value):
        self.sets.append((name, value))
        if name == 'GroupAddress' and self.set_error is not None:
            raise self.set_error

    def save_to_source(self):
        self.saves += 1


class KeyToNeoApplyTests(unittest.TestCase):
    def make_converter(self, *, source=None, source_firmware='1.2.67', set_error=None):
        converter = tweakers.ToolkitTweakerConversion(
            NoIO(), 'KEY4', synthetic_spec('KEY4', source=True),
            'KEYB4', synthetic_spec('KEYB4', source=False))
        source = {**source_values(), 'LearnedFlag': '0'} if source is None else source
        source_session = ScriptedSession(source)
        target_session = ScriptedSession({
            'Application': '56 255', 'GroupAddress': '255 255 255 255 255 255 255 255 255',
            'IndicatorFunction': '3 3 3 3 1 2 3 0', 'IndicatorBrightness': '17',
            'LearnAnyApp': '0', 'LearnMode': '0', 'LearnedFlag': '1',
        }, set_error=set_error)
        readback_session = ScriptedSession({
            'Application': '56 255', 'GroupAddress': '0 10 254 255 255 255 255 255 173',
            'IndicatorFunction': '0 2 2 1 1 2 3 0', 'IndicatorBrightness': '165',
            'LearnAnyApp': '1', 'LearnMode': '1', 'LearnedFlag': '1',
        })
        converter._unit_type = Mock(return_value='KEY4')
        converter._unit_firmware = Mock(return_value=source_firmware)
        converter.programmer = Mock()
        converter.programmer.load.side_effect = (source_session, target_session, readback_session)
        converter.database = Mock()
        return converter, source_session, target_session

    @staticmethod
    def apply(converter, *, target_firmware='2.5.00'):
        return converter.apply('//SYNTH/254/p/20', 21, target_firmware=target_firmware,
                               target_catalog='SYNTHETIC')

    def test_target_firmware_refusal_precedes_all_metadata_and_pp_io(self):
        for firmware in ('', '2.4.00', '2.5.0', '2.5.01', None):
            with self.subTest(firmware=firmware):
                converter, source, target = self.make_converter()
                with self.assertRaises(tweakers.TweakerConversionError):
                    self.apply(converter, target_firmware=firmware)
                converter._unit_type.assert_not_called()
                converter._unit_firmware.assert_not_called()
                converter.programmer.load.assert_not_called()
                converter.database.create_unit.assert_not_called()
                self.assertEqual((source.sets, target.sets, target.saves), ([], [], 0))

    def test_source_firmware_refusal_precedes_pp_load_and_target_creation(self):
        for firmware in ('', '1.2.63', '1.2.66', '1.2.68', '2.5.00', '1.2.067'):
            with self.subTest(firmware=firmware):
                converter, source, target = self.make_converter(source_firmware=firmware)
                with self.assertRaises(tweakers.TweakerConversionError):
                    self.apply(converter)
                converter._unit_type.assert_called_once_with('//SYNTH/254/p/20')
                converter._unit_firmware.assert_called_once_with('//SYNTH/254/p/20')
                converter.programmer.load.assert_not_called()
                converter.database.create_unit.assert_not_called()
                self.assertEqual((source.sets, target.sets, target.saves), ([], [], 0))

    def test_malformed_source_refusal_follows_one_read_and_precedes_target_creation(self):
        for name, value in (('GroupAddress', '0 1 2 3 4'), ('GroupAddress', '256 1 2 3 4 5 6 7'),
                            ('IndicatorFunction', '0 1 2'), ('IndicatorFunction', '0 1 2 4')):
            with self.subTest(parameter=name, value=value):
                values = {**source_values(), name: value}
                converter, source, target = self.make_converter(source=values)
                with self.assertRaises(tweakers.TweakerConversionError):
                    self.apply(converter)
                converter.programmer.load.assert_called_once_with('//SYNTH/254', '/db//SYNTH/254/p/20')
                converter.database.create_unit.assert_not_called()
                self.assertEqual(source.current, values)
                self.assertEqual((source.sets, target.sets, target.saves), ([], [], 0))

    def test_apply_uses_constructor_order_once_and_reads_back_without_source_mutation(self):
        converter, source, target = self.make_converter()
        before = deepcopy(source.current)
        result = self.apply(converter)
        self.assertEqual(target.sets, [
            ('Application', '0x38 0xff'), ('LearnAnyApp', '1'), ('LearnMode', '1'),
            ('GroupAddress', '0x00 0x0A 0xFE 0xFF 0xFF 0xFF 0xFF 0xFF 0xAD'),
            ('IndicatorBrightness', '0xa5'), ('IndicatorFunction', '0 2 2 1 '),
        ])
        self.assertEqual(target.saves, 1)
        self.assertEqual(converter.programmer.load.call_count, 3)
        converter.database.create_unit.assert_called_once_with(
            '//SYNTH/254', 21, 'Tweaked21', 'KEYB4', '2.5.00', catalog_number='SYNTHETIC')
        self.assertEqual(source.current, before)
        self.assertEqual(source.sets, [])
        self.assertEqual(source.saves, 0)
        self.assertEqual(result['failed_writes'], {})
        self.assertEqual(result['verified_parameters'], 7)
        self.assertTrue(result['saved_to_database'])
        for field in ('project_saved', 'source_deleted', 'readdressed', 'hardware_programmed'):
            self.assertFalse(result[field], field)

    def test_uncertain_transport_failure_stops_before_save_or_readback(self):
        error = OSError('connection lost after sending PP SET')
        converter, source, target = self.make_converter(set_error=error)
        with self.assertRaises(OSError) as caught:
            self.apply(converter)
        self.assertIs(caught.exception, error)
        self.assertEqual([name for name, _value in target.sets], [
            'Application', 'LearnAnyApp', 'LearnMode', 'GroupAddress',
        ])
        self.assertEqual(target.saves, 0)
        self.assertEqual(converter.programmer.load.call_count, 2)
        self.assertEqual(source.sets, [])


if __name__ == '__main__':
    unittest.main()
