"""Independent original-DLL widget vectors, PP preservation and native CRCs."""
from dataclasses import replace
import hashlib
import json
import os
from pathlib import Path
import subprocess
import tempfile
from types import SimpleNamespace
import unittest
from uuid import uuid4
import xml.etree.ElementTree as ET

from cbus_toolkit.edlt import EdltLighting, EdltError, EdltApplyError, configuration_crc
from cbus_toolkit.unitspec import ParameterSpec, UnitSpec, UnitSpecStore


# Output from unchanged CBusLogicModel.dll LightingData properties, executed
# by research/NativeEdltProbe.cs. These are not generated by the Python helper.
DEFAULT = '020002010000FF0F1001FFFF1900000000000000000000000000000000000000'
OFF_ON = '02B2020100002A0A0901FFFF1901000000000000000000000000000000000000'
DIMMER = '02B2020100002A0F10047FC81F01000000000000000000000000000000000000'


def fixture():
    parameters = {}
    def add(name, address, count=1, default=None, bits=8):
        values = default if default is not None else [0] * count
        fields = {'Name': name, 'Type': 'int', 'Address': hex(address), 'ArraySize': str(count),
                  'BitSize': str(bits), 'DefaultValue': ' '.join(map(str, values))}
        parameters[name] = ParameterSpec(name, 'int', 'synthetic.xml', fields)
    for name, address, count, values in (
            ('Application', 0x21, 2, [255, 255]), ('ConfigVersionMinor', 0x100, 1, [255]),
            ('ConfigVersionMajor', 0x101, 1, [255]), ('OverallCRC', 0x102, 2, [255, 255]),
            ('GlobalParameterCRC', 0x104, 2, [255, 255]), ('WidgetsCRC', 0x106, 2, [255, 255]),
            ('StaticTextCRC', 0x108, 2, [255, 255]), ('ScenesCheckSum', 0x10a, 2, [255, 255]),
            ('PrimaryApplication', 0x110, 1, [56]), ('SecondaryApplication', 0x111, 1, [57]),
            ('NavWidgetType', 0x200, 1, [255])):
        add(name, address, count, values)
    for widget in range(1, 22):
        base = 0x220 + (widget - 1) * 32
        add(f'Widget{widget}WidgetType', base, default=[255])
        for index in range(1, 32):
            add(f'Widget{widget}WidgetByteValue{index}', base + index)
        if widget >= 6:
            add(f'Widget{widget}RestoreLevel', 0x1a0 + widget - 6)
    for index in range(64):
        text = (b'Light', b'Lamp')[index] if index < 2 else b''
        add(f'StaticTextString{index}', 0x1100 + index * 64, 64, list(text.ljust(64, b'\0')))
    # Explicit unrelated synthetic state in each CRC region, not vendor defaults.
    add('NavWidgetVariant', 0x201, bits=4)
    add('SceneCount', 0x2100)
    for index in range(1, 5): add(f'PageNameIndex{index}', 0x204 + index)
    for index in range(1, 9): add(f'Scene{index}StartAddress', 0x2100 + 2 * index, default=[65535], bits=16)
    add('SceneBucket', 0x2112, 232, [0xa5] * 232)
    add('UnrelatedGlobal', 0x17f, default=[0x67])
    return UnitSpec('KEYGL5.xml', {'Type': 'KEYGL5'}, ('synthetic.xml',), parameters)


class Session:
    source = '/db//EDLTTEST/254/p/20'
    def __init__(self, spec):
        self.spec, self.current, self.calls = spec, spec.defaults(), []
        self.failure = None
        self.programmer = SimpleNamespace(client=self)
        self.identity = {'UnitType': 'KEYGL5', 'FirmwareVersion': '5.5.00', 'CatalogNumber': '5055EDL'}

    def command(self, command):
        field = command.rsplit('/', 1)[1]
        return SimpleNamespace(lines=(f'342 {field}={self.identity[field]}',))

    def values(self):
        return dict(self.current)

    def info(self, name):
        root = ET.Element('Parameters')
        for parameter in self.spec.parameters.values():
            element = ET.SubElement(root, 'Param')
            for key, value in parameter.fields.items():
                ET.SubElement(element, key).text = value
        return SimpleNamespace(lines=('347-' + ET.tostring(root, encoding='unicode'), '344 End XML'))

    def set(self, name, value):
        self.calls.append((name, value))
        self.current[name] = value
        if self.failure == name:
            self.failure = None
            raise RuntimeError('Injected mutation followed by failure')


class EdltTests(unittest.TestCase):
    def setUp(self):
        self.spec = fixture()
        self.editor = EdltLighting(self.spec)
        self.session = Session(self.spec)

    def plan(self, current=None, **options):
        return self.editor.plan(self.session.values() if current is None else current,
                                **dict(page=1, position=1, group=42, mode='dimmer', **options))

    def test_original_dll_crc_vectors(self):
        for value, expected in ((b'', 0xfa50), (bytes.fromhex('000102ff'), 0xe68a), (b'123456789', 0x0156)):
            self.assertEqual(configuration_crc(value), expected)

    def test_default_and_two_original_lighting_records(self):
        default = bytearray.fromhex(DEFAULT); default[6] = 42
        self.assertEqual(self.plan().record, bytes(default))
        off = self.editor.plan(self.session.values(), page=1, position=1, group=42, mode='off-on',
                               application='secondary', label_text='Lamp', status_type='percent')
        self.assertEqual(off.record.hex().upper(), OFF_ON)
        current = dict(off.expected); current.update(off.changes)
        # These three existing fields are inactive for the selected macros.
        # Explicit fixture state proves changing mode/ramp preserves them.
        for offset, value in ((10, 127), (11, 200), (12, 31)):
            current[f'Widget6WidgetByteValue{offset}'] = (value,)
        dim = self.editor.plan(current, page=1, position=1, group=42, mode='dimmer',
                               application='secondary', ramp_seconds=20)
        self.assertEqual(dim.record.hex().upper(), DIMMER)

    def test_four_pages_and_single_page_fifth_position(self):
        for page, position, widget in ((1, 1, 6), (1, 4, 9), (2, 1, 10), (3, 4, 17), (4, 4, 21)):
            plan = self.editor.plan(self.session.values(), page=page, position=position, group=9,
                                    mode='off-on', page_mode='multiple')
            self.assertEqual(plan.widget, widget)
            updated = dict(plan.expected); updated.update(plan.changes)
            for preceding in range(6, widget):
                self.assertEqual(updated[f'Widget{preceding}WidgetType'], (0,))
            if widget < 21:
                self.assertEqual(updated[f'Widget{widget + 1}WidgetType'], (255,))
        self.assertEqual(self.editor.plan(self.session.values(), page=1, position=5, group=9,
                                          mode='off-on').widget, 10)

    def test_unrelated_widgets_scenes_and_opaque_selected_bytes_are_preserved(self):
        current = self.session.values()
        current.update({'Widget1WidgetType': '7', 'Widget6WidgetType': '3',
                        'Widget6WidgetByteValue9': '65', 'Widget7WidgetByteValue4': '82',
                        'Widget7WidgetByteValue31': '113', 'Widget7WidgetByteValue13': '12',
                        'Widget7WidgetByteValue14': '15'})
        plan = self.editor.plan(current, page=1, position=2, group=22, mode='dimmer', restore_level=127)
        updated = dict(plan.expected); updated.update(plan.changes)
        for name in ('Widget1WidgetType', 'Widget6WidgetType', 'Widget6WidgetByteValue9',
                     'Widget7WidgetByteValue4', 'Widget7WidgetByteValue31', 'Widget7WidgetByteValue13',
                     'Widget7WidgetByteValue14', 'SceneBucket', 'UnrelatedGlobal'):
            self.assertEqual(updated[name], plan.expected[name])
        self.assertEqual(updated['Widget7RestoreLevel'], (127,))
        self.assertEqual(updated['Application'], (56, 57))
        self.assertEqual(updated['ConfigVersionMajor'], (1,))
        self.assertEqual(updated['ConfigVersionMinor'], (0,))
        self.assertTrue(set(plan.changes) & {'OverallCRC', 'WidgetsCRC'})

    def test_labels_status_and_ramp_indices(self):
        plan = self.plan(label_type='dynamic-text', label_index=3, status_type='dynamic-icon', status_index=2,
                         ramp_seconds=1020)
        self.assertEqual((plan.record[1], plan.record[9], plan.record[13], plan.record[14]), (0x17, 15, 3, 2))
        changed = dict(plan.expected); changed.update(plan.changes)
        switched = self.plan(changed, label_type='dynamic-icon', status_type='dynamic-text')
        self.assertEqual((switched.record[13], switched.record[14]), (3, 2))
        other = self.plan(changed, label_type='static', status_type='percent')
        self.assertEqual((other.record[1], other.record[13], other.record[14]), (0x32, 0, 0))

    def test_invalid_inputs_do_not_mutate_session(self):
        for option in ({'page': 0}, {'page': 2}, {'position': 6}, {'page_mode': 'multiple', 'position': 5},
                       {'page': True}, {'group': 255}, {'mode': 'toggle'}, {'application': '56'},
                       {'label_text': 'A' * 64}, {'label_type': 'static', 'label_index': 64},
                       {'label_type': 'dynamic-icon', 'label_index': 4}, {'status_type': 'level', 'status_index': 1},
                       {'ramp_seconds': 5}, {'mode': 'off-on', 'ramp_seconds': 4}, {'restore_level': -1}):
            options = dict(page=1, position=1, group=42, mode='dimmer'); options.update(option)
            with self.subTest(option=option), self.assertRaises(EdltError):
                self.editor.configure(self.session, **options)
        self.assertEqual(self.session.calls, [])

    def test_unknown_layout_missing_values_hidden_widget_and_group_change_are_rejected(self):
        for options in ({'catalog_number': '5085EDL'}, {'firmware': '6.0.00'}):
            with self.assertRaises(EdltError): EdltLighting(self.spec, **options)
        current = self.session.values(); del current['SceneBucket']
        with self.assertRaises(EdltError): self.plan(current)
        current = self.session.values(); current['Widget7WidgetType'] = '2'
        with self.assertRaises(EdltError): self.plan(current)
        plan = self.plan(); updated = dict(plan.expected); updated.update(plan.changes)
        with self.assertRaises(EdltError):
            self.editor.plan(updated, page=1, position=1, group=43, mode='dimmer')

    def test_apply_verifies_every_value_and_rolls_back_partial_failure(self):
        plan = self.plan(label_text='Lamp')
        original = self.editor.snapshot(self.session.values())
        self.session.failure = 'Widget6WidgetByteValue7'
        with self.assertRaises(EdltApplyError) as caught:
            self.editor.apply(self.session, plan)
        self.assertEqual(caught.exception.rollback_errors, ())
        self.assertEqual(self.editor.snapshot(self.session.values()), original)
        result = self.editor.apply(self.session, plan)
        self.assertTrue(result['verified']); self.assertFalse(result['saved'])
        expected = dict(plan.expected); expected.update(plan.changes)
        self.assertEqual(self.editor.snapshot(self.session.values()), expected)

    def test_stale_snapshot_device_identity_and_unrelated_plan_edits_are_rejected(self):
        plan = self.plan()
        self.session.current['SceneBucket'] = '0 ' * 20
        with self.assertRaises(EdltError): self.editor.apply(self.session, plan)
        self.session = Session(self.spec); self.session.identity['FirmwareVersion'] = '6.0.00'
        with self.assertRaises(EdltError): self.editor.apply(self.session, plan)
        self.session = Session(self.spec)
        forged = dict(plan.changes); forged['SceneBucket'] = (0,) * 20
        with self.assertRaises(EdltError): self.editor.apply(self.session, replace(plan, changes=forged))
        self.assertEqual(self.session.calls, [])

    def test_disconnected_write_has_no_rollback_or_verification_io(self):
        plan = self.plan()
        original_set = self.session.set
        def fail(name, value):
            original_set(name, value)
            self.session.connected = False
            raise TimeoutError('Injected framing loss')
        self.session.set = fail
        with self.assertRaises(EdltApplyError) as caught:
            self.editor.apply(self.session, plan)
        self.assertEqual(len(self.session.calls), 1)
        self.assertEqual(caught.exception.attempted_parameters, (self.session.calls[0][0],))
        self.assertFalse(caught.exception.saved)
        self.assertIn('Connection lost', caught.exception.rollback_errors[0])
        self.assertEqual(caught.exception.details, caught.exception.as_dict())

    def test_plan_boundaries_and_wrong_identity_precede_parameter_reads(self):
        plan = self.plan()
        for invalid in (None, replace(plan, widget=22), replace(plan, widget=True),
                        replace(plan, position=2), replace(plan, record=b'bad')):
            with self.subTest(invalid=type(invalid)), self.assertRaises(EdltError):
                self.editor.apply(self.session, invalid)
        self.session.identity['UnitType'] = 'KEY4'
        self.session.values = lambda: self.fail('Identity must be checked before reading values')
        with self.assertRaisesRegex(EdltError, 'identity'):
            self.editor.configure(self.session, page=1, position=1, group=2, mode='dimmer')


@unittest.skipUnless(all(os.environ.get(key) for key in ('CBUS_CGATE_TEST_HOST', 'CBUS_UNITSPEC_DIR', 'CBUS_TOOLKIT_EXE')),
                     'Set C-Gate host, unit specifications and Toolkit EXE for original-DLL/native eDLT acceptance')
class NativeEdltTests(unittest.TestCase):
    def test_default_widget_pp_bytes_crc_original_dll_and_saved_project_reload(self):
        from cbus_toolkit.cgate import CGateClient
        from cbus_toolkit.programming import Programmer
        from research.original_oracle import OriginalModelOracle, selected_backend
        spec_path = Path(os.environ['CBUS_UNITSPEC_DIR']).resolve()
        spec = UnitSpecStore(spec_path).load('KEYGL5.xml')
        editor = EdltLighting(spec)
        project = 'EDL' + uuid4().hex[:5].upper()
        network, unit = f'//{project}/254', f'//{project}/254/p/20'
        root = Path(__file__).resolve().parents[1]
        report = {'project': project, 'scope': '5055EDL5.5 database PP widgets and original Toolkit DLL CRC; no physical eDLT', 'passed': False}
        backend = selected_backend(); report['original_backend'] = backend
        with tempfile.TemporaryDirectory() as folder, CGateClient(os.environ['CBUS_CGATE_TEST_HOST'],
                int(os.environ.get('CBUS_CGATE_TEST_PORT', '20023')), timeout=30) as client:
            client.command('PROJECT NEW ' + project)
            try:
                for text in ('PROJECT USE ' + project, f'DBSET //{project}/Project/Description cbus-toolkit-isolated-edlt-v1',
                             'DBCREATENET 254 Offline Cni 127.0.0.1:1', 'PROJECT SAVE ' + project,
                             f'DBADDSAFE {network} Unit 20 EDLT'):
                    client.command(text)
                for key, value in (('UnitType', 'KEYGL5'), ('UnitName', 'EDLT'), ('FirmwareVersion', '5.5.00'), ('CatalogNumber', '5055EDL')):
                    client.command(f'DBSET {unit}/{key} {value}')
                client.command('NET LOAD DB ' + project)
                programmer = Programmer(client)
                with programmer.load(network, '/db' + unit) as session:
                    session.reset_defaults()
                    defaults = session.values()
                    self.assertEqual(editor.crcs(defaults), {'OverallCRC': (0x6e, 0x20), 'GlobalParameterCRC': (0xfd, 0x47),
                        'WidgetsCRC': (0x30, 0xd7), 'StaticTextCRC': (0x66, 0x79), 'ScenesCheckSum': (0xb8, 6)})
                    first = editor.plan(defaults, page=1, position=1, group=42, mode='off-on', label_text='Lamp', status_type='percent')
                    self.assertTrue(editor.apply(session, first)['verified'])
                    self.assertEqual(session.get_raw_data(0x2c0, 32).lines[-1].split('RawData=')[1],
                                     OFF_ON.lower()[:2] + '32' + OFF_ON.lower()[4:])
                    second = editor.plan(session.values(), page=4, position=4, group=9, mode='dimmer',
                                         page_mode='multiple', ramp_seconds=20, restore_level=127,
                                         label_type='dynamic-text', label_index=2, status_type='bar')
                    self.assertTrue(editor.apply(session, second)['verified'])
                    final = editor.snapshot(session.values())
                    self.assertEqual(session.get_raw_data(0x4a0, 32).lines[-1].split('RawData=')[1], second.record.hex())
                    self.assertEqual([final[f'Widget6WidgetByteValue{i}'][0] for i in range(1, 32)], list(first.record[1:]))
                    for name in defaults:
                        if name.startswith('Scene') and name != 'ScenesCheckSum' or name.startswith('StaticTextString'):
                            self.assertEqual(final[name], editor.snapshot(defaults)[name])
                    allocation = editor.plan(session.values(), page=1, position=1, group=42, mode='off-on',
                                             label_text='Māori Lounge', status_text='Room state')
                    self.assertEqual(allocation.static_allocation.index, 63)
                    self.assertEqual(allocation.status_allocation.index, 62)
                    self.assertTrue(editor.apply(session, allocation)['verified'])
                    allocated = editor.snapshot(session.values())
                    text_bytes = 'Māori Lounge'.encode('utf-8').ljust(64, b'\0')
                    self.assertEqual(session.get_raw_data(0x20c0, 64).lines[-1].split('RawData=')[1], text_bytes.hex())
                    self.assertEqual(allocated['StaticTextString63'], tuple(text_bytes))
                    status_bytes = b'Room state'.ljust(64, b'\0')
                    self.assertEqual(session.get_raw_data(0x2080, 64).lines[-1].split('RawData=')[1], status_bytes.hex())
                    self.assertEqual(allocated['StaticTextString62'], tuple(status_bytes))
                    for name in final:
                        if name not in allocation.changes:
                            self.assertEqual(allocated[name], final[name])
                    self.assertTrue(editor.allocate_static_text(allocated, 'Māori Lounge').reused)
                    shared = editor.plan(session.values(), page=1, position=1, group=42, mode='off-on',
                                         label_text='Māori Lounge', status_text='Māori Lounge')
                    self.assertTrue(shared.static_allocation.reused)
                    self.assertTrue(shared.status_allocation.reused)
                    self.assertEqual((shared.record[13], shared.record[14]), (63, 63))
                    self.assertTrue(editor.apply(session, shared)['verified'])
                    self.assertEqual(session.get_raw_data(0x2cd, 2).lines[-1].split('RawData=')[1], '3f3f')
                    final = editor.snapshot(session.values())
                    self.assertEqual(final['StaticTextString62'], allocated['StaticTextString62'])
                    source = Path(folder) / 'NativeEdltProbe.cs'
                    source.write_bytes((root / 'research/NativeEdltProbe.cs').read_bytes())
                    Path(folder, 'NativeEdltStaticProbe.cs').write_bytes((root / 'research/NativeEdltStaticProbe.cs').read_bytes())
                    Path(folder, 'KEYGL5.xml').write_bytes((spec_path / 'KEYGL5.xml').read_bytes())
                    Path(folder, 'values.tsv').write_text(''.join(name + '\t' + (value if isinstance(value, str) else
                        ' '.join(hex(n) for n in value)) + '\n' for name, value in final.items()))
                    app = Path(os.environ['CBUS_TOOLKIT_EXE']).resolve().parent
                    if backend == 'windows':
                        with OriginalModelOracle(root / 'research/NativeEdltProbe.cs', app, backend='windows') as crc_oracle, \
                                OriginalModelOracle(root / 'research/NativeEdltStaticProbe.cs', app, backend='windows') as static_oracle:
                            first_result = crc_oracle.run_result(('KEYGL5.xml', 'values.tsv'),
                                files={name: Path(folder, name).read_bytes() for name in ('KEYGL5.xml', 'values.tsv')})
                            second_result = static_oracle.run_result() if first_result.returncode == 0 else None
                            run = subprocess.CompletedProcess([], second_result.returncode if second_result is not None else first_result.returncode,
                                first_result.stdout + (second_result.stdout if second_result is not None else ''),
                                first_result.stderr + (second_result.stderr if second_result is not None else ''))
                    else:
                        run = subprocess.run(['docker', 'run', '--rm', '-v', str(app) + ':/input:ro', '-v', folder + ':/work', '-w', '/work',
                            'mono@sha256:34d816779b1248b5cfd095770b64ecbaf1798e2aca693a91c11a018dce9c7ad5', 'sh', '-c',
                            'mcs -r:/input/CBusLogicModel.dll -r:System.Windows.Forms -r:System.Xml.Linq NativeEdltProbe.cs && '
                            'MONO_PATH=/input mono NativeEdltProbe.exe KEYGL5.xml values.tsv && '
                            'mcs -r:/input/CBusLogicModel.dll -r:System.Windows.Forms NativeEdltStaticProbe.cs && '
                            'MONO_PATH=/input mono NativeEdltStaticProbe.exe'], capture_output=True, text=True, timeout=60)
                    self.assertEqual(run.returncode, 0, run.stdout + run.stderr)
                    native_crcs = {}
                    for line in run.stdout.splitlines():
                        if line.startswith('pp-crc:'):
                            _, name, value = line.split(':'); native_crcs[name] = tuple(int(v, 16) for v in value.split())
                    self.assertEqual(native_crcs, editor.crcs(final))
                    for record in (DEFAULT, OFF_ON, DIMMER): self.assertIn(':' + record + ':0', run.stdout)
                    from test_edlt_static import REFERENCE_VECTORS, BLANK_VECTORS
                    for prefix, vectors in (('references', REFERENCE_VECTORS), ('references-blank', BLANK_VECTORS)):
                        parsed = {}
                        for line in run.stdout.splitlines():
                            if line.startswith(prefix + ':'):
                                _, kind, value = line.split(':')
                                parsed[int(kind)] = tuple(int(n) for n in value.split(',') if n)
                        self.assertEqual(parsed, vectors)
                    for line in ('used:57,58,59,60,61,62,63', 'existing:1', 'blank:255', 'same:56',
                                 'unreferenced-slot-reused:56', 'next-after-binding:63',
                                 'pair-different:56,63', 'pair-same:62,62',
                                 'capacity:64:Static Text Table is full', 'existing-full:1',
                                 'mra-zone-bits:11,12',
                                 'allocated:56:0x4D 0xC4 0x81 0x6F 0x72 0x69 0x0'):
                        self.assertIn(line, run.stdout.splitlines())
                    report.update(dll_stdout=run.stdout, crcs=native_crcs, record=second.record.hex(),
                                  static_allocation=allocation.static_allocation.as_dict(),
                                  status_allocation=allocation.status_allocation.as_dict(),
                                  shared_label_status_indexes=[shared.record[13], shared.record[14]],
                                  full_unit_static_reference_vectors_verified=True,
                                  dll_sha256=hashlib.sha256((app / 'CBusLogicModel.dll').read_bytes()).hexdigest())
                    session.save_to_source()
                client.command('PROJECT SAVE ' + project)
                client.command('PROJECT CLOSE ' + project)
                client.command('PROJECT LOAD ' + project)
                client.command('NET LOAD DB ' + project)
                with programmer.load(network, '/db' + unit) as session:
                    self.assertEqual(editor.snapshot(session.values()), final)
                self.assertTrue(any('state=new' in line for line in client.command('GET ' + network + ' state').lines))
                report['passed'] = True
            finally:
                client.command('PROJECT CLOSE ' + project)
                client.command('PROJECT DELETE ' + project)
                if os.environ.get('CBUS_EDLT_REPORT'):
                    Path(os.environ['CBUS_EDLT_REPORT']).write_text(json.dumps(report, indent=2) + '\n')


if __name__ == '__main__':
    unittest.main()
