import json
from pathlib import Path
import socket
import tempfile
import unittest
from unittest.mock import patch

from cbus_toolkit.pci import AcknowledgeCAL, PCIClient, PCIRejected
from cbus_toolkit.simulator import PCISimulator, UnitState


class SimulatorTests(unittest.TestCase):
    def wire(self, address, command, expected_size=None):
        with socket.create_connection(address, timeout=1) as conn:
            conn.settimeout(1)
            conn.sendall(command)
            if expected_size is None:
                return conn.recv(4096)
            reply = bytearray()
            while len(reply) < expected_size:
                data = conn.recv(expected_size - len(reply))
                if not data:
                    break
                reply.extend(data)
            return bytes(reply)

    def test_captured_identity_and_programming_ack_are_literal(self):
        sim = PCISimulator()
        with sim.running() as address:
            with PCIClient(*address) as client:
                self.assertEqual(client.identify(None, 1), b"PC_CNIED")
                self.assertEqual(client.identify(5, 1), b"KEYGL5  ")
                self.assertEqual(client.recall(4, 0x30, 1), b"\x03")
                self.assertEqual(client.write(5, 0, b"\x41\xa0\x00", addressing="programming", ack_tag=0x41),
                                 AcknowledgeCAL(0, 0x41))
                self.assertEqual(client.write(5, 1, b"\x42\x12\x34", addressing="programming", ack_tag=0x42),
                                 AcknowledgeCAL(1, 0x42))
        replies = [bytes.fromhex(record["hex"]) for record in sim.wire_log if record["direction"] == "tx"]
        self.assertIn(b"g.890150435F434E49454421\r\n", replies)
        self.assertIn(b"j.8605100100320041F1\r\n", replies)
        self.assertIn(b"k.8605100100320142EF\r\n", replies)

    def test_written_raw_blocks_survive_reconnect_and_process_state_reload(self):
        with tempfile.TemporaryDirectory() as folder:
            state = Path(folder) / "state.json"
            sim = PCISimulator(state_path=state)
            with sim.running() as address:
                with PCIClient(*address) as client:
                    client.write(5, 0, b"\x41\xac\x00", addressing="programming")
                    client.write(5, 1, b"\x42\x01\x02\x03")
                with PCIClient(*address) as client:
                    self.assertEqual(client.recall(5, 0, 3), b"\x41\xac\x00")
                    self.assertEqual(client.recall(5, 1, 4), b"\x42\x01\x02\x03")
            # Construct a different server instance from its disk image.
            reloaded = PCISimulator(state_path=state)
            with reloaded.running() as address:
                with PCIClient(*address) as client:
                    self.assertEqual(client.recall(5, 0, 3), b"\x41\xac\x00")
                    self.assertEqual(client.recall(5, 1, 2), b"\x42\x01")
                    self.assertEqual(client.identify(5, 1), b"KEYGL5  ")
            self.assertEqual(reloaded.snapshot(), sim.snapshot())

    def test_captured_physical_address_selection_and_literal_segmented_registers(self):
        sim = PCISimulator(profile="captured", fragment_sizes=(1, 3, 2))
        with sim.running() as address:
            with PCIClient(*address) as client:
                self.assertEqual(client.write(5, 0, bytes.fromhex("411000"),
                                              addressing="programming", ack_tag=0x41),
                                 AcknowledgeCAL(0, 0x41))
                self.assertEqual(client.recall(5, 1, 2, addressing="programming"),
                                 bytes.fromhex("38FF"))
                self.assertEqual(client.recall(5, 0xFA, 44, addressing="programming"),
                                 bytes.fromhex("FFFFFFFFFFFFFFFFFFFFFFFF381B381938213818"
                                               "FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF"))
                self.assertEqual(client.recall(5, 0xFB, 9, addressing="programming"), b"01.05.00\x00")
        wire = b"".join(bytes.fromhex(record["hex"]) for record in sim.wire_log
                        if record["direction"] == "tx")
        # Independent, literal proxy.log frames, not responses generated by the client codec.
        for frame in (b"8605100100320041F1\r\n", b"8605100100830138FFA9\r\n",
                      b"860510010091FAFFFFFFFFFFFFFFFFFFFFFFFF381B381941\r\n",
                      b"860510010091FA38213818FFFFFFFFFFFFFFFFFFFFFFFF3C\r\n",
                      b"86051001008DFAFFFFFFFFFFFFFFFFFFFFFFFFE9\r\n",
                      b"86051001008AFB30312E30352E3030005D\r\n"):
            self.assertIn(frame, wire)

    def test_physical_writes_recall_and_disk_reload_keep_selected_memory(self):
        with tempfile.TemporaryDirectory() as folder:
            state = Path(folder) / "state.json"
            sim = PCISimulator(profile="captured", state_path=state,
                               physical_memory={5: {0x10000 + i: i for i in range(40)}})
            with sim.running() as address:
                with PCIClient(*address) as client:
                    client.write(5, 0, bytes.fromhex("41000001"), addressing="programming", ack_tag=0x41)
                    self.assertEqual(client.recall(5, 1, 33, addressing="programming"), bytes(range(33)))
                    client.write(5, 0, bytes.fromhex("4100000100"), addressing="programming", ack_tag=0x41)
                    client.write(5, 1, bytes.fromhex("42AABB"), addressing="programming", ack_tag=0x42)
                    # RECALL after WRITE uses the advanced pointer.
                    self.assertEqual(client.recall(5, 1, 2, addressing="programming"), b"\x02\x03")
            reloaded = PCISimulator(profile="captured", state_path=state)
            with reloaded.running() as address:
                with PCIClient(*address) as client:
                    # The volatile selector is not persisted; select explicitly after restart.
                    with self.assertRaises(PCIRejected):
                        client.recall(5, 1, 1, addressing="programming")
                with PCIClient(*address) as client:
                    client.write(5, 0, bytes.fromhex("41000001"), addressing="programming", ack_tag=0x41)
                    self.assertEqual(client.recall(5, 1, 4, addressing="programming"), bytes.fromhex("AABB0203"))
            self.assertEqual(reloaded.snapshot(), sim.snapshot())

    def test_physical_unknown_bytes_and_forms_reject_without_mutating_memory(self):
        sim = PCISimulator(profile="captured")
        before = sim.snapshot()
        with sim.running() as address:
            actions = [lambda client: client.recall(5, 1, 1, addressing="programming"),
                       lambda client: client.write(5, 0, b"\x41\x10", addressing="programming"),
                       lambda client: client.write(5, 0, b"\x40\x10\x00", addressing="programming"),
                       lambda client: client.recall(5, 0xFA, 45, addressing="programming"),
                       lambda client: client.recall(4, 1, 1, addressing="programming")]
            for action in actions:
                with PCIClient(*address) as client:
                    with self.assertRaises(PCIRejected):
                        action(client)
            for action in (lambda client: client.recall(5, 1, 3, addressing="programming"),
                           lambda client: client.write(5, 1, b"\x42\xAA\xBB\xCC", addressing="programming")):
                with PCIClient(*address) as client:
                    client.write(5, 0, b"\x41\x10\x00", addressing="programming")
                    with self.assertRaises(PCIRejected):
                        action(client)
        self.assertEqual(sim.snapshot(), before)

    def test_physical_persistence_failure_rolls_back_bytes_and_pointer(self):
        sim = PCISimulator(profile="captured")
        with sim.running() as address:
            with PCIClient(*address) as client:
                client.write(5, 0, b"\x41\x10\x00", addressing="programming")
                with patch.object(sim, "_persist", side_effect=OSError("disk full")):
                    with self.assertRaises(PCIRejected):
                        client.write(5, 1, b"\x42\xAA\xBB", addressing="programming")
            with PCIClient(*address) as client:
                self.assertEqual(client.recall(5, 1, 2, addressing="programming"), b"\x38\xFF")

    def test_synthetic_names_change_byte_and_levels_are_explicit_fixture_state(self):
        sim = PCISimulator(profile="synthetic")
        with sim.running() as address:
            with PCIClient(*address) as client:
                self.assertEqual(client.recall(4, 0x23, 6), bytes.fromhex("CA8B33932CDE"))
                self.assertEqual(client.recall(4, 0x2A, 6), bytes.fromhex("CA8B2A93841E"))
                self.assertEqual(client.recall(5, 0x2A, 6), bytes.fromhex("CA8B248EBCDE"))
                self.assertEqual(client.recall(4, 0xF2, 1), b"\xFF")
                self.assertEqual(client.identify(4, 8), bytes(9))
                # Overlapping captured block has the same synthetic name bytes.
                self.assertEqual(client.recall(4, 0x21, 12)[2:8], bytes.fromhex("CA8B33932CDE"))
            expected = (b"g.D838000000000200008A0008000000000000000000000000005C\r\n"
                        b"D838580000000000000000000000000000000000000000000098\r\n"
                        b"D638B0000000000000000000000000000000000000000042\r\n")
            self.assertEqual(self.wire(address, b"\\05FF00FA3800g\r", len(expected)), expected)
        # Generated state never silently changes the original capture fixture.
        self.assertNotIn(8, PCISimulator(profile="captured").units[4].attributes)

    def test_fixture_profile_cannot_be_reinterpreted_as_another_memory_model(self):
        with tempfile.TemporaryDirectory() as folder:
            state = Path(folder) / "state.json"
            PCISimulator(profile="synthetic", state_path=state)
            for profile in ("raw", "captured"):
                with self.assertRaises(ValueError):
                    PCISimulator(profile=profile, state_path=state)

    def test_native_legacy_store_tag_is_not_written_to_memory_and_ack_is_literal(self):
        memory = {0x2A + i: value for i, value in enumerate(bytes.fromhex("CA8B2A9384DE"))}
        sim = PCISimulator(profile="synthetic", legacy_memory={4: memory},
                           legacy_writable={4: set(memory)})
        with sim.running() as address:
            with PCIClient(*address) as client:
                self.assertEqual(client.write(4, 0x2A, bytes.fromhex("00BEFDB1A3391E"), ack_tag=0),
                                 AcknowledgeCAL(0x2A, 0))
                self.assertEqual(client.recall(4, 0x2A, 6), bytes.fromhex("BEFDB1A3391E"))
        tx = [bytes.fromhex(row["hex"]) for row in sim.wire_log if row["direction"] == "tx"]
        # Literal independent native PP SAVE and subsequent RECALL wire vectors.
        self.assertEqual(tx, [b"g.86041000322A000A\r\n", b"h.86041000872ABEFDB1A3391E4F\r\n"])

    def test_legacy_memory_unmapped_and_protected_writes_are_atomic(self):
        memory = {0x1F: 0xFF, 0x20: 4, 0x21: 56, 0x22: 255}
        sim = PCISimulator(profile="synthetic", legacy_memory={4: memory}, legacy_writable={4: {0x21}})
        before = sim.snapshot()
        with sim.running() as address:
            for parameter, data in ((0x1F, b"\x00\x80"), (0x20, b"\x01\xAA"),
                                    (0x21, b"\x02\x39\x00"), (0x24, b"\x03\x00")):
                with PCIClient(*address) as client:
                    with self.assertRaises(PCIRejected):
                        client.write(4, parameter, data)
            with PCIClient(*address) as client:
                with self.assertRaises(PCIRejected):
                    client.recall(4, 0x21, 3)
            # Vendor dd supplies this UNLOCK shape, but its device lifecycle
            # is not established. A fixture allowlist must not imply support.
            self.assertEqual(self.wire(address, b"\\4604001120g\r", 2), b"g#")
        self.assertEqual(sim.snapshot(), before)
        # The fixture cannot pretend a checksum update algorithm was executed.
        self.assertEqual(sim.legacy_memory[4][0x1F], 0xFF)

    def test_legacy_memory_and_status_blocks_persist_with_writable_allowlist(self):
        with tempfile.TemporaryDirectory() as folder:
            state = Path(folder) / "state.json"
            sim = PCISimulator(profile="synthetic", state_path=state, legacy_memory={4: {0x2A: 1}},
                               legacy_writable={4: {0x2A}}, status_blocks={4: {1: bytes(5)}})
            with sim.running() as address:
                with PCIClient(*address) as client:
                    client.write(4, 0x2A, b"\x7E\x99", ack_tag=0x7E)
                expected = b"g.8604100086010000000000DF\r\n"
                self.assertEqual(self.wire(address, b"\\4604002A0105g\r", len(expected)), expected)
            reloaded = PCISimulator(profile="synthetic", state_path=state)
            with reloaded.running() as address:
                with PCIClient(*address) as client:
                    self.assertEqual(client.recall(4, 0x2A, 1), b"\x99")
            self.assertEqual(sim.snapshot(), reloaded.snapshot())

    def test_legacy_fixture_configuration_rejects_unknown_or_out_of_range_memory(self):
        for options in ({"legacy_memory": {4: {256: 0}}},
                        {"legacy_memory": {4: {1: 0}}, "legacy_writable": {4: {2}}},
                        {"profile": "raw", "legacy_memory": {4: {1: 0}}}):
            options.setdefault("profile", "synthetic")
            with self.subTest(options=options), self.assertRaises(ValueError):
                PCISimulator(**options)

    def test_literal_labels_compressed_header_and_persistent_commit(self):
        with tempfile.TemporaryDirectory() as folder:
            state_path = Path(folder) / "state.json"
            sim = PCISimulator(profile="synthetic", state_path=state_path, fragment_sizes=(1,))
            with sim.running() as address:
                # Independent native Lounge and icon258 vectors, then the
                # second packet uses the vendor's retained routing header.
                wire = b"\\053800A90140004C6F756E6765g\rA6016200010102h\r"
                self.assertEqual(self.wire(address, wire, 4), b"g.h.")
                before = sim.snapshot()
                self.assertEqual(self.wire(address, b"\\053800A90140004C6F756Eg\r", 2), b"g#")
                self.assertEqual(sim.snapshot(), before)
            reloaded = PCISimulator(profile="synthetic", state_path=state_path)
            self.assertEqual(reloaded.labels.labels[(56, 1, None, 0, 2)]["text"], "Lounge")
            self.assertEqual(reloaded.labels.labels[(56, 1, None, 0, 3)]["icon"], 258)
            self.assertEqual(reloaded.snapshot(), sim.snapshot())

    def test_label_persistence_failure_rolls_back_and_other_profiles_reject(self):
        wire = b"\\053800A90140004C6F756E6765g\r"
        for profile in ("raw", "captured", "synthetic"):
            sim = PCISimulator(profile=profile)
            before = sim.snapshot()
            with sim.running() as address, patch.object(sim, "_persist", side_effect=OSError("disk failure")):
                self.assertEqual(self.wire(address, wire, 2), b"g#")
            self.assertEqual(sim.snapshot(), before)

    def test_unknown_units_attributes_parameters_and_readonly_writes_reject(self):
        sim = PCISimulator()
        before = sim.snapshot()
        with sim.running() as address:
            actions = [lambda client: client.identify(99, 1),
                       lambda client: client.identify(5, 255),
                       lambda client: client.recall(5, 255, 1),
                       lambda client: client.recall(5, 0, 4),
                       lambda client: client.write(4, 0x30, b"\x00"),
                       lambda client: client.write(5, 255, b"\x00")]
            for action in actions:
                with PCIClient(*address) as client:
                    with self.assertRaises(PCIRejected):
                        action(client)
        self.assertEqual(sim.snapshot(), before)
        rejected = [record for record in sim.wire_log if "reason" in record]
        self.assertEqual(len(rejected), len(actions))
        self.assertTrue(all(bytes.fromhex(record["hex"]) == b"g#" for record in rejected))

    def test_malformed_unknown_and_chained_frames_never_succeed(self):
        sim = PCISimulator()
        before = sim.snapshot()
        malformed = [
            b"\\46050008g\r",             # Unsupported CAL, not a reset success.
            b"\\460500A40041g\r",         # Truncated WRITE.
            b"\\460500A000g\r",           # Invalid count.
            b"\\460500A40041A0002101g\r", # Extra CAL must not apply initial WRITE.
            b"\\46051200A40041A000g\r",   # Unsupported bridge route.
            b"\\0505002101g\r",           # Unsupported packet kind.
            b"\\4605002101FFg\r",         # Extra byte is not ignored.
            b"\\4605001A0000g\r",         # Empty recall count.
            b"\\4605001A001Fg\r",         # Multi-CAL recall unsupported.
            b"\\460500A4xyzg\r",          # Not hexadecimal.
            b"\\460500A40041a00g\r",      # Odd hex length.
        ]
        with sim.running() as address:
            for command in malformed:
                with self.subTest(command=command):
                    self.assertEqual(self.wire(address, command, 2), b"g#")
        self.assertEqual(sim.snapshot(), before)

    def test_checksum_mode_validates_before_mutation(self):
        sim = PCISimulator(command_checksum=True)
        before = sim.snapshot()
        with sim.running() as address:
            with PCIClient(*address, command_checksum=True) as client:
                self.assertEqual(client.recall(4, 0x30, 1), b"\x03")
            for command in (b"\\460500A40041A00000g\r", b"\\460500A40041A000g\r"):
                # CBUS-QS section 4.2 distinguishes corruption from retries.
                self.assertEqual(self.wire(address, command, 2), b"g$")
            with PCIClient(*address) as client:
                with self.assertRaises(PCIRejected):
                    client.write(5, 0, b"\x41\xa0\x00")
        self.assertEqual(sim.snapshot(), before)

    def test_smartconnect_setup_is_per_connection(self):
        sim = PCISimulator(smart=False)
        with sim.running() as address:
            with PCIClient(*address) as client:
                with self.assertRaises(PCIRejected):
                    client.identify(None, 1)
            with PCIClient(*address) as client:
                client.socket.sendall(b"null\r\r||\r")
                self.assertEqual(client.identify(None, 1), b"PC_CNIED")
            with PCIClient(*address) as client:
                with self.assertRaises(PCIRejected):
                    client.identify(None, 1)

    def test_configured_other_unit_chatter_and_fragmentation_are_preserved(self):
        # Same parameter as the awaited RECALL, from a different source.
        chatter = b"8605990082300327\r\n"
        sim = PCISimulator(fragment_sizes=(1, 2, 3), chatter=(chatter,))
        with sim.running() as address:
            with PCIClient(*address) as client:
                self.assertEqual(client.recall(4, 0x30, 1), b"\x03")
                self.assertEqual(len(client.unsolicited), 1)
                self.assertEqual(client.unsolicited[0].source, 5)
        fragments = [bytes.fromhex(record["hex"]) for record in sim.wire_log if record["direction"] == "tx"]
        self.assertEqual([len(part) for part in fragments[:6]], [1, 2, 3, 1, 2, 3])
        self.assertEqual(b"".join(fragments), b"g." + chatter + b"86041000823003B1\r\n")

    def test_json_wire_log_matches_in_memory_records(self):
        with tempfile.TemporaryDirectory() as folder:
            log = Path(folder) / "wire.jsonl"
            sim = PCISimulator(wire_log_path=log, fragment_sizes=(2,))
            with sim.running() as address:
                with PCIClient(*address) as client:
                    self.assertEqual(client.identify(None, 1), b"PC_CNIED")
            records = [json.loads(line) for line in log.read_text().splitlines()]
            self.assertEqual(records, sim.wire_log)
            self.assertEqual(records[0]["hex"], b"@1A2001\r".hex())
            self.assertEqual([record["sequence"] for record in records], list(range(len(records))))

    def test_persistence_failure_rolls_back_and_has_no_success_ack(self):
        sim = PCISimulator()
        before = sim.snapshot()
        with sim.running() as address:
            with patch.object(sim, "_persist", side_effect=OSError("disk unavailable")):
                with PCIClient(*address) as client:
                    with self.assertRaises(PCIRejected):
                        client.write(5, 0, b"\x41\xa0\x00")
            with PCIClient(*address) as client:
                self.assertEqual(client.recall(5, 0, 3), b"\x41\x00\x00")
        self.assertEqual(sim.snapshot(), before)

    def test_user_fixtures_are_explicit_and_original_objects_not_mutated(self):
        attached = UnitState(16, {1: b"PC_CNIED"})
        fixture = UnitState(23, {1: b"TEST"}, {7: b"\x12"}, {7: 0x55})
        sim = PCISimulator([attached, fixture])
        with sim.running() as address:
            with PCIClient(*address) as client:
                self.assertEqual(client.write(23, 7, b"\x99", ack_tag=0x55), AcknowledgeCAL(7, 0x55))
                self.assertEqual(client.recall(23, 7, 1), b"\x99")
        self.assertEqual(fixture.parameters[7], b"\x12")

    def test_incomplete_disconnect_and_oversized_request_do_not_mutate(self):
        sim = PCISimulator()
        before = sim.snapshot()
        with sim.running() as address:
            with socket.create_connection(address, timeout=1) as conn:
                conn.sendall(b"\\460500A40041A000g")
                conn.shutdown(socket.SHUT_WR)
                self.assertEqual(conn.recv(1), b"")
            self.assertEqual(self.wire(address, b"F" * 5000 + b"\r", 1), b"!")
        self.assertEqual(sim.snapshot(), before)
        self.assertTrue(any(record.get("reason") == "Truncated command on disconnect" for record in sim.wire_log))

    def test_vendor_basic_address_query_is_one_shot_and_does_not_enable_smart(self):
        sim = PCISimulator(smart=False, command_checksum=True)
        with sim.running() as address:
            with PCIClient(*address) as client:
                client.socket.sendall(b"@1A2001\r")
                self.assertEqual(client.socket.recv(10), b"8220104E\r\n")
                with self.assertRaises(PCIRejected):
                    client.identify(None, 1)
            self.assertEqual(self.wire(address, b"@A3300055\r", 1), b"!")

    def test_vendor_read_chain_has_literal_combined_reply(self):
        sim = PCISimulator()
        with sim.running() as address:
            expected = b"i.8902352E352E303020208321FFFF6D\r\n"
            self.assertEqual(self.wire(address, b"21021A2102i\r", len(expected)), expected)
            with PCIClient(*address) as client:
                self.assertEqual(client.identify(None, 2), b"5.5.00  ")
                self.assertEqual(client.identify(None, 4), bytes.fromhex("FFFFFF000018A664A3B10005"))
                self.assertEqual(client.recall(None, 0x20, 1), b"\x10")
                self.assertEqual(client.recall(None, 0x2A, 6), bytes.fromhex("B64CF6BB1A9E"))
                self.assertEqual(client.recall(None, 0x23, 6), bytes.fromhex("9B192D8229E4"))

    def test_install_mmi_matches_literal_three_block_fixture(self):
        expected = (b"u.D8FF00000A00000100000000000000000000000000000000001E\r\n"
                    b"D8FF5800000000000000000000000000000000000000000000D1\r\n"
                    b"D6FFB000000000000000000000000000000000000000007B\r\n")
        sim = PCISimulator(fragment_sizes=(1, 5, 2))
        with sim.running() as address:
            self.assertEqual(self.wire(address, b"\\05FF00FAFF00u\r", len(expected)), expected)
            # A different application, offset, or SAL has not been implemented.
            for command in (b"\\05FF00FA3800g\r", b"\\05FF00FAFF20g\r", b"\\05FF007AFF00g\r"):
                self.assertEqual(self.wire(address, command, 2), b"g#")

    def test_mmi_presence_encoding_covers_all_boundaries_without_phantom_units(self):
        expected = {0: 1, 87: 2, 88: 1, 175: 2, 176: 1, 255: 2}
        units = [UnitState(unit, mmi_state=state) for unit, state in expected.items()]
        sim = PCISimulator(units, local_unit=0)
        with sim.running() as address:
            response = self.wire(address, b"\\05FF00FAFF00g\r", 160)
        self.assertTrue(response.startswith(b"g."))
        frames = response[2:].split(b"\r\n")[:-1]
        self.assertEqual(len(frames), 3)
        recovered = {}
        for text, start in zip(frames, (0, 88, 176)):
            frame = bytes.fromhex(text.decode())
            self.assertEqual(sum(frame) % 256, 0)
            self.assertEqual(frame[1:3], bytes((255, start)))
            self.assertEqual(frame[0] & 31, len(frame) - 2)
            for i, byte in enumerate(frame[3:-1]):
                for pair in range(4):
                    state = (byte >> (2 * pair)) & 3
                    if state:
                        recovered[start + 4 * i + pair] = state
        self.assertEqual(recovered, expected)

    def test_header_compression_reuses_previous_unit_and_isolates_connections(self):
        sim = PCISimulator()
        with sim.running() as address:
            with socket.create_connection(address, timeout=1) as conn:
                conn.settimeout(1)
                conn.sendall(b"\\4604002101g\r")
                self.assertIn(b"8604100089014B455945312020201D", conn.recv(200))
                conn.sendall(b"2102h\r")
                # The response is from unit4, whose firmware is2.5, not CNI5.5.
                self.assertEqual(conn.recv(200), b"h.860410008902322E352E3030202078\r\n")
            with PCIClient(*address) as client:
                self.assertEqual(client.identify(None, 2), b"5.5.00  ")

    def test_client_local_calls_after_bus_calls_cannot_hit_cached_bus_destination(self):
        units = [UnitState(16, {1: b"PC_CNIED"}, {0x20: b"\x10", 7: b"\x10"}, {7: 0x44}),
                 UnitState(5, {1: b"TEST"}, {7: b"\x20"}, {7: 0x55})]
        sim = PCISimulator(units)
        with sim.running() as address:
            with PCIClient(*address) as client:
                client.write(5, 7, b"\x99", ack_tag=0x55)
                client.write(None, 7, b"\xaa", ack_tag=0x44)
                self.assertEqual(client.recall(5, 7, 1), b"\x99")
                self.assertEqual(client.recall(None, 7, 1), b"\xaa")
        requests = [bytes.fromhex(row["hex"]) for row in sim.wire_log if row["direction"] == "rx"]
        self.assertEqual(requests[1], b"@1A2001\r")
        self.assertEqual(requests[2], b"\\461000A207AAh\r")
        self.assertEqual(sim.units[5].parameters[7], b"\x99")
        self.assertEqual(sim.units[16].parameters[7], b"\xaa")

    def test_unknown_chained_read_rejects_entire_response(self):
        sim = PCISimulator()
        with sim.running() as address:
            self.assertEqual(self.wire(address, b"210221FEg\r", 2), b"g#")

    def test_invalid_configuration_and_state_are_not_silently_replaced(self):
        for options in ({"units": []}, {"fragment_sizes": (0,)}, {"fragment_sizes": (True,)},
                        {"chatter": ("not bytes",)}, {"local_unit": 256}):
            with self.subTest(options=options), self.assertRaises((TypeError, ValueError)):
                PCISimulator(**options)
        with self.assertRaises(ValueError):
            UnitState(5, parameters={}, write_tags={0: 0x41})
        with tempfile.TemporaryDirectory() as folder:
            state = Path(folder) / "state.json"
            state.write_text('{"schema": 999}')
            original = state.read_bytes()
            with self.assertRaises(ValueError):
                PCISimulator(state_path=state)
            self.assertEqual(state.read_bytes(), original)


if __name__ == "__main__":
    unittest.main()
