"""Source-pinned eDLT FormattedDisplay and SortMode list behavior.

Expected strings and orders below are written by hand from the retained eDLT
source logic, not generated by the implementation under test.
"""
from contextlib import redirect_stderr, redirect_stdout
import hashlib
import io
import itertools
import json
from pathlib import Path
import tempfile
import unittest

from cbus_toolkit import cli
from cbus_toolkit.edlt import EdltError
from cbus_toolkit.edlt_application_cache import (
    ApplicationCache, CachedDisplay, CachedGroupList,
)
from cbus_toolkit.edlt_display_model import (
    EdltDisplayPreferences, REGISTRY_NAMES, address_as_int, display_list,
    evidence, formatted_display, name_ties, native_display_lists, order,
    present_application_cache,
)
from cbus_toolkit.edlt_lifecycle import LifecycleCache, LifecycleGroup


VENDOR = Path('/Volumes/external/mac-mini-offload/source-cbus/'
              'toolkit-cli-research-vendor/edlt-decompiled/CBusLogicModel')
# Private decompiled eDLT sources are identified by hash only.  Each excerpt is
# the inclusive 1-based line range whose logic this module models.
ORIGINAL_SOURCES = {
    'CBusLogicModel/GlobalSoftwareParameters.cs':
        '08a79965131c84e87becd4294218c66737fe9e641ca6bea5728e07c901934b6f',
    'CBusLogicModel.CBusObjects.BaseObjects/CBusBaseObject.cs':
        'b49db12edd5be47e4c1ad362a8ea62c41fe84107d768f6bd0d5bb8c5b523b99d',
    'CBusLogicModel/CBusNetwork.cs':
        'ddd65e5d34d94f3b0468f0db5a8468c0b6b5cdc50b8a49ca27b9f7331000d39c',
    'CBusLogicModel/CBusApplication.cs':
        '669554fea6b53c01a2d0d0c1d7cf8c89cd76d68af0b7d2b11f3bb73a6bfe5933',
    'CBusLogicModel.CBusObjects/CBusGroup.cs':
        '882ef659aa8114ee8d5a9f51c7d7d14cde7322f7da83a33853c9c6f49a3e7aa2',
    'CBusLogicModel/TagDLT.cs':
        'ce6461d96e5017e91f4dc394a27796ff806da3bee12518113b8c2770a1132aa6',
    'CBusLogicModel.Utilities/DataStore.cs':
        'd60cd2371e221a54774e6b8c35ce631975d0c2491e6b9e053d700810831f4f2b',
}
ORIGINAL_EXCERPTS = (
    # UpdateValues: HKCU Preferences key; each flag = value != null && (int)value > 0.
    ('CBusLogicModel/GlobalSoftwareParameters.cs', 108, 124,
     '19bebc304d099901867e6e50c21f33005e5d6ba0b7bae82858466803991b6a57'),
    # CompareTo: string.Compare(ToString(), other, OrdinalIgnoreCase); ToString = TagName.
    ('CBusLogicModel.CBusObjects.BaseObjects/CBusBaseObject.cs', 86, 93,
     'a7a1404271362ae501fbf619f934dacbacc55bf6e3ab61ccc7a5512ac2985257'),
    # FormattedDisplay: PadLeft(3,'0'), " (" + X.PadLeft(2,'0') + "h)", Trim() + " - ".
    ('CBusLogicModel.CBusObjects.BaseObjects/CBusBaseObject.cs', 186, 207,
     'a5fd8a7f6371ce0e6cd791d4dd5d8b9f8abad1946507f4603d4bcf632dc41bd1'),
    # SortModeApplications ? AddressAsInt difference : List.Sort().
    ('CBusLogicModel/CBusNetwork.cs', 498, 505,
     '7fd5cf26ed66cfd152d901cef4a26cd93d7a25983a7accfef169fffc75397a77'),
    # SortModeGroups, then Groups.Add(new CBusGroup(this, "<Unused>", 255)) first.
    ('CBusLogicModel/CBusApplication.cs', 149, 158,
     'f5939b5b1213653e3b7acad5251c5e97b608f3896c5e2249b9316c0609d39213'),
    # SortModeLevels ? AddressAsInt difference : List.Sort().
    ('CBusLogicModel.CBusObjects/CBusGroup.cs', 301, 308,
     '754870f061f6164234463a0fb41d044dc1d67f10613b100a9c8adb5662d18777'),
)

PREFERENCE_FIELDS = ('display_hex', 'display_address_value',
                     'sort_applications_by_address', 'sort_groups_by_address',
                     'sort_levels_by_address')
APPLICATIONS = (CachedDisplay(202, 'trigger Control', 'trigger Control'),
                CachedDisplay(56, 'Lighting', 'Lighting'),
                CachedDisplay(100, 'air', 'air'),
                CachedDisplay(7, 'lighting', 'lighting'))
GROUPS = (CachedDisplay(10, 'Kitchen', 'Kitchen'),
          CachedDisplay(255, '<Unused>', '<Unused>'),
          CachedDisplay(0, '_Spare', '_Spare'),
          CachedDisplay(3, 'Zone', 'Zone'))
LEVELS = (CachedDisplay(200, 'A', 'A'), CachedDisplay(1, 'b', 'b'),
          CachedDisplay(99, 'a', 'a'))

# (display_hex, display_address_value) -> formatted text by address.
DISPLAYS = {
    (False, False): {202: 'trigger Control', 56: 'Lighting', 100: 'air', 7: 'lighting',
                     10: 'Kitchen', 0: '_Spare', 3: 'Zone', 200: 'A', 1: 'b', 99: 'a'},
    (False, True): {202: '202 - trigger Control', 56: '056 - Lighting', 100: '100 - air',
                    7: '007 - lighting', 10: '010 - Kitchen', 0: '000 - _Spare',
                    3: '003 - Zone', 200: '200 - A', 1: '001 - b', 99: '099 - a'},
    (True, False): {202: '(CAh) - trigger Control', 56: '(38h) - Lighting',
                    100: '(64h) - air', 7: '(07h) - lighting', 10: '(0Ah) - Kitchen',
                    0: '(00h) - _Spare', 3: '(03h) - Zone', 200: '(C8h) - A',
                    1: '(01h) - b', 99: '(63h) - a'},
    (True, True): {202: '202 (CAh) - trigger Control', 56: '056 (38h) - Lighting',
                   100: '100 (64h) - air', 7: '007 (07h) - lighting',
                   10: '010 (0Ah) - Kitchen', 0: '000 (00h) - _Spare', 3: '003 (03h) - Zone',
                   200: '200 (C8h) - A', 1: '001 (01h) - b', 99: '099 (63h) - a'},
}
# False: List.Sort() through CompareTo, i.e. TagName under OrdinalIgnoreCase.
# That comparison upper-cases first, so '_' (0x5F) follows 'Z' (0x5A).  Equal
# names ("Lighting"/"lighting", "A"/"a") keep their input order.
# True: AddressAsInt ascending.  Group lists always start with <Unused> 255.
ORDERS = {
    'application': {False: (100, 56, 7, 202), True: (7, 56, 100, 202)},
    'group': {False: (255, 10, 3, 0), True: (255, 0, 3, 10)},
    'level': {False: (200, 99, 1), True: (1, 99, 200)},
}


def preferences(flags):
    return EdltDisplayPreferences(**dict(zip(PREFERENCE_FIELDS, flags)))


class SourcePinTests(unittest.TestCase):
    @unittest.skipUnless(VENDOR.is_dir(), 'Private decompiled eDLT sources are absent')
    def test_modeled_excerpts_match_the_retained_original_sources(self):
        for path, digest in ORIGINAL_SOURCES.items():
            self.assertEqual(hashlib.sha256((VENDOR / path).read_bytes()).hexdigest(),
                             digest, path)
        for path, first, last, digest in ORIGINAL_EXCERPTS:
            lines = (VENDOR / path).read_bytes().split(b'\n')[first - 1:last]
            self.assertEqual(hashlib.sha256(b'\n'.join(lines)).hexdigest(),
                             digest, (path, first, last))

    def test_excerpt_logic_literal_cases(self):
        both = EdltDisplayPreferences(display_hex=True, display_address_value=True)
        # Address.PadLeft(3, '0') pads the stored text, never truncating it.
        self.assertEqual(formatted_display('1234', 'N', both), '1234 (4D2h) - N')
        # AddressAsInt uses int.TryParse and falls back to zero.
        self.assertEqual(formatted_display('x', 'N', both), '00x (00h) - N')
        self.assertEqual(address_as_int(' +7 '), 7)
        self.assertEqual(address_as_int('7.0'), 0)
        self.assertEqual(address_as_int('2147483648'), 0)
        # Negative Int32 ToString("X") is two's complement.
        self.assertEqual(formatted_display('-1', 'N', both), '0-1 (FFFFFFFFh) - N')
        # Trim() applies to the prefix only; the TagName is appended verbatim.
        hex_only = EdltDisplayPreferences(display_hex=True)
        self.assertEqual(formatted_display(5, ' spaced ', hex_only), '(05h) -  spaced ')
        self.assertEqual(formatted_display(5, '', EdltDisplayPreferences()), '')


class RegistryTests(unittest.TestCase):
    def test_absent_key_and_values_use_static_false_defaults(self):
        absent = EdltDisplayPreferences.from_registry(key_present=False)
        self.assertEqual(absent, EdltDisplayPreferences())
        self.assertEqual(EdltDisplayPreferences.from_registry({}), EdltDisplayPreferences())
        with self.assertRaisesRegex(EdltError, 'absent Preferences key'):
            EdltDisplayPreferences.from_registry({'DisplayHexAddress': 1}, key_present=False)

    def test_int_cast_greater_than_zero(self):
        for raw, expected in ((0, False), (1, True), (2, True), (0x7fffffff, True),
                              (0x80000000, False), (0xffffffff, False), (-1, False)):
            with self.subTest(raw=raw):
                values = {name: raw for name in REGISTRY_NAMES}
                self.assertEqual(
                    EdltDisplayPreferences.from_registry(values),
                    EdltDisplayPreferences(*(expected,) * 5))
        for bad in (True, '1', 1.0, 2**32, -(2**31) - 1, None):
            with self.subTest(bad=bad), self.assertRaises(EdltError):
                EdltDisplayPreferences.from_registry({'SortModeGroups': bad})
        with self.assertRaisesRegex(EdltError, 'five eDLT names'):
            EdltDisplayPreferences.from_registry({'DisplayHex': 1})

    def test_each_registry_name_selects_exactly_one_flag(self):
        for index, name in enumerate(REGISTRY_NAMES):
            flags = [False] * 5; flags[index] = True
            self.assertEqual(EdltDisplayPreferences.from_registry({name: 1}),
                             EdltDisplayPreferences(*flags))

    def test_document_roundtrip_and_toolkit_store_adapter(self):
        for flags in itertools.product((False, True), repeat=5):
            value = preferences(flags)
            self.assertEqual(EdltDisplayPreferences.from_dict(
                json.loads(json.dumps(value.as_dict()))), value)
        store = {'tag_hex': True, 'tag_override': 0, 'sort_applications': 1,
                 'sort_groups': False, 'sort_levels': 255}
        self.assertEqual(EdltDisplayPreferences.from_toolkit_display_values(store),
                         EdltDisplayPreferences(True, False, True, False, True))
        with self.assertRaises(EdltError):
            EdltDisplayPreferences.from_dict({'format': 'x', 'registry_key_present': True,
                                              'values': {}})


class DisplayListTests(unittest.TestCase):
    def test_all_32_flag_combinations(self):
        for flags in itertools.product((False, True), repeat=5):
            display_hex, display_value, sort_apps, sort_groups, sort_levels = flags
            prefs = preferences(flags)
            texts = DISPLAYS[(display_hex, display_value)]
            with self.subTest(flags=flags):
                for kind, rows, by_address in (('application', APPLICATIONS, sort_apps),
                                               ('group', GROUPS, sort_groups),
                                               ('level', LEVELS, sort_levels)):
                    result = display_list(kind, rows, prefs)
                    self.assertEqual(tuple(row.address for row in result),
                                     ORDERS[kind][by_address], kind)
                    for row in result:
                        expected = '<Unused>' if row.address == 255 else texts[row.address]
                        self.assertEqual(row.formatted_display, expected)
                        self.assertEqual(row.name, next(
                            item.name for item in rows if item.address == row.address))

    def test_case_insensitive_ties_are_stable_and_reported(self):
        rows = tuple(CachedDisplay(address, name, name) for address, name in (
            (9, 'b'), (4, 'A'), (7, 'a'), (1, '_x'), (2, 'Z'), (3, 'A')))
        by_name = order(rows, by_address=False)
        self.assertEqual([row.address for row in by_name], [4, 7, 3, 9, 2, 1])
        self.assertEqual(name_ties(rows), ((1, 2, 5),))
        self.assertEqual([row.address for row in order(tuple(reversed(rows)),
                                                         by_address=False)],
                         [3, 7, 4, 9, 2, 1])
        self.assertEqual(order(by_name, by_address=False), by_name)
        self.assertEqual([row.address for row in order(rows, by_address=True)],
                         [1, 2, 3, 4, 7, 9])
        # Non-ASCII names use one-character upper mappings; ß has none.
        rows = tuple(CachedDisplay(address, name, name) for address, name in (
            (1, 'é'), (2, 'É'), (3, 'ß'), (4, 'z')))
        self.assertEqual([row.address for row in order(rows, by_address=False)],
                         [4, 1, 2, 3])

    def test_application_cache_presentation_is_idempotent_and_keeps_identity(self):
        lifecycle = LifecycleCache((202, 56, 100, 7), (
            LifecycleGroup(56, 255, True, (False,) * 4, True, ()),))
        cache = ApplicationCache(lifecycle, True, APPLICATIONS, (
            CachedGroupList(56, True, GROUPS),
            CachedGroupList(202, False, ())))
        prefs = EdltDisplayPreferences(True, True, False, True, False)
        presented = present_application_cache(cache, prefs)
        self.assertIs(presented.lifecycle, cache.lifecycle)
        self.assertEqual([row.address for row in presented.applications], [100, 56, 7, 202])
        self.assertEqual([row.formatted_display for row in presented.find_group_list(56).groups],
                         ['<Unused>', '000 (00h) - _Spare', '003 (03h) - Zone',
                          '010 (0Ah) - Kitchen'])
        self.assertFalse(presented.find_group_list(202).complete)
        self.assertEqual(present_application_cache(presented, prefs), presented)
        self.assertEqual(
            [row.formatted_display for row in presented.application_choices(
                primary=56, secondary=100)['secondary']],
            ['<Unused>', '100 (64h) - air'])
        report = evidence(prefs, presented)
        self.assertEqual(report['case_insensitive_name_ties'],
                         [{'kind': 'application', 'application': None, 'addresses': [56, 7]}])
        self.assertEqual(evidence(None)['display_projection'], 'exact TagName database view')


def project_xml():
    def level(address, name):
        return (f'<Level Value="{address}"><OID>l{address}</OID><TagName>{name}</TagName>'
                f'<Address>{address}</Address></Level>')
    return (
        '<Installation><Project><Address>TEST</Address>'
        '<Network><Address>1</Address></Network>'
        '<Network><Address>254</Address>'
        '<Application><TagName>trigger Control</TagName><Address>202</Address>'
        '<Group><TagName>Zone</TagName><Address>3</Address>'
        + level(200, 'b') + level(1, 'A') + level(99, 'a') + '</Group>'
        '<Group><TagName>Stored unused</TagName><Address>255</Address></Group>'
        '<Group><TagName>Kitchen</TagName><Address>10</Address></Group>'
        '</Application>'
        '<Application><TagName>air</TagName><Address>7</Address></Application>'
        '</Network></Project></Installation>')


class NativeListTests(unittest.TestCase):
    def test_database_lists_under_explicit_preferences(self):
        result = native_display_lists(project_xml(), 254, EdltDisplayPreferences(
            display_address_value=True, sort_levels_by_address=True))
        self.assertEqual([row['formatted_display'] for row in result['applications']],
                         ['007 - air', '202 - trigger Control'])
        self.assertEqual(result['groups'][0]['groups'],
                         [{'address': 255, 'name': '<Unused>', 'formatted_display': '<Unused>'},
                          {'address': 10, 'name': 'Kitchen', 'formatted_display': '010 - Kitchen'},
                          {'address': 3, 'name': 'Zone', 'formatted_display': '003 - Zone'}])
        self.assertEqual([row['address'] for row in result['levels'][0]['levels']],
                         [1, 99, 200])
        self.assertTrue(result['toolkit_display_preferences_supplied'])
        self.assertFalse(result['toolkit_registry_read'])
        with self.assertRaisesRegex(ValueError, 'selected network'):
            native_display_lists(project_xml(), 9, EdltDisplayPreferences())

    def test_cli_defaults_to_absent_registry_and_reads_documents(self):
        def invoke(arguments):
            stdout, stderr = io.StringIO(), io.StringIO()
            with redirect_stdout(stdout), redirect_stderr(stderr):
                status = cli.main(list(map(str, arguments)))
            self.assertEqual(status, 0, stderr.getvalue())
            return json.loads(stdout.getvalue())
        with tempfile.TemporaryDirectory() as root:
            project = Path(root) / 'project.xml'
            project.write_text(project_xml())
            before = project.read_bytes()
            result = invoke(['edlt', 'display-lists', '--project-xml', project,
                             '--network', 254])
            self.assertEqual([row['formatted_display'] for row in result['levels'][0]['levels']],
                             ['A', 'a', 'b'])
            self.assertEqual(result['toolkit_display_preferences']['values'],
                             dict.fromkeys(REGISTRY_NAMES, 0))
            document = Path(root) / 'preferences.json'
            document.write_text(json.dumps({
                'format': 'cbus-edlt-display-preferences-v1', 'registry_key_present': True,
                'values': {'DisplayHexAddress': 1, 'SortModeApplications': 1}}))
            result = invoke(['edlt', 'display-lists', '--project-xml', project,
                             '--network', 254, '--display-preferences', document])
            self.assertEqual([row['formatted_display'] for row in result['applications']],
                             ['(07h) - air', '(CAh) - trigger Control'])
            self.assertEqual(project.read_bytes(), before)


if __name__ == '__main__':
    unittest.main()


class PlanThreadingTests(unittest.TestCase):
    """Explicit preferences reach the automatic ordered caches unchanged."""

    def setUp(self):
        import tests.test_edlt_parent_auto_cache as auto
        auto.ParentAutomaticApplicationCacheTests.setUp(self)
        from tests.test_edlt_parent_cache_panels import operations
        self.operations = operations()

    def plan(self, preferences=None):
        from cbus_toolkit.edlt_parent_metadata import plan_native_parent_metadata
        return plan_native_parent_metadata(
            self.client.xml(), '//TEST/254/p/20', self.source, self.editor,
            self.operations, display_preferences=preferences)

    def test_parent_ordered_cache_uses_supplied_preferences_only(self):
        legacy = self.plan()
        names = [row.name for row in legacy.cache.applications]
        addresses = [row.address for row in legacy.cache.applications]
        self.assertEqual([row.formatted_display for row in legacy.cache.applications], names)

        absent = self.plan(EdltDisplayPreferences.from_registry(key_present=False))
        self.assertEqual([row.name for row in absent.cache.applications],
                         sorted(names, key=lambda name: name.upper()))
        self.assertEqual([row.formatted_display for row in absent.cache.applications],
                         [row.name for row in absent.cache.applications])
        evidence_row = absent.as_dict()['automatic_ordered_application_cache']
        self.assertTrue(evidence_row['toolkit_display_preferences_supplied'])
        self.assertFalse(evidence_row['toolkit_registry_display_and_sort_preferences_observed'])
        self.assertNotEqual(absent.semantic_source(), legacy.semantic_source())

        numbered = self.plan(EdltDisplayPreferences(
            display_address_value=True, sort_applications_by_address=True,
            sort_groups_by_address=True))
        self.assertEqual([row.address for row in numbered.cache.applications], sorted(addresses))
        self.assertEqual([row.formatted_display for row in numbered.cache.applications],
                         [f'{row.address:03d} - {row.name}' for row in numbered.cache.applications])
        for row in numbered.cache.group_lists:
            groups = [group.address for group in row.groups]
            self.assertEqual(groups, sorted(groups, key=lambda value: (value != 255, value)))
        self.assertEqual(numbered.parent_plan.changes, legacy.parent_plan.changes)
        with self.assertRaisesRegex(ValueError, 'EdltDisplayPreferences'):
            self.plan({'DisplayHexAddress': 1})

    def test_parent_cli_threads_the_preference_document(self):
        from unittest.mock import patch
        values = {name: list(value) for name, value in self.source.items()}
        with tempfile.TemporaryDirectory() as root:
            files = {name: Path(root) / name for name in (
                'values.json', 'project.xml', 'operations.json', 'preferences.json')}
            files['values.json'].write_text(json.dumps(values))
            files['project.xml'].write_text(self.client.xml())
            files['operations.json'].write_text(json.dumps(list(self.operations)))
            files['preferences.json'].write_text(json.dumps(EdltDisplayPreferences(
                display_hex=True).as_dict()))
            stdout, stderr = io.StringIO(), io.StringIO()
            with patch.object(cli, '_edlt_parent_transaction', return_value=self.editor), \
                    redirect_stdout(stdout), redirect_stderr(stderr):
                status = cli.main(list(map(str, [
                    'edlt', 'parent-transaction-plan', files['values.json'],
                    '--project-xml', files['project.xml'], '--unit', '//TEST/254/p/20',
                    '--operations', files['operations.json'],
                    '--display-preferences', files['preferences.json']])))
            self.assertEqual(status, 0, stderr.getvalue())
            result = json.loads(stdout.getvalue())
        applications = result['metadata_cache']['applications']
        self.assertTrue(all(row['formatted_display'].startswith('(')
                            and row['formatted_display'].endswith(') - ' + row['name'])
                            for row in applications))
        self.assertEqual(result['automatic_ordered_application_cache'][
            'toolkit_display_preferences']['values']['DisplayHexAddress'], 1)


class SceneThreadingTests(unittest.TestCase):
    def setUp(self):
        import tests.test_edlt_scene_metadata as scene
        scene.SceneMetadataTests.setUp(self)
        self.rows = scene.operations('sync')

    def test_scene_resolver_presents_its_application_cache(self):
        from cbus_toolkit.edlt_scene_metadata import resolve_native_scene_metadata
        legacy = resolve_native_scene_metadata(
            self.client.xml(), '//TEST/254/p/20', self.values, self.editor.engine, self.rows)
        prefs = EdltDisplayPreferences(display_address_value=True, display_hex=True)
        resolved = resolve_native_scene_metadata(
            self.client.xml(), '//TEST/254/p/20', self.values, self.editor.engine, self.rows,
            display_preferences=prefs)
        cache = resolved.cache.application_cache
        self.assertEqual(cache, present_application_cache(legacy.cache.application_cache, prefs))
        self.assertEqual(resolved.cache.level_labels, legacy.cache.level_labels)
        self.assertTrue(all(row.formatted_display == formatted_display(row.address, row.name, prefs)
                            for row in cache.applications))
        report = resolved.as_dict()['ordered_lists']
        self.assertTrue(report['toolkit_display_preferences_supplied'])
        self.assertFalse(legacy.as_dict()['ordered_lists']['toolkit_display_preferences_supplied'])
