"""Original RCPData vectors and bounded native Room Courtesy PP editing."""
from dataclasses import replace
import hashlib
import json
import os
from pathlib import Path
import subprocess
import tempfile
import unittest
from uuid import uuid4

from cbus_toolkit.edlt import EdltError, EdltApplyError, EdltLighting
from cbus_toolkit.edlt_room_courtesy import EdltRoomCourtesyWidget, ROOM_COURTESY_COLOURS
from cbus_toolkit.unitspec import UnitSpecStore
from test_edlt import fixture, Session

# Literal outputs of the unchanged original Toolkit RCPData on explicit PP
# scaffolds. They are not generated by the Python Room Courtesy helper.
DEFAULT = '0F0084840000FF19000000000000000000000000000000000000000000000000'
BOUND_DEFAULT = '0F00848400002A19000000000000000000000000000000000000000000000000'
UNUSED_COLOURS = '0F80848400002AFF000002030000000000000000000000000000000000000000'
CUSTOM_STATIC = '0FB5848400002AFF3F3E02030000000000000000000000000000000000000000'
BELL_RETAINS_LABELS = '0FB5848400002A193F3E02030000000000000000000000000000000000000000'
COLOUR_0 = '0FB5848400002A193F3E00080000000000000000000000000000000000000000'
COLOUR_1 = '0FB5848400002A193F3E01070000000000000000000000000000000000000000'
COLOUR_2 = '0FB5848400002A193F3E02060000000000000000000000000000000000000000'
COLOUR_3 = '0FB5848400002A193F3E03050000000000000000000000000000000000000000'
COLOUR_4 = '0FB5848400002A193F3E04040000000000000000000000000000000000000000'
COLOUR_5 = '0FB5848400002A193F3E05030000000000000000000000000000000000000000'
COLOUR_6 = '0FB5848400002A193F3E06020000000000000000000000000000000000000000'
COLOUR_7 = '0FB5848400002A193F3E07010000000000000000000000000000000000000000'
COLOUR_8 = '0FB5848400002A193F3E08000000000000000000000000000000000000000000'
DYNAMIC_ICONS = '0FA7848400002A19010302030000000000000000000000000000000000000000'
DYNAMIC_TEXT = '0F96848400002A19020002030000000000000000000000000000000000000000'
SAME_INDEX_REFRESH = '0FA7848400002A19020002030000000000000000000000000000000000000000'
GROUP_REFRESH = '0FA7848400002B19020002030000000000000000000000000000000000000000'
APPLICATION_127 = '0FA7848400002B19020002030000000000000000000000000000000000000000'
APPLICATION_136 = '0FA7848400002B19020002030000000000000000000000000000000000000000'
BLANK_TYPES = '0F80848400002B19000002030000000000000000000000000000000000000000'
SINGLE_ICON_BOTH_BYTES = '0F80898900002B19000002030000000000000000000000000000000000000000'
NO_FORCING = '0F80898900002B19000002030000000000000000000000000000000000000000'
OPAQUE_DEFAULT = '0F0084840405FF19000000000C0D0E0F101112131415161718191A1B1C1D1E1F'
OPAQUE_BLANK_DEFAULT = '0F0084840405FF19080900000C0D0E0F101112131415161718191A1B1C1D1E1F'


def after(plan):
    return {**plan.expected, **plan.changes}


class RoomCourtesyTests(unittest.TestCase):
    def setUp(self):
        self.spec = fixture(); self.editor = EdltRoomCourtesyWidget(self.spec); self.session = Session(self.spec)

    def plan(self, current=None, **options):
        settings = dict(page=1, position=1, group=42); settings.update(options)
        return self.editor.plan(self.session.values() if current is None else current, **settings)

    def test_default_both_modes_and_all_original_colours(self):
        plan = self.plan()
        self.assertEqual(plan.record.hex().upper(), BOUND_DEFAULT)
        self.assertEqual((plan.mode, plan.off_colour, plan.on_colour), ('bell-press', 'none', 'none'))
        self.assertFalse(any(key.startswith('StaticTextString') for key in plan.changes))
        self.assertFalse(self.plan(after(plan)).changes)
        plan = self.plan(after(plan), application='secondary', mode='unused', off_colour='red', on_colour='green')
        self.assertEqual(plan.record.hex().upper(), UNUSED_COLOURS)
        plan = self.plan(after(plan), application='secondary', label_text='Courtesy', status_text='Available')
        self.assertEqual(plan.record.hex().upper(), CUSTOM_STATIC)
        plan = self.plan(after(plan), application='secondary', mode='bell-press')
        self.assertEqual(plan.record.hex().upper(), BELL_RETAINS_LABELS)
        names = tuple(ROOM_COURTESY_COLOURS)
        for off, literal in enumerate((COLOUR_0, COLOUR_1, COLOUR_2, COLOUR_3, COLOUR_4, COLOUR_5, COLOUR_6, COLOUR_7, COLOUR_8)):
            result = self.plan(after(plan), application='secondary', off_colour=names[off], on_colour=names[8-off])
            self.assertEqual(result.record.hex().upper(), literal)

    def test_original_dynamic_index_refresh_and_status_types(self):
        plan = self.plan(application='secondary', off_colour='red', on_colour='green', label_text='Courtesy', status_text='Available')
        for settings, literal in ((dict(label_type='dynamic-icon', label_index=1, status_type='dynamic-icon', status_index=3), DYNAMIC_ICONS),
                                  (dict(label_type='dynamic-text', label_index=2, status_type='dynamic-text', status_index=0), DYNAMIC_TEXT),
                                  (dict(label_type='dynamic-icon', label_index=2, status_type='dynamic-icon', status_index=0), SAME_INDEX_REFRESH),
                                  (dict(group=43, label_type='dynamic-icon', status_type='dynamic-icon'), GROUP_REFRESH),
                                  (dict(group=43, label_type='blank', status_type='blank'), BLANK_TYPES)):
            plan = self.plan(after(plan), application='secondary', **settings)
            self.assertEqual(plan.record.hex().upper(), literal)

    def test_dynamic_same_index_group_and_application_require_explicit_metadata(self):
        current = after(self.plan(label_type='dynamic-text', label_index=2, status_type='dynamic-icon', status_index=0))
        for options in ({'group': 43}, {'application': 'secondary'}, {'label_index': 2}, {'status_index': 0},
                        {'label_index': 3}, {'status_index': 1}, {'label_index': 2, 'status_index': 0}):
            with self.subTest(options=options), self.assertRaisesRegex(EdltError, 'explicit'): self.plan(current, **options)
        self.assertFalse(self.plan(current).changes)
        self.assertEqual(self.plan(current, label_type='dynamic-icon', label_index=2).record[1], 0x27)

    def test_shared_text_reuse_dedup_direct_indexes_and_full_reference_capacity(self):
        plan = self.plan(label_text='Same', status_text='Same')
        self.assertEqual((plan.static_allocation.index, plan.status_allocation.index), (63, 63))
        self.assertTrue(plan.status_allocation.reused)
        current = after(plan); current['StaticTextString50'] = tuple(b'Same'.ljust(64, b'\0'))
        plan = self.plan(current, label_type='static', label_index=50, status_index=63)
        self.assertEqual(plan.record[8:10], bytes((50, 63)))
        self.assertFalse(any(key.startswith('StaticTextString') for key in plan.changes))
        current = after(self.plan()); index = 0
        for widget in range(7, 22):
            current[f'Widget{widget}WidgetType'] = (16,); current[f'Widget{widget}WidgetByteValue1'] = (0x35,)
            for offset in range(9, 14):
                current[f'Widget{widget}WidgetByteValue{offset}'] = (min(index, 63),); index += 1
        with self.assertRaises(EdltError): self.plan(current, label_text='New text')
        self.plan(current, mode='unused')  # No default text allocation or forcing.

    def test_opaque_retention_and_explicit_repair_of_invalid_active_fields(self):
        for control, literal in ((255, OPAQUE_DEFAULT), (0, OPAQUE_BLANK_DEFAULT)):
            current = self.session.values()
            for offset in range(1, 32): current[f'Widget6WidgetByteValue{offset}'] = (offset,)
            current['Widget6WidgetByteValue1'] = (control,)
            expected = bytearray.fromhex(literal); expected[6] = 42
            self.assertEqual(self.plan(current).record, bytes(expected))
        current = after(self.plan())
        for slot, repair in ((7, {'mode': 'unused'}), (10, {'off_colour': 'orange'}), (11, {'on_colour': 'cyan'})):
            invalid = dict(current); invalid[f'Widget6WidgetByteValue{slot}'] = (99,)
            with self.assertRaises(EdltError): self.plan(invalid)
            self.plan(invalid, **repair)
        current['Widget6WidgetByteValue2'] = (137,); current['Widget6WidgetByteValue3'] = (138,)
        self.assertEqual(self.plan(current).record[2:4], bytes((137, 138)))

    def test_restore_lookup_pages_and_other_widgets_preserved(self):
        current = after(self.plan())
        light = EdltLighting(self.spec).plan(current, page=1, position=2, group=43, mode='off-on', restore_level=137)
        current = after(light)
        plan = self.plan(current, group=43, application='secondary')
        self.assertEqual((plan.restore_level, plan.restore_source_widget), (137, 7))
        for key in current:
            if key.startswith('Widget7') or key.startswith('Scene'): self.assertNotIn(key, plan.changes)
        same = after(plan); same['Widget6RestoreLevel'] = (88,)
        self.assertEqual(self.plan(same, group=43).restore_level, 88)
        self.assertEqual(self.plan(same, group=44).restore_level, 0)
        last = self.plan(page_mode='multiple', page=4, position=4)
        self.assertEqual(last.widget, 21)
        for index in range(6, 21): self.assertEqual(after(last)[f'Widget{index}WidgetType'], (0,))
        self.assertEqual(self.plan(position=5).widget, 10)

    def test_original_application_scope_and_strict_options_profile_references(self):
        for app in (48, 95, 96, 127, 136):
            current = self.session.values(); current['SecondaryApplication'] = (app,)
            self.assertEqual(self.plan(current, application='secondary').application, app)
        for app in (0, 47, 128, 135, 137, 203, 255):
            current = self.session.values(); current['SecondaryApplication'] = (app,)
            with self.assertRaises(EdltError): self.plan(current, application='secondary')
        for options in ({'mode': []}, {'mode': 'off-on'}, {'off_colour': 2}, {'on_colour': True}, {'off_colour': 'RED'},
                        {'group': 255}, {'group': True}, {'application': []}, {'page': 2}, {'position': 6},
                        {'label_type': []}, {'status_type': 'level'}, {'status_type': 'timer'}, {'status_type': 'bar'},
                        {'status_type': 'percent'}, {'status_type': 'blank', 'status_index': 1},
                        {'label_type': 'dynamic-icon', 'label_index': 4}, {'status_type': 'static', 'status_index': 64},
                        {'label_text': 'a\0b'}, {'status_text': 'ā'*32}, {'label_text': ' '}, {'label_text': 'Hi', 'label_index': 1}):
            with self.subTest(options=options), self.assertRaises(EdltError): self.plan(**options)
        for index, kind in ((1, 15), (6, 14), (7, 15)):
            current = self.session.values(); current[f'Widget{index}WidgetType'] = (kind,)
            with self.assertRaises(EdltError): self.plan(current)
        for settings in ({'catalog_number': '5055EDLB'}, {'firmware': '6.0.00'}):
            with self.assertRaises(EdltError): EdltRoomCourtesyWidget(self.spec, **settings)
        self.assertFalse(self.session.calls)

    def test_stale_forged_identity_and_unsaved_apply(self):
        plan = self.plan(label_text='Courtesy', status_text='Available')
        for forged in (None, replace(plan, widget=True), replace(plan, record=b'bad'), replace(plan, application=128),
                       replace(plan, restore_level=False), replace(plan, off_colour='red'),
                       replace(plan, static_allocation=None), replace(plan, changes={**plan.changes, 'SceneCount': (8,)})):
            with self.assertRaises(EdltError): self.editor.apply(self.session, forged)
        self.session.current['SceneCount'] = (8,)
        with self.assertRaisesRegex(EdltError, 'changed'): self.editor.apply(self.session, plan)
        self.session.current['SceneCount'] = (0,)
        result = self.editor.apply(self.session, plan)
        self.assertTrue(result['verified']); self.assertFalse(result['saved']); self.assertFalse(result['physical_device_verified'])
        self.session.identity['UnitType'] = 'KEY4'; self.session.values = lambda: self.fail('Identity must precede PP read')
        with self.assertRaisesRegex(EdltError, 'identity'): self.editor.configure(self.session)

    def test_failure_rollback_and_no_recovery_after_disconnect(self):
        plan = self.plan(label_text='Courtesy', status_text='Available'); original = self.editor.snapshot(self.session.values())
        self.session.failure = 'Widget6WidgetByteValue7'
        with self.assertRaises(EdltApplyError) as caught: self.editor.apply(self.session, plan)
        self.assertTrue(caught.exception.details['rollback_verified']); self.assertFalse(caught.exception.details['saved'])
        self.assertEqual(self.editor.snapshot(self.session.values()), original)
        self.session.calls.clear(); initial = self.session.set
        def fail(name, value):
            initial(name, value); self.session.connected = False; raise TimeoutError('Injected disconnect')
        self.session.set = fail
        with self.assertRaises(EdltApplyError) as caught: self.editor.apply(self.session, plan)
        self.assertEqual(len(self.session.calls), 1); self.assertIn('Connection lost', caught.exception.rollback_errors[0])


@unittest.skipUnless(all(os.environ.get(key) for key in ('CBUS_CGATE_TEST_HOST', 'CBUS_UNITSPEC_DIR', 'CBUS_TOOLKIT_EXE')),
                     'Set C-Gate host, specifications and Toolkit EXE for native Room Courtesy acceptance')
class NativeRoomCourtesyTests(unittest.TestCase):
    def test_original_dll_native_raw_crc_and_save_reload(self):
        from cbus_toolkit.cgate import CGateClient
        from cbus_toolkit.programming import Programmer
        root = Path(__file__).resolve().parents[1]; app = Path(os.environ['CBUS_TOOLKIT_EXE']).resolve().parent
        specs = Path(os.environ['CBUS_UNITSPEC_DIR']).resolve(); spec = UnitSpecStore(specs).load('KEYGL5.xml')
        editor = EdltRoomCourtesyWidget(spec); project = 'ERC' + uuid4().hex[:5].upper()
        network, unit = f'//{project}/254', f'//{project}/254/p/20'
        report = {'project': project, 'scope': '5055EDL5.5 Room Courtesy database PP; no physical device', 'passed': False}
        from research.original_oracle import OriginalModelOracle, selected_backend
        backend = selected_backend(); report['original_backend'] = backend
        with tempfile.TemporaryDirectory() as folder:
            for name in ('NativeEdltRCPProbe.cs', 'NativeEdltProbe.cs'):
                Path(folder, name).write_bytes((root / 'research' / name).read_bytes())
            def mono(command):
                result = subprocess.run(['docker', 'run', '--rm', '-v', str(app) + ':/input:ro', '-v', folder + ':/work', '-w', '/work',
                    'mono@sha256:34d816779b1248b5cfd095770b64ecbaf1798e2aca693a91c11a018dce9c7ad5', 'sh', '-c', command],
                    capture_output=True, text=True, timeout=60)
                self.assertEqual(result.returncode, 0, result.stdout + result.stderr); return result.stdout
            oracle = OriginalModelOracle(root / 'research/NativeEdltRCPProbe.cs', app, backend='windows') if backend == 'windows' else None
            crc_oracle = OriginalModelOracle(root / 'research/NativeEdltProbe.cs', app, backend='windows') if backend == 'windows' else None
            if oracle is not None:
                self.addCleanup(oracle.close); self.addCleanup(crc_oracle.close)
                native = oracle.run()
            else:
                native = mono('mcs -r:/input/CBusLogicModel.dll -r:System.Windows.Forms -r:System.Drawing NativeEdltRCPProbe.cs && MONO_PATH=/input mono NativeEdltRCPProbe.exe')
            for literal in (DEFAULT, BOUND_DEFAULT, UNUSED_COLOURS, CUSTOM_STATIC, BELL_RETAINS_LABELS, COLOUR_0, COLOUR_1,
                            COLOUR_2, COLOUR_3, COLOUR_4, COLOUR_5, COLOUR_6, COLOUR_7, COLOUR_8, DYNAMIC_ICONS,
                            DYNAMIC_TEXT, SAME_INDEX_REFRESH, OPAQUE_DEFAULT, OPAQUE_BLANK_DEFAULT):
                self.assertIn(':' + literal + ':0', native)
            for literal in (GROUP_REFRESH, APPLICATION_127, APPLICATION_136, BLANK_TYPES, SINGLE_ICON_BOTH_BYTES, NO_FORCING):
                self.assertIn(':' + literal + ':137', native)
            self.assertIn('selected-application:127', native); self.assertIn('selected-application:136', native)
            self.assertIn('modes:<Unused>=255|Bell Press=25', native)
            with CGateClient(os.environ['CBUS_CGATE_TEST_HOST'], int(os.environ.get('CBUS_CGATE_TEST_PORT', '20023')), timeout=30) as client:
                client.command('PROJECT NEW ' + project)
                try:
                    for command in ('PROJECT USE ' + project, f'DBSET //{project}/Project/Description cbus-toolkit-isolated-edlt-rcp-v1',
                                    'DBCREATENET 254 Offline Cni 127.0.0.1:1', 'PROJECT SAVE ' + project, f'DBADDSAFE {network} Unit 20 EDLT'):
                        client.command(command)
                    for key, value in (('UnitType', 'KEYGL5'), ('UnitName', 'EDLT'), ('FirmwareVersion', '5.5.00'), ('CatalogNumber', '5055EDL')):
                        client.command(f'DBSET {unit}/{key} {value}')
                    client.command('NET LOAD DB ' + project); programmer = Programmer(client)
                    with programmer.load(network, '/db' + unit) as session:
                        session.reset_defaults(); session.set('SecondaryApplication', '57'); original = editor.snapshot(session.values())
                        first = editor.plan(original, page=1, position=1, group=42)
                        self.assertEqual(first.record.hex().upper(), BOUND_DEFAULT); editor.apply(session, first)
                        sequence = ((dict(mode='unused', off_colour='red', on_colour='green'), UNUSED_COLOURS),
                                    (dict(label_text='Courtesy', status_text='Available'), CUSTOM_STATIC),
                                    (dict(mode='bell-press'), BELL_RETAINS_LABELS),
                                    (dict(label_type='dynamic-icon', label_index=1, status_type='dynamic-icon', status_index=3), DYNAMIC_ICONS),
                                    (dict(label_type='dynamic-text', label_index=2, status_type='dynamic-text', status_index=0), DYNAMIC_TEXT))
                        for options, literal in sequence:
                            plan = editor.plan(session.values(), page=1, position=1, group=42, application='secondary', **options)
                            self.assertEqual(plan.record.hex().upper(), literal); editor.apply(session, plan)
                            self.assertEqual(session.get_raw_data(0x2c0, 32).lines[-1].split('RawData=')[1], literal.lower())
                        before = editor.snapshot(session.values())
                        for options in ({'label_index': 2}, {'status_index': 0}):
                            with self.assertRaisesRegex(EdltError, 'explicit'):
                                editor.configure(session, page=1, position=1, group=42, application='secondary', **options)
                            self.assertEqual(editor.snapshot(session.values()), before)
                        plan = editor.plan(session.values(), page=1, position=1, group=42, application='secondary',
                                           label_type='dynamic-icon', label_index=2, status_type='dynamic-icon', status_index=0)
                        self.assertEqual(plan.record.hex().upper(), SAME_INDEX_REFRESH); editor.apply(session, plan)
                        light = EdltLighting(spec); light.apply(session, light.plan(session.values(), page=1, position=2, group=43, mode='off-on', restore_level=137))
                        prior = editor.snapshot(session.values())
                        plan = editor.plan(prior, page=1, position=1, group=43, application='secondary',
                                           label_type='dynamic-icon', status_type='dynamic-icon')
                        self.assertEqual(plan.record.hex().upper(), GROUP_REFRESH); self.assertEqual(plan.restore_level, 137)
                        editor.apply(session, plan)
                        self.assertEqual(session.get_raw_data(0x1a0, 1).lines[-1].split('RawData=')[1], '89')
                        last = editor.plan(session.values(), page=4, position=4, page_mode='multiple', group=43,
                                           label_text='Māori', status_text='Māori', on_colour='orange')
                        self.assertEqual(last.static_allocation.index, last.status_allocation.index); editor.apply(session, last)
                        self.assertEqual(session.get_raw_data(0x4a0, 32).lines[-1].split('RawData=')[1], last.record.hex())
                        self.assertEqual(session.get_raw_data(0x1100+64*last.static_allocation.index, 64).lines[-1].split('RawData=')[1],
                                         'Māori'.encode().ljust(64, b'\0').hex())
                        session.save_to_source()
                    app_results = []
                    for application in (127, 136):
                        with programmer.load(network, '/db' + unit) as session:
                            session.set('SecondaryApplication', str(application))
                            plan = editor.plan(session.values(), page=1, position=1, group=43, application='secondary',
                                               label_type='dynamic-icon', status_type='dynamic-icon')
                            self.assertEqual(plan.record.hex().upper(), GROUP_REFRESH); self.assertEqual(plan.application, application)
                            editor.apply(session, plan); final = editor.snapshot(session.values())
                            self.assertEqual(session.get_raw_data(0x2c0, 32).lines[-1].split('RawData=')[1], GROUP_REFRESH.lower())
                            for key in final:
                                if key.startswith('Scene') and key != 'ScenesCheckSum': self.assertEqual(final[key], original[key])
                                if key.startswith('Widget7'): self.assertEqual(final[key], prior[key])
                            Path(folder, 'KEYGL5.xml').write_bytes((specs / 'KEYGL5.xml').read_bytes())
                            Path(folder, 'values.tsv').write_text(''.join(key + '\t' + (value if isinstance(value, str) else ' '.join(hex(n) for n in value)) + '\n' for key, value in final.items()))
                            if crc_oracle is not None:
                                output = crc_oracle.run(('KEYGL5.xml', 'values.tsv'), files={name: Path(folder,name).read_bytes() for name in ('KEYGL5.xml','values.tsv')})
                            else:
                                output = mono('mcs -r:/input/CBusLogicModel.dll -r:System.Windows.Forms -r:System.Xml.Linq NativeEdltProbe.cs && MONO_PATH=/input mono NativeEdltProbe.exe KEYGL5.xml values.tsv')
                            crcs = {parts[1]: tuple(int(n, 16) for n in parts[2].split()) for line in output.splitlines()
                                    if (parts := line.split(':'))[0] == 'pp-crc'}
                            self.assertEqual(crcs, editor.crcs(final)); session.save_to_source()
                        for command in ('PROJECT SAVE ', 'PROJECT CLOSE ', 'PROJECT LOAD ', 'NET LOAD DB '): client.command(command + project)
                        with programmer.load(network, '/db' + unit) as session:
                            self.assertEqual(editor.snapshot(session.values()), final)
                            with self.assertRaises(EdltError): editor.configure(session, page=1, position=1, group=43, off_colour=2)
                            self.assertEqual(editor.snapshot(session.values()), final)
                        app_results.append({'application': application, 'crcs': crcs, 'all_pp_reloaded': True})
                    self.assertTrue(any('state=new' in line for line in client.command('GET ' + network + ' state').lines))
                    report.update(passed=True, dll_stdout=native, applications=app_results, first=first.as_dict(), last=last.as_dict(),
                                  dll_sha256=hashlib.sha256((app / 'CBusLogicModel.dll').read_bytes()).hexdigest())
                finally:
                    client.command('PROJECT CLOSE ' + project); client.command('PROJECT DELETE ' + project)
                    if os.environ.get('CBUS_EDLT_ROOM_COURTESY_REPORT'):
                        Path(os.environ['CBUS_EDLT_ROOM_COURTESY_REPORT']).write_text(json.dumps(report, indent=2) + '\n')


if __name__ == '__main__': unittest.main()
