"""Independent full109PP/project literals for direct source plant assignments.

These cases do not claim full quick-zone/Framework scheduling, native Group
factory defaults or hardware acceptance. Expected records were transcribed
from pinned source effects before this production component existed.
"""
from copy import deepcopy
from dataclasses import replace
import json

import pytest

from cbus_toolkit.thermostat_plant_types import PlantTypeModel, PlantGroupCapacityError
from cbus_toolkit.thermostat_remote_references import (
    ProjectGraphSnapshot, RemoteApplication, RemoteGroup, RemoteLevel, _GraphResolver)
from cbus_toolkit.thermostat_templates import ThermostatTemplateError

ROLES = ("CoolActivation", "CoolStage1", "CoolStage2", "CoolStage3", "CoolFanLow",
    "CoolFanMedium", "CoolFanHigh", "HeatActivation", "HeatStage1", "HeatStage2",
    "HeatStage3", "HeatFanLow", "HeatFanMedium", "HeatFanHigh", "DamperZone1",
    "DamperZone2", "DamperZone3", "DamperZone4", "InternalRelay1", "InternalRelay2",
    "InternalRelay3", "InternalRelay4", "InternalRelay5")

PP_NAMES = ('Application', 'ApplicationNumber', 'BacklightActiveTime', 'BacklightDimTime', 'BeepEnable', 'ControlledZones', 'CoolActivationOutput', 'CoolFanHighOutput', 'CoolFanLowOutput', 'CoolFanMediumOutput', 'CoolStage1Output', 'CoolStage2Output', 'CoolStage3Output', 'CoolingPlantFanDefaultSpeed', 'CoolingPlantFanEnable', 'CoolingPlantFanOffDelay', 'CoolingPlantFanOnDelay', 'CoolingPlantFanSpeedControlEnable', 'CoolingPlantFanSpeeds', 'CoolingPlantInstalledZones', 'CoolingPlantStages', 'CoolingPlantType', 'DamperModulationEnable', 'DamperZone1Output', 'DamperZone2Output', 'DamperZone3Output', 'DamperZone4Output', 'DisplayBacklightActiveBrightness', 'DisplayBacklightIdleBrightness', 'EnableHVACRelayDrive', 'EvapComfortStartTemp', 'EvapComfortStepSize', 'EvapCoolerDryTime', 'EvapCoolerDumpTime', 'EvapCoolerFillTime', 'EvapCoolerIdleTime', 'EvapCoolerPrewetTime', 'EvapProgramEnabled', 'EvapStartProportionalTemperature', 'EvapStopProportionalTemperature', 'FanOperationMode', 'GuardLowerTemperature', 'GuardMaximumLowerTemperature', 'GuardMaximumUpperTemperature', 'GuardMinimumLowerTemperature', 'GuardMinimumUpperTemperature', 'GuardUpperTemperature', 'HeatActivationOutput', 'HeatCoolDifferentialFactor', 'HeatCoolIntegralFactor', 'HeatCoolPlantType', 'HeatFanHighOutput', 'HeatFanLowOutput', 'HeatFanMediumOutput', 'HeatStage1Output', 'HeatStage2Output', 'HeatStage3Output', 'HeatingPlantFanDefaultSpeed', 'HeatingPlantFanEnable', 'HeatingPlantFanOffDelay', 'HeatingPlantFanOnDelay', 'HeatingPlantFanSpeedControlEnable', 'HeatingPlantFanSpeeds', 'HeatingPlantInstalledZones', 'HeatingPlantStages', 'HeatingPlantType', 'InstallationCode', 'InstalledZones', 'InternalPlantModes', 'InternalPlantType', 'InternalPlantZones', 'InternalRelay1GroupNumber', 'InternalRelay2GroupNumber', 'InternalRelay3GroupNumber', 'InternalRelay4GroupNumber', 'InternalRelay5GroupNumber', 'KeyBacklightActiveBrightness', 'KeyBacklightIdleBrightness', 'MaximumSetTemperature', 'MeasuredZones', 'MinimumSetTemperature', 'NonEvapProgramEnabled', 'PlantCycleTime', 'PlantMinimumOffTime', 'PlantMinimumOnTime', 'RemoteScheduleEnable', 'RemoteScheduleOffGroup', 'RemoteScheduleOnGroup', 'RemoteScheduleOverrideGroup', 'RemoteSetbackControlSource', 'RemoteSetbackOffGroup', 'RemoteSetbackOnGroup', 'ScheduleControlledZones', 'SendInterval', 'SetbackLevel', 'TemperatureOffset', 'TemperatureSendDifferential', 'TemperatureUnits', 'TimeUnits', 'TimerEnable', 'UIAllocatedZones', 'UnrelatedParameter', 'VariableFanCoilEnable', 'VariableFanCoilTiming', 'VentPlantType', 'VentingPlantInstalledZones', 'VentingPlantType', 'ZoneGroup', 'ZoneTemperatureDisplay')

PLANT_CASES = (('plant0-unused-only-nil',
  0,
  None,
  [(255, 'Unused')],
  {},
  [(255, 'Unused')],
  [('CoolActivationOutputGroup', 255),
   ('CoolStage1OutputGroup', 255),
   ('CoolStage2OutputGroup', 255),
   ('CoolStage3OutputGroup', 255),
   ('CoolFanLowOutputGroup', 255),
   ('CoolFanMediumOutputGroup', 255),
   ('CoolFanHighOutputGroup', 255),
   ('HeatActivationOutputGroup', 255),
   ('HeatStage1OutputGroup', 255),
   ('HeatStage2OutputGroup', 255),
   ('HeatStage3OutputGroup', 255),
   ('HeatFanLowOutputGroup', 255),
   ('HeatFanMediumOutputGroup', 255),
   ('HeatFanHighOutputGroup', 255),
   ('InternalRelay1Group', 255),
   ('InternalRelay2Group', 255),
   ('InternalRelay3Group', 255),
   ('InternalRelay4Group', 255),
   ('InternalRelay5Group', 255),
   ('DamperZone1OutputGroup', 255),
   ('DamperZone2OutputGroup', 255),
   ('DamperZone3OutputGroup', 255),
   ('DamperZone4OutputGroup', 255),
   ('CoolingPlantFanEnable', 0),
   ('HeatingPlantFanEnable', 0)],
  []),
 ('plant0-retained-prefix-collision-nil',
  0,
  None,
  [(255, 'Unused'),
   (0, 'Opaque zero'),
   (1, 'User Y'),
   (3, 'User G'),
   (5, 'User W'),
   (20, '[CG07] Previous twenty'),
   (40, '[CG07] Previous forty')],
  {},
  [(255, 'Unused'),
   (0, 'Opaque zero'),
   (1, 'User Y'),
   (3, 'User G'),
   (5, 'User W'),
   (20, '[CG07] Previous twenty'),
   (40, '[CG07] Previous forty')],
  [('CoolActivationOutputGroup', 255),
   ('CoolStage1OutputGroup', 255),
   ('CoolStage2OutputGroup', 255),
   ('CoolStage3OutputGroup', 255),
   ('CoolFanLowOutputGroup', 255),
   ('CoolFanMediumOutputGroup', 255),
   ('CoolFanHighOutputGroup', 255),
   ('HeatActivationOutputGroup', 255),
   ('HeatStage1OutputGroup', 255),
   ('HeatStage2OutputGroup', 255),
   ('HeatStage3OutputGroup', 255),
   ('HeatFanLowOutputGroup', 255),
   ('HeatFanMediumOutputGroup', 255),
   ('HeatFanHighOutputGroup', 255),
   ('InternalRelay1Group', 255),
   ('InternalRelay2Group', 255),
   ('InternalRelay3Group', 255),
   ('InternalRelay4Group', 255),
   ('InternalRelay5Group', 255),
   ('DamperZone1OutputGroup', 255),
   ('DamperZone2OutputGroup', 255),
   ('DamperZone3OutputGroup', 255),
   ('DamperZone4OutputGroup', 255),
   ('CoolingPlantFanEnable', 0),
   ('HeatingPlantFanEnable', 0)],
  []),
 ('plant1-unused-only-nil',
  1,
  None,
  [(255, 'Unused')],
  {'CoolingPlantFanDefaultSpeed': 1,
   'CoolingPlantFanSpeeds': 1,
   'HeatFanLowOutput': 3,
   'HeatStage1Output': 5,
   'HeatingPlantFanDefaultSpeed': 1,
   'HeatingPlantFanEnable': 1,
   'HeatingPlantFanSpeedControlEnable': 1,
   'HeatingPlantFanSpeeds': 1,
   'InternalRelay3GroupNumber': 3,
   'InternalRelay5GroupNumber': 5},
  [(255, 'Unused'), (5, '[CG07] W (heat)'), (3, '[CG07] G (heat fan)')],
  [('CoolActivationOutputGroup', 255),
   ('CoolStage1OutputGroup', 255),
   ('CoolStage2OutputGroup', 255),
   ('CoolStage3OutputGroup', 255),
   ('CoolFanLowOutputGroup', 255),
   ('CoolFanMediumOutputGroup', 255),
   ('CoolFanHighOutputGroup', 255),
   ('HeatActivationOutputGroup', 255),
   ('HeatStage1OutputGroup', 5),
   ('HeatStage2OutputGroup', 255),
   ('HeatStage3OutputGroup', 255),
   ('HeatFanLowOutputGroup', 3),
   ('HeatFanMediumOutputGroup', 255),
   ('HeatFanHighOutputGroup', 255),
   ('InternalRelay1Group', 255),
   ('InternalRelay2Group', 255),
   ('InternalRelay3Group', 3),
   ('InternalRelay4Group', 255),
   ('InternalRelay5Group', 5),
   ('CoolingPlantFanSpeedControlEnable', 0),
   ('CoolingPlantFanSpeeds', 1),
   ('CoolingPlantFanDefaultSpeed', 1),
   ('CoolingPlantFanEnable', 0),
   ('HeatingPlantFanSpeedControlEnable', 1),
   ('HeatingPlantFanSpeeds', 1),
   ('HeatingPlantFanDefaultSpeed', 1),
   ('HeatingPlantFanEnable', 1)],
  [('create', 5, None, '[CG07] W (heat)'), ('create', 3, None, '[CG07] G (heat fan)')]),
 ('plant1-retained-prefix-collision-nil',
  1,
  None,
  [(255, 'Unused'),
   (0, 'Opaque zero'),
   (1, 'User Y'),
   (3, 'User G'),
   (5, 'User W'),
   (20, '[CG07] Previous twenty'),
   (40, '[CG07] Previous forty')],
  {'CoolingPlantFanDefaultSpeed': 1,
   'CoolingPlantFanSpeeds': 1,
   'HeatFanLowOutput': 42,
   'HeatStage1Output': 41,
   'HeatingPlantFanDefaultSpeed': 1,
   'HeatingPlantFanEnable': 1,
   'HeatingPlantFanSpeedControlEnable': 1,
   'HeatingPlantFanSpeeds': 1,
   'InternalRelay3GroupNumber': 42,
   'InternalRelay5GroupNumber': 41},
  [(255, 'Unused'),
   (0, 'Opaque zero'),
   (1, 'User Y'),
   (3, 'User G'),
   (5, 'User W'),
   (20, '[CG07] Previous twenty'),
   (40, '[CG07] Previous forty'),
   (41, '[CG07] W (heat)'),
   (42, '[CG07] G (heat fan)')],
  [('CoolActivationOutputGroup', 255),
   ('CoolStage1OutputGroup', 255),
   ('CoolStage2OutputGroup', 255),
   ('CoolStage3OutputGroup', 255),
   ('CoolFanLowOutputGroup', 255),
   ('CoolFanMediumOutputGroup', 255),
   ('CoolFanHighOutputGroup', 255),
   ('HeatActivationOutputGroup', 255),
   ('HeatStage1OutputGroup', 41),
   ('HeatStage2OutputGroup', 255),
   ('HeatStage3OutputGroup', 255),
   ('HeatFanLowOutputGroup', 42),
   ('HeatFanMediumOutputGroup', 255),
   ('HeatFanHighOutputGroup', 255),
   ('InternalRelay1Group', 255),
   ('InternalRelay2Group', 255),
   ('InternalRelay3Group', 42),
   ('InternalRelay4Group', 255),
   ('InternalRelay5Group', 41),
   ('CoolingPlantFanSpeedControlEnable', 0),
   ('CoolingPlantFanSpeeds', 1),
   ('CoolingPlantFanDefaultSpeed', 1),
   ('CoolingPlantFanEnable', 0),
   ('HeatingPlantFanSpeedControlEnable', 1),
   ('HeatingPlantFanSpeeds', 1),
   ('HeatingPlantFanDefaultSpeed', 1),
   ('HeatingPlantFanEnable', 1)],
  [('create', 41, None, '[CG07] W (heat)'),
   ('ChangeTagName', 41, '[CG07] W (heat)', '[CG07] W (heat)'),
   ('create', 42, None, '[CG07] G (heat fan)'),
   ('ChangeTagName', 42, '[CG07] G (heat fan)', '[CG07] G (heat fan)')]),
 ('plant2-unused-only-nil',
  2,
  None,
  [(255, 'Unused')],
  {'CoolFanLowOutput': 3,
   'CoolFanMediumOutput': 4,
   'CoolStage1Output': 1,
   'CoolStage3Output': 2,
   'CoolingPlantFanDefaultSpeed': 1,
   'CoolingPlantFanEnable': 1,
   'CoolingPlantFanSpeedControlEnable': 1,
   'CoolingPlantFanSpeeds': 2,
   'HeatingPlantFanDefaultSpeed': 1,
   'HeatingPlantFanSpeeds': 2,
   'InternalRelay1GroupNumber': 1,
   'InternalRelay2GroupNumber': 2,
   'InternalRelay3GroupNumber': 3,
   'InternalRelay4GroupNumber': 4},
  [(255, 'Unused'),
   (1, '[CG07] pump'),
   (2, '[CG07] fill'),
   (3, '[CG07] cool fan speed 1'),
   (4, '[CG07] cool fan speed 2')],
  [('CoolActivationOutputGroup', 255),
   ('CoolStage1OutputGroup', 1),
   ('CoolStage2OutputGroup', 255),
   ('CoolStage3OutputGroup', 2),
   ('CoolFanLowOutputGroup', 3),
   ('CoolFanMediumOutputGroup', 4),
   ('CoolFanHighOutputGroup', 255),
   ('HeatActivationOutputGroup', 255),
   ('HeatStage1OutputGroup', 255),
   ('HeatStage2OutputGroup', 255),
   ('HeatStage3OutputGroup', 255),
   ('HeatFanLowOutputGroup', 255),
   ('HeatFanMediumOutputGroup', 255),
   ('HeatFanHighOutputGroup', 255),
   ('InternalRelay1Group', 1),
   ('InternalRelay2Group', 2),
   ('InternalRelay3Group', 3),
   ('InternalRelay4Group', 4),
   ('InternalRelay5Group', 255),
   ('CoolingPlantFanSpeedControlEnable', 1),
   ('CoolingPlantFanSpeeds', 2),
   ('CoolingPlantFanDefaultSpeed', 1),
   ('CoolingPlantFanEnable', 1),
   ('HeatingPlantFanSpeedControlEnable', 0),
   ('HeatingPlantFanSpeeds', 2),
   ('HeatingPlantFanDefaultSpeed', 1),
   ('HeatingPlantFanEnable', 0)],
  [('create', 1, None, '[CG07] pump'),
   ('create', 2, None, '[CG07] fill'),
   ('create', 3, None, '[CG07] cool fan speed 1'),
   ('create', 4, None, '[CG07] cool fan speed 2')]),
 ('plant2-retained-prefix-collision-nil',
  2,
  None,
  [(255, 'Unused'),
   (0, 'Opaque zero'),
   (1, 'User Y'),
   (3, 'User G'),
   (5, 'User W'),
   (20, '[CG07] Previous twenty'),
   (40, '[CG07] Previous forty')],
  {'CoolFanLowOutput': 42,
   'CoolFanMediumOutput': 4,
   'CoolStage1Output': 41,
   'CoolStage3Output': 2,
   'CoolingPlantFanDefaultSpeed': 1,
   'CoolingPlantFanEnable': 1,
   'CoolingPlantFanSpeedControlEnable': 1,
   'CoolingPlantFanSpeeds': 2,
   'HeatingPlantFanDefaultSpeed': 1,
   'HeatingPlantFanSpeeds': 2,
   'InternalRelay1GroupNumber': 41,
   'InternalRelay2GroupNumber': 2,
   'InternalRelay3GroupNumber': 42,
   'InternalRelay4GroupNumber': 4},
  [(255, 'Unused'),
   (0, 'Opaque zero'),
   (1, 'User Y'),
   (3, 'User G'),
   (5, 'User W'),
   (20, '[CG07] Previous twenty'),
   (40, '[CG07] Previous forty'),
   (41, '[CG07] pump'),
   (2, '[CG07] fill'),
   (42, '[CG07] cool fan speed 1'),
   (4, '[CG07] cool fan speed 2')],
  [('CoolActivationOutputGroup', 255),
   ('CoolStage1OutputGroup', 41),
   ('CoolStage2OutputGroup', 255),
   ('CoolStage3OutputGroup', 2),
   ('CoolFanLowOutputGroup', 42),
   ('CoolFanMediumOutputGroup', 4),
   ('CoolFanHighOutputGroup', 255),
   ('HeatActivationOutputGroup', 255),
   ('HeatStage1OutputGroup', 255),
   ('HeatStage2OutputGroup', 255),
   ('HeatStage3OutputGroup', 255),
   ('HeatFanLowOutputGroup', 255),
   ('HeatFanMediumOutputGroup', 255),
   ('HeatFanHighOutputGroup', 255),
   ('InternalRelay1Group', 41),
   ('InternalRelay2Group', 2),
   ('InternalRelay3Group', 42),
   ('InternalRelay4Group', 4),
   ('InternalRelay5Group', 255),
   ('CoolingPlantFanSpeedControlEnable', 1),
   ('CoolingPlantFanSpeeds', 2),
   ('CoolingPlantFanDefaultSpeed', 1),
   ('CoolingPlantFanEnable', 1),
   ('HeatingPlantFanSpeedControlEnable', 0),
   ('HeatingPlantFanSpeeds', 2),
   ('HeatingPlantFanDefaultSpeed', 1),
   ('HeatingPlantFanEnable', 0)],
  [('create', 41, None, '[CG07] pump'),
   ('ChangeTagName', 41, '[CG07] pump', '[CG07] pump'),
   ('create', 2, None, '[CG07] fill'),
   ('create', 42, None, '[CG07] cool fan speed 1'),
   ('ChangeTagName', 42, '[CG07] cool fan speed 1', '[CG07] cool fan speed 1'),
   ('create', 4, None, '[CG07] cool fan speed 2')]),
 ('plant3-unused-only-nil',
  3,
  None,
  [(255, 'Unused')],
  {'CoolActivationOutput': 2,
   'CoolFanLowOutput': 3,
   'CoolStage1Output': 1,
   'CoolingPlantFanDefaultSpeed': 1,
   'CoolingPlantFanEnable': 1,
   'CoolingPlantFanSpeeds': 1,
   'HeatActivationOutput': 4,
   'HeatFanLowOutput': 3,
   'HeatStage1Output': 1,
   'HeatingPlantFanDefaultSpeed': 1,
   'HeatingPlantFanEnable': 1,
   'HeatingPlantFanSpeeds': 1,
   'InternalRelay1GroupNumber': 1,
   'InternalRelay2GroupNumber': 2,
   'InternalRelay3GroupNumber': 3,
   'InternalRelay4GroupNumber': 4},
  [(255, 'Unused'),
   (2, '[CG07] B (cool activation)'),
   (1, '[CG07] Y (heat/cool)'),
   (3, '[CG07] G (fan)'),
   (4, '[CG07] B (heat activation)')],
  [('CoolActivationOutputGroup', 2),
   ('CoolStage1OutputGroup', 1),
   ('CoolStage2OutputGroup', 255),
   ('CoolStage3OutputGroup', 255),
   ('CoolFanLowOutputGroup', 3),
   ('CoolFanMediumOutputGroup', 255),
   ('CoolFanHighOutputGroup', 255),
   ('HeatActivationOutputGroup', 4),
   ('HeatStage1OutputGroup', 1),
   ('HeatStage2OutputGroup', 255),
   ('HeatStage3OutputGroup', 255),
   ('HeatFanLowOutputGroup', 3),
   ('HeatFanMediumOutputGroup', 255),
   ('HeatFanHighOutputGroup', 255),
   ('InternalRelay1Group', 1),
   ('InternalRelay2Group', 2),
   ('InternalRelay3Group', 3),
   ('InternalRelay4Group', 4),
   ('InternalRelay5Group', 255),
   ('CoolingPlantFanSpeedControlEnable', 0),
   ('CoolingPlantFanSpeeds', 1),
   ('CoolingPlantFanDefaultSpeed', 1),
   ('CoolingPlantFanEnable', 1),
   ('HeatingPlantFanSpeedControlEnable', 0),
   ('HeatingPlantFanSpeeds', 1),
   ('HeatingPlantFanDefaultSpeed', 1),
   ('HeatingPlantFanEnable', 1)],
  [('create', 2, None, '[CG07] B (cool activation)'),
   ('create', 1, None, '[CG07] Y (heat/cool)'),
   ('create', 3, None, '[CG07] G (fan)'),
   ('create', 4, None, '[CG07] B (heat activation)')]),
 ('plant3-retained-prefix-collision-nil',
  3,
  None,
  [(255, 'Unused'),
   (0, 'Opaque zero'),
   (1, 'User Y'),
   (3, 'User G'),
   (5, 'User W'),
   (20, '[CG07] Previous twenty'),
   (40, '[CG07] Previous forty')],
  {'CoolActivationOutput': 2,
   'CoolFanLowOutput': 42,
   'CoolStage1Output': 41,
   'CoolingPlantFanDefaultSpeed': 1,
   'CoolingPlantFanEnable': 1,
   'CoolingPlantFanSpeeds': 1,
   'HeatActivationOutput': 4,
   'HeatFanLowOutput': 42,
   'HeatStage1Output': 41,
   'HeatingPlantFanDefaultSpeed': 1,
   'HeatingPlantFanEnable': 1,
   'HeatingPlantFanSpeeds': 1,
   'InternalRelay1GroupNumber': 41,
   'InternalRelay2GroupNumber': 2,
   'InternalRelay3GroupNumber': 42,
   'InternalRelay4GroupNumber': 4},
  [(255, 'Unused'),
   (0, 'Opaque zero'),
   (1, 'User Y'),
   (3, 'User G'),
   (5, 'User W'),
   (20, '[CG07] Previous twenty'),
   (40, '[CG07] Previous forty'),
   (2, '[CG07] B (cool activation)'),
   (41, '[CG07] Y (heat/cool)'),
   (42, '[CG07] G (fan)'),
   (4, '[CG07] B (heat activation)')],
  [('CoolActivationOutputGroup', 2),
   ('CoolStage1OutputGroup', 41),
   ('CoolStage2OutputGroup', 255),
   ('CoolStage3OutputGroup', 255),
   ('CoolFanLowOutputGroup', 42),
   ('CoolFanMediumOutputGroup', 255),
   ('CoolFanHighOutputGroup', 255),
   ('HeatActivationOutputGroup', 4),
   ('HeatStage1OutputGroup', 41),
   ('HeatStage2OutputGroup', 255),
   ('HeatStage3OutputGroup', 255),
   ('HeatFanLowOutputGroup', 42),
   ('HeatFanMediumOutputGroup', 255),
   ('HeatFanHighOutputGroup', 255),
   ('InternalRelay1Group', 41),
   ('InternalRelay2Group', 2),
   ('InternalRelay3Group', 42),
   ('InternalRelay4Group', 4),
   ('InternalRelay5Group', 255),
   ('CoolingPlantFanSpeedControlEnable', 0),
   ('CoolingPlantFanSpeeds', 1),
   ('CoolingPlantFanDefaultSpeed', 1),
   ('CoolingPlantFanEnable', 1),
   ('HeatingPlantFanSpeedControlEnable', 0),
   ('HeatingPlantFanSpeeds', 1),
   ('HeatingPlantFanDefaultSpeed', 1),
   ('HeatingPlantFanEnable', 1)],
  [('create', 2, None, '[CG07] B (cool activation)'),
   ('create', 41, None, '[CG07] Y (heat/cool)'),
   ('ChangeTagName', 41, '[CG07] Y (heat/cool)', '[CG07] Y (heat/cool)'),
   ('create', 42, None, '[CG07] G (fan)'),
   ('ChangeTagName', 42, '[CG07] G (fan)', '[CG07] G (fan)'),
   ('create', 4, None, '[CG07] B (heat activation)')]),
 ('plant3-unused-only-Zoned 2 Stage Reverse Cycle System',
  3,
  'Zoned 2 Stage Reverse Cycle System',
  [(255, 'Unused')],
  {'CoolFanLowOutput': 3,
   'CoolFanMediumOutput': 5,
   'CoolStage1Output': 1,
   'CoolStage2Output': 2,
   'CoolingPlantFanDefaultSpeed': 1,
   'CoolingPlantFanEnable': 1,
   'CoolingPlantFanSpeedControlEnable': 1,
   'CoolingPlantFanSpeeds': 2,
   'HeatActivationOutput': 4,
   'HeatFanLowOutput': 3,
   'HeatFanMediumOutput': 5,
   'HeatStage1Output': 1,
   'HeatStage2Output': 2,
   'HeatingPlantFanDefaultSpeed': 1,
   'HeatingPlantFanEnable': 1,
   'HeatingPlantFanSpeedControlEnable': 1,
   'HeatingPlantFanSpeeds': 2,
   'InternalRelay1GroupNumber': 1,
   'InternalRelay2GroupNumber': 2,
   'InternalRelay3GroupNumber': 3,
   'InternalRelay4GroupNumber': 4,
   'InternalRelay5GroupNumber': 5},
  [(255, 'Unused'),
   (1, '[CG07] Y1 (cool/heat)'),
   (2, '[CG07] Y2 (cool/heat)'),
   (3, '[CG07] G (fan)'),
   (5, '[CG07] Heat/cool fan speed'),
   (4, '[CG07] B (heat activation)')],
  [('CoolActivationOutputGroup', 255),
   ('CoolStage1OutputGroup', 1),
   ('CoolStage2OutputGroup', 2),
   ('CoolStage3OutputGroup', 255),
   ('CoolFanLowOutputGroup', 3),
   ('CoolFanMediumOutputGroup', 5),
   ('CoolFanHighOutputGroup', 255),
   ('HeatActivationOutputGroup', 4),
   ('HeatStage1OutputGroup', 1),
   ('HeatStage2OutputGroup', 2),
   ('HeatStage3OutputGroup', 255),
   ('HeatFanLowOutputGroup', 3),
   ('HeatFanMediumOutputGroup', 5),
   ('HeatFanHighOutputGroup', 255),
   ('InternalRelay1Group', 1),
   ('InternalRelay2Group', 2),
   ('InternalRelay3Group', 3),
   ('InternalRelay4Group', 4),
   ('InternalRelay5Group', 5),
   ('CoolingPlantFanSpeedControlEnable', 1),
   ('CoolingPlantFanSpeeds', 2),
   ('CoolingPlantFanDefaultSpeed', 1),
   ('CoolingPlantFanEnable', 1),
   ('HeatingPlantFanSpeedControlEnable', 1),
   ('HeatingPlantFanSpeeds', 2),
   ('HeatingPlantFanDefaultSpeed', 1),
   ('HeatingPlantFanEnable', 1)],
  [('create', 1, None, '[CG07] Y1 (cool/heat)'),
   ('create', 2, None, '[CG07] Y2 (cool/heat)'),
   ('create', 3, None, '[CG07] G (fan)'),
   ('create', 5, None, '[CG07] Heat/cool fan speed'),
   ('create', 4, None, '[CG07] B (heat activation)')]),
 ('plant3-retained-prefix-collision-Zoned 2 Stage Reverse Cycle System',
  3,
  'Zoned 2 Stage Reverse Cycle System',
  [(255, 'Unused'),
   (0, 'Opaque zero'),
   (1, 'User Y'),
   (3, 'User G'),
   (5, 'User W'),
   (20, '[CG07] Previous twenty'),
   (40, '[CG07] Previous forty')],
  {'CoolFanLowOutput': 42,
   'CoolFanMediumOutput': 43,
   'CoolStage1Output': 41,
   'CoolStage2Output': 2,
   'CoolingPlantFanDefaultSpeed': 1,
   'CoolingPlantFanEnable': 1,
   'CoolingPlantFanSpeedControlEnable': 1,
   'CoolingPlantFanSpeeds': 2,
   'HeatActivationOutput': 4,
   'HeatFanLowOutput': 42,
   'HeatFanMediumOutput': 43,
   'HeatStage1Output': 41,
   'HeatStage2Output': 2,
   'HeatingPlantFanDefaultSpeed': 1,
   'HeatingPlantFanEnable': 1,
   'HeatingPlantFanSpeedControlEnable': 1,
   'HeatingPlantFanSpeeds': 2,
   'InternalRelay1GroupNumber': 41,
   'InternalRelay2GroupNumber': 2,
   'InternalRelay3GroupNumber': 42,
   'InternalRelay4GroupNumber': 4,
   'InternalRelay5GroupNumber': 43},
  [(255, 'Unused'),
   (0, 'Opaque zero'),
   (1, 'User Y'),
   (3, 'User G'),
   (5, 'User W'),
   (20, '[CG07] Previous twenty'),
   (40, '[CG07] Previous forty'),
   (41, '[CG07] Y1 (cool/heat)'),
   (2, '[CG07] Y2 (cool/heat)'),
   (42, '[CG07] G (fan)'),
   (43, '[CG07] Heat/cool fan speed'),
   (4, '[CG07] B (heat activation)')],
  [('CoolActivationOutputGroup', 255),
   ('CoolStage1OutputGroup', 41),
   ('CoolStage2OutputGroup', 2),
   ('CoolStage3OutputGroup', 255),
   ('CoolFanLowOutputGroup', 42),
   ('CoolFanMediumOutputGroup', 43),
   ('CoolFanHighOutputGroup', 255),
   ('HeatActivationOutputGroup', 4),
   ('HeatStage1OutputGroup', 41),
   ('HeatStage2OutputGroup', 2),
   ('HeatStage3OutputGroup', 255),
   ('HeatFanLowOutputGroup', 42),
   ('HeatFanMediumOutputGroup', 43),
   ('HeatFanHighOutputGroup', 255),
   ('InternalRelay1Group', 41),
   ('InternalRelay2Group', 2),
   ('InternalRelay3Group', 42),
   ('InternalRelay4Group', 4),
   ('InternalRelay5Group', 43),
   ('CoolingPlantFanSpeedControlEnable', 1),
   ('CoolingPlantFanSpeeds', 2),
   ('CoolingPlantFanDefaultSpeed', 1),
   ('CoolingPlantFanEnable', 1),
   ('HeatingPlantFanSpeedControlEnable', 1),
   ('HeatingPlantFanSpeeds', 2),
   ('HeatingPlantFanDefaultSpeed', 1),
   ('HeatingPlantFanEnable', 1)],
  [('create', 41, None, '[CG07] Y1 (cool/heat)'),
   ('ChangeTagName', 41, '[CG07] Y1 (cool/heat)', '[CG07] Y1 (cool/heat)'),
   ('create', 2, None, '[CG07] Y2 (cool/heat)'),
   ('create', 42, None, '[CG07] G (fan)'),
   ('ChangeTagName', 42, '[CG07] G (fan)', '[CG07] G (fan)'),
   ('create', 43, None, '[CG07] Heat/cool fan speed'),
   ('ChangeTagName', 43, '[CG07] Heat/cool fan speed', '[CG07] Heat/cool fan speed'),
   ('create', 4, None, '[CG07] B (heat activation)')]),
 ('plant3-unused-only-Conventional 2 Stage Heat/Cool USA System',
  3,
  'Conventional 2 Stage Heat/Cool USA System',
  [(255, 'Unused')],
  {'CoolActivationOutput': 2,
   'CoolFanLowOutput': 3,
   'CoolStage1Output': 1,
   'CoolingPlantFanDefaultSpeed': 1,
   'CoolingPlantFanEnable': 1,
   'CoolingPlantFanSpeeds': 1,
   'HeatActivationOutput': 4,
   'HeatFanLowOutput': 3,
   'HeatStage1Output': 1,
   'HeatingPlantFanDefaultSpeed': 1,
   'HeatingPlantFanEnable': 1,
   'HeatingPlantFanSpeeds': 1,
   'InternalRelay1GroupNumber': 1,
   'InternalRelay2GroupNumber': 2,
   'InternalRelay3GroupNumber': 3,
   'InternalRelay4GroupNumber': 4},
  [(255, 'Unused'),
   (2, '[CG07] B (cool activation)'),
   (1, '[CG07] Y (heat/cool)'),
   (3, '[CG07] G (fan)'),
   (4, '[CG07] B (heat activation)')],
  [('CoolActivationOutputGroup', 2),
   ('CoolStage1OutputGroup', 1),
   ('CoolStage2OutputGroup', 255),
   ('CoolStage3OutputGroup', 255),
   ('CoolFanLowOutputGroup', 3),
   ('CoolFanMediumOutputGroup', 255),
   ('CoolFanHighOutputGroup', 255),
   ('HeatActivationOutputGroup', 4),
   ('HeatStage1OutputGroup', 1),
   ('HeatStage2OutputGroup', 255),
   ('HeatStage3OutputGroup', 255),
   ('HeatFanLowOutputGroup', 3),
   ('HeatFanMediumOutputGroup', 255),
   ('HeatFanHighOutputGroup', 255),
   ('InternalRelay1Group', 1),
   ('InternalRelay2Group', 2),
   ('InternalRelay3Group', 3),
   ('InternalRelay4Group', 4),
   ('InternalRelay5Group', 255),
   ('CoolingPlantFanSpeedControlEnable', 0),
   ('CoolingPlantFanSpeeds', 1),
   ('CoolingPlantFanDefaultSpeed', 1),
   ('CoolingPlantFanEnable', 1),
   ('HeatingPlantFanSpeedControlEnable', 0),
   ('HeatingPlantFanSpeeds', 1),
   ('HeatingPlantFanDefaultSpeed', 1),
   ('HeatingPlantFanEnable', 1)],
  [('create', 2, None, '[CG07] B (cool activation)'),
   ('create', 1, None, '[CG07] Y (heat/cool)'),
   ('create', 3, None, '[CG07] G (fan)'),
   ('create', 4, None, '[CG07] B (heat activation)')]),
 ('plant3-retained-prefix-collision-Conventional 2 Stage Heat/Cool USA System',
  3,
  'Conventional 2 Stage Heat/Cool USA System',
  [(255, 'Unused'),
   (0, 'Opaque zero'),
   (1, 'User Y'),
   (3, 'User G'),
   (5, 'User W'),
   (20, '[CG07] Previous twenty'),
   (40, '[CG07] Previous forty')],
  {'CoolActivationOutput': 2,
   'CoolFanLowOutput': 42,
   'CoolStage1Output': 41,
   'CoolingPlantFanDefaultSpeed': 1,
   'CoolingPlantFanEnable': 1,
   'CoolingPlantFanSpeeds': 1,
   'HeatActivationOutput': 4,
   'HeatFanLowOutput': 42,
   'HeatStage1Output': 41,
   'HeatingPlantFanDefaultSpeed': 1,
   'HeatingPlantFanEnable': 1,
   'HeatingPlantFanSpeeds': 1,
   'InternalRelay1GroupNumber': 41,
   'InternalRelay2GroupNumber': 2,
   'InternalRelay3GroupNumber': 42,
   'InternalRelay4GroupNumber': 4},
  [(255, 'Unused'),
   (0, 'Opaque zero'),
   (1, 'User Y'),
   (3, 'User G'),
   (5, 'User W'),
   (20, '[CG07] Previous twenty'),
   (40, '[CG07] Previous forty'),
   (2, '[CG07] B (cool activation)'),
   (41, '[CG07] Y (heat/cool)'),
   (42, '[CG07] G (fan)'),
   (4, '[CG07] B (heat activation)')],
  [('CoolActivationOutputGroup', 2),
   ('CoolStage1OutputGroup', 41),
   ('CoolStage2OutputGroup', 255),
   ('CoolStage3OutputGroup', 255),
   ('CoolFanLowOutputGroup', 42),
   ('CoolFanMediumOutputGroup', 255),
   ('CoolFanHighOutputGroup', 255),
   ('HeatActivationOutputGroup', 4),
   ('HeatStage1OutputGroup', 41),
   ('HeatStage2OutputGroup', 255),
   ('HeatStage3OutputGroup', 255),
   ('HeatFanLowOutputGroup', 42),
   ('HeatFanMediumOutputGroup', 255),
   ('HeatFanHighOutputGroup', 255),
   ('InternalRelay1Group', 41),
   ('InternalRelay2Group', 2),
   ('InternalRelay3Group', 42),
   ('InternalRelay4Group', 4),
   ('InternalRelay5Group', 255),
   ('CoolingPlantFanSpeedControlEnable', 0),
   ('CoolingPlantFanSpeeds', 1),
   ('CoolingPlantFanDefaultSpeed', 1),
   ('CoolingPlantFanEnable', 1),
   ('HeatingPlantFanSpeedControlEnable', 0),
   ('HeatingPlantFanSpeeds', 1),
   ('HeatingPlantFanDefaultSpeed', 1),
   ('HeatingPlantFanEnable', 1)],
  [('create', 2, None, '[CG07] B (cool activation)'),
   ('create', 41, None, '[CG07] Y (heat/cool)'),
   ('ChangeTagName', 41, '[CG07] Y (heat/cool)', '[CG07] Y (heat/cool)'),
   ('create', 42, None, '[CG07] G (fan)'),
   ('ChangeTagName', 42, '[CG07] G (fan)', '[CG07] G (fan)'),
   ('create', 4, None, '[CG07] B (heat activation)')]),
 ('plant3-unused-only-Conventional Single Stage Heat/Cool USA System',
  3,
  'Conventional Single Stage Heat/Cool USA System',
  [(255, 'Unused')],
  {'CoolActivationOutput': 2,
   'CoolFanLowOutput': 3,
   'CoolStage1Output': 1,
   'CoolingPlantFanDefaultSpeed': 1,
   'CoolingPlantFanEnable': 1,
   'CoolingPlantFanSpeeds': 1,
   'HeatActivationOutput': 4,
   'HeatFanLowOutput': 3,
   'HeatStage1Output': 1,
   'HeatingPlantFanDefaultSpeed': 1,
   'HeatingPlantFanEnable': 1,
   'HeatingPlantFanSpeeds': 1,
   'InternalRelay1GroupNumber': 1,
   'InternalRelay2GroupNumber': 2,
   'InternalRelay3GroupNumber': 3,
   'InternalRelay4GroupNumber': 4},
  [(255, 'Unused'),
   (2, '[CG07] B (cool activation)'),
   (1, '[CG07] Y (heat/cool)'),
   (3, '[CG07] G (fan)'),
   (4, '[CG07] B (heat activation)')],
  [('CoolActivationOutputGroup', 2),
   ('CoolStage1OutputGroup', 1),
   ('CoolStage2OutputGroup', 255),
   ('CoolStage3OutputGroup', 255),
   ('CoolFanLowOutputGroup', 3),
   ('CoolFanMediumOutputGroup', 255),
   ('CoolFanHighOutputGroup', 255),
   ('HeatActivationOutputGroup', 4),
   ('HeatStage1OutputGroup', 1),
   ('HeatStage2OutputGroup', 255),
   ('HeatStage3OutputGroup', 255),
   ('HeatFanLowOutputGroup', 3),
   ('HeatFanMediumOutputGroup', 255),
   ('HeatFanHighOutputGroup', 255),
   ('InternalRelay1Group', 1),
   ('InternalRelay2Group', 2),
   ('InternalRelay3Group', 3),
   ('InternalRelay4Group', 4),
   ('InternalRelay5Group', 255),
   ('CoolingPlantFanSpeedControlEnable', 0),
   ('CoolingPlantFanSpeeds', 1),
   ('CoolingPlantFanDefaultSpeed', 1),
   ('CoolingPlantFanEnable', 1),
   ('HeatingPlantFanSpeedControlEnable', 0),
   ('HeatingPlantFanSpeeds', 1),
   ('HeatingPlantFanDefaultSpeed', 1),
   ('HeatingPlantFanEnable', 1)],
  [('create', 2, None, '[CG07] B (cool activation)'),
   ('create', 1, None, '[CG07] Y (heat/cool)'),
   ('create', 3, None, '[CG07] G (fan)'),
   ('create', 4, None, '[CG07] B (heat activation)')]),
 ('plant3-retained-prefix-collision-Conventional Single Stage Heat/Cool USA System',
  3,
  'Conventional Single Stage Heat/Cool USA System',
  [(255, 'Unused'),
   (0, 'Opaque zero'),
   (1, 'User Y'),
   (3, 'User G'),
   (5, 'User W'),
   (20, '[CG07] Previous twenty'),
   (40, '[CG07] Previous forty')],
  {'CoolActivationOutput': 2,
   'CoolFanLowOutput': 42,
   'CoolStage1Output': 41,
   'CoolingPlantFanDefaultSpeed': 1,
   'CoolingPlantFanEnable': 1,
   'CoolingPlantFanSpeeds': 1,
   'HeatActivationOutput': 4,
   'HeatFanLowOutput': 42,
   'HeatStage1Output': 41,
   'HeatingPlantFanDefaultSpeed': 1,
   'HeatingPlantFanEnable': 1,
   'HeatingPlantFanSpeeds': 1,
   'InternalRelay1GroupNumber': 41,
   'InternalRelay2GroupNumber': 2,
   'InternalRelay3GroupNumber': 42,
   'InternalRelay4GroupNumber': 4},
  [(255, 'Unused'),
   (0, 'Opaque zero'),
   (1, 'User Y'),
   (3, 'User G'),
   (5, 'User W'),
   (20, '[CG07] Previous twenty'),
   (40, '[CG07] Previous forty'),
   (2, '[CG07] B (cool activation)'),
   (41, '[CG07] Y (heat/cool)'),
   (42, '[CG07] G (fan)'),
   (4, '[CG07] B (heat activation)')],
  [('CoolActivationOutputGroup', 2),
   ('CoolStage1OutputGroup', 41),
   ('CoolStage2OutputGroup', 255),
   ('CoolStage3OutputGroup', 255),
   ('CoolFanLowOutputGroup', 42),
   ('CoolFanMediumOutputGroup', 255),
   ('CoolFanHighOutputGroup', 255),
   ('HeatActivationOutputGroup', 4),
   ('HeatStage1OutputGroup', 41),
   ('HeatStage2OutputGroup', 255),
   ('HeatStage3OutputGroup', 255),
   ('HeatFanLowOutputGroup', 42),
   ('HeatFanMediumOutputGroup', 255),
   ('HeatFanHighOutputGroup', 255),
   ('InternalRelay1Group', 41),
   ('InternalRelay2Group', 2),
   ('InternalRelay3Group', 42),
   ('InternalRelay4Group', 4),
   ('InternalRelay5Group', 255),
   ('CoolingPlantFanSpeedControlEnable', 0),
   ('CoolingPlantFanSpeeds', 1),
   ('CoolingPlantFanDefaultSpeed', 1),
   ('CoolingPlantFanEnable', 1),
   ('HeatingPlantFanSpeedControlEnable', 0),
   ('HeatingPlantFanSpeeds', 1),
   ('HeatingPlantFanDefaultSpeed', 1),
   ('HeatingPlantFanEnable', 1)],
  [('create', 2, None, '[CG07] B (cool activation)'),
   ('create', 41, None, '[CG07] Y (heat/cool)'),
   ('ChangeTagName', 41, '[CG07] Y (heat/cool)', '[CG07] Y (heat/cool)'),
   ('create', 42, None, '[CG07] G (fan)'),
   ('ChangeTagName', 42, '[CG07] G (fan)', '[CG07] G (fan)'),
   ('create', 4, None, '[CG07] B (heat activation)')]),
 ('plant3-unused-only-Unmatched retained name',
  3,
  'Unmatched retained name',
  [(255, 'Unused')],
  {'CoolActivationOutput': 2,
   'CoolFanLowOutput': 3,
   'CoolStage1Output': 1,
   'CoolingPlantFanDefaultSpeed': 1,
   'CoolingPlantFanEnable': 1,
   'CoolingPlantFanSpeeds': 1,
   'HeatActivationOutput': 4,
   'HeatFanLowOutput': 3,
   'HeatStage1Output': 1,
   'HeatingPlantFanDefaultSpeed': 1,
   'HeatingPlantFanEnable': 1,
   'HeatingPlantFanSpeeds': 1,
   'InternalRelay1GroupNumber': 1,
   'InternalRelay2GroupNumber': 2,
   'InternalRelay3GroupNumber': 3,
   'InternalRelay4GroupNumber': 4},
  [(255, 'Unused'),
   (2, '[CG07] B (cool activation)'),
   (1, '[CG07] Y (heat/cool)'),
   (3, '[CG07] G (fan)'),
   (4, '[CG07] B (heat activation)')],
  [('CoolActivationOutputGroup', 2),
   ('CoolStage1OutputGroup', 1),
   ('CoolStage2OutputGroup', 255),
   ('CoolStage3OutputGroup', 255),
   ('CoolFanLowOutputGroup', 3),
   ('CoolFanMediumOutputGroup', 255),
   ('CoolFanHighOutputGroup', 255),
   ('HeatActivationOutputGroup', 4),
   ('HeatStage1OutputGroup', 1),
   ('HeatStage2OutputGroup', 255),
   ('HeatStage3OutputGroup', 255),
   ('HeatFanLowOutputGroup', 3),
   ('HeatFanMediumOutputGroup', 255),
   ('HeatFanHighOutputGroup', 255),
   ('InternalRelay1Group', 1),
   ('InternalRelay2Group', 2),
   ('InternalRelay3Group', 3),
   ('InternalRelay4Group', 4),
   ('InternalRelay5Group', 255),
   ('CoolingPlantFanSpeedControlEnable', 0),
   ('CoolingPlantFanSpeeds', 1),
   ('CoolingPlantFanDefaultSpeed', 1),
   ('CoolingPlantFanEnable', 1),
   ('HeatingPlantFanSpeedControlEnable', 0),
   ('HeatingPlantFanSpeeds', 1),
   ('HeatingPlantFanDefaultSpeed', 1),
   ('HeatingPlantFanEnable', 1)],
  [('create', 2, None, '[CG07] B (cool activation)'),
   ('create', 1, None, '[CG07] Y (heat/cool)'),
   ('create', 3, None, '[CG07] G (fan)'),
   ('create', 4, None, '[CG07] B (heat activation)')]),
 ('plant3-retained-prefix-collision-Unmatched retained name',
  3,
  'Unmatched retained name',
  [(255, 'Unused'),
   (0, 'Opaque zero'),
   (1, 'User Y'),
   (3, 'User G'),
   (5, 'User W'),
   (20, '[CG07] Previous twenty'),
   (40, '[CG07] Previous forty')],
  {'CoolActivationOutput': 2,
   'CoolFanLowOutput': 42,
   'CoolStage1Output': 41,
   'CoolingPlantFanDefaultSpeed': 1,
   'CoolingPlantFanEnable': 1,
   'CoolingPlantFanSpeeds': 1,
   'HeatActivationOutput': 4,
   'HeatFanLowOutput': 42,
   'HeatStage1Output': 41,
   'HeatingPlantFanDefaultSpeed': 1,
   'HeatingPlantFanEnable': 1,
   'HeatingPlantFanSpeeds': 1,
   'InternalRelay1GroupNumber': 41,
   'InternalRelay2GroupNumber': 2,
   'InternalRelay3GroupNumber': 42,
   'InternalRelay4GroupNumber': 4},
  [(255, 'Unused'),
   (0, 'Opaque zero'),
   (1, 'User Y'),
   (3, 'User G'),
   (5, 'User W'),
   (20, '[CG07] Previous twenty'),
   (40, '[CG07] Previous forty'),
   (2, '[CG07] B (cool activation)'),
   (41, '[CG07] Y (heat/cool)'),
   (42, '[CG07] G (fan)'),
   (4, '[CG07] B (heat activation)')],
  [('CoolActivationOutputGroup', 2),
   ('CoolStage1OutputGroup', 41),
   ('CoolStage2OutputGroup', 255),
   ('CoolStage3OutputGroup', 255),
   ('CoolFanLowOutputGroup', 42),
   ('CoolFanMediumOutputGroup', 255),
   ('CoolFanHighOutputGroup', 255),
   ('HeatActivationOutputGroup', 4),
   ('HeatStage1OutputGroup', 41),
   ('HeatStage2OutputGroup', 255),
   ('HeatStage3OutputGroup', 255),
   ('HeatFanLowOutputGroup', 42),
   ('HeatFanMediumOutputGroup', 255),
   ('HeatFanHighOutputGroup', 255),
   ('InternalRelay1Group', 41),
   ('InternalRelay2Group', 2),
   ('InternalRelay3Group', 42),
   ('InternalRelay4Group', 4),
   ('InternalRelay5Group', 255),
   ('CoolingPlantFanSpeedControlEnable', 0),
   ('CoolingPlantFanSpeeds', 1),
   ('CoolingPlantFanDefaultSpeed', 1),
   ('CoolingPlantFanEnable', 1),
   ('HeatingPlantFanSpeedControlEnable', 0),
   ('HeatingPlantFanSpeeds', 1),
   ('HeatingPlantFanDefaultSpeed', 1),
   ('HeatingPlantFanEnable', 1)],
  [('create', 2, None, '[CG07] B (cool activation)'),
   ('create', 41, None, '[CG07] Y (heat/cool)'),
   ('ChangeTagName', 41, '[CG07] Y (heat/cool)', '[CG07] Y (heat/cool)'),
   ('create', 42, None, '[CG07] G (fan)'),
   ('ChangeTagName', 42, '[CG07] G (fan)', '[CG07] G (fan)'),
   ('create', 4, None, '[CG07] B (heat activation)')]),
 ('plant4-unused-only-nil',
  4,
  None,
  [(255, 'Unused')],
  {'CoolingPlantFanDefaultSpeed': 1,
   'CoolingPlantFanSpeeds': 1,
   'HeatFanLowOutput': 3,
   'HeatStage1Output': 1,
   'HeatingPlantFanDefaultSpeed': 1,
   'HeatingPlantFanEnable': 1,
   'HeatingPlantFanSpeedControlEnable': 1,
   'HeatingPlantFanSpeeds': 1,
   'InternalRelay1GroupNumber': 1,
   'InternalRelay3GroupNumber': 3},
  [(255, 'Unused'), (1, '[CG07] W (heat)'), (3, '[CG07] G (heat fan)')],
  [('CoolActivationOutputGroup', 255),
   ('CoolStage1OutputGroup', 255),
   ('CoolStage2OutputGroup', 255),
   ('CoolStage3OutputGroup', 255),
   ('CoolFanLowOutputGroup', 255),
   ('CoolFanMediumOutputGroup', 255),
   ('CoolFanHighOutputGroup', 255),
   ('HeatActivationOutputGroup', 255),
   ('HeatStage1OutputGroup', 1),
   ('HeatStage2OutputGroup', 255),
   ('HeatStage3OutputGroup', 255),
   ('HeatFanLowOutputGroup', 3),
   ('HeatFanMediumOutputGroup', 255),
   ('HeatFanHighOutputGroup', 255),
   ('InternalRelay1Group', 1),
   ('InternalRelay2Group', 255),
   ('InternalRelay3Group', 3),
   ('InternalRelay4Group', 255),
   ('InternalRelay5Group', 255),
   ('CoolingPlantFanSpeedControlEnable', 0),
   ('CoolingPlantFanSpeeds', 1),
   ('CoolingPlantFanDefaultSpeed', 1),
   ('CoolingPlantFanEnable', 0),
   ('HeatingPlantFanSpeedControlEnable', 1),
   ('HeatingPlantFanSpeeds', 1),
   ('HeatingPlantFanDefaultSpeed', 1),
   ('HeatingPlantFanEnable', 1)],
  [('create', 1, None, '[CG07] W (heat)'), ('create', 3, None, '[CG07] G (heat fan)')]),
 ('plant4-retained-prefix-collision-nil',
  4,
  None,
  [(255, 'Unused'),
   (0, 'Opaque zero'),
   (1, 'User Y'),
   (3, 'User G'),
   (5, 'User W'),
   (20, '[CG07] Previous twenty'),
   (40, '[CG07] Previous forty')],
  {'CoolingPlantFanDefaultSpeed': 1,
   'CoolingPlantFanSpeeds': 1,
   'HeatFanLowOutput': 42,
   'HeatStage1Output': 41,
   'HeatingPlantFanDefaultSpeed': 1,
   'HeatingPlantFanEnable': 1,
   'HeatingPlantFanSpeedControlEnable': 1,
   'HeatingPlantFanSpeeds': 1,
   'InternalRelay1GroupNumber': 41,
   'InternalRelay3GroupNumber': 42},
  [(255, 'Unused'),
   (0, 'Opaque zero'),
   (1, 'User Y'),
   (3, 'User G'),
   (5, 'User W'),
   (20, '[CG07] Previous twenty'),
   (40, '[CG07] Previous forty'),
   (41, '[CG07] W (heat)'),
   (42, '[CG07] G (heat fan)')],
  [('CoolActivationOutputGroup', 255),
   ('CoolStage1OutputGroup', 255),
   ('CoolStage2OutputGroup', 255),
   ('CoolStage3OutputGroup', 255),
   ('CoolFanLowOutputGroup', 255),
   ('CoolFanMediumOutputGroup', 255),
   ('CoolFanHighOutputGroup', 255),
   ('HeatActivationOutputGroup', 255),
   ('HeatStage1OutputGroup', 41),
   ('HeatStage2OutputGroup', 255),
   ('HeatStage3OutputGroup', 255),
   ('HeatFanLowOutputGroup', 42),
   ('HeatFanMediumOutputGroup', 255),
   ('HeatFanHighOutputGroup', 255),
   ('InternalRelay1Group', 41),
   ('InternalRelay2Group', 255),
   ('InternalRelay3Group', 42),
   ('InternalRelay4Group', 255),
   ('InternalRelay5Group', 255),
   ('CoolingPlantFanSpeedControlEnable', 0),
   ('CoolingPlantFanSpeeds', 1),
   ('CoolingPlantFanDefaultSpeed', 1),
   ('CoolingPlantFanEnable', 0),
   ('HeatingPlantFanSpeedControlEnable', 1),
   ('HeatingPlantFanSpeeds', 1),
   ('HeatingPlantFanDefaultSpeed', 1),
   ('HeatingPlantFanEnable', 1)],
  [('create', 41, None, '[CG07] W (heat)'),
   ('ChangeTagName', 41, '[CG07] W (heat)', '[CG07] W (heat)'),
   ('create', 42, None, '[CG07] G (heat fan)'),
   ('ChangeTagName', 42, '[CG07] G (heat fan)', '[CG07] G (heat fan)')]),
 ('plant5-unused-only-nil',
  5,
  None,
  [(255, 'Unused')],
  {'CoolFanLowOutput': 3,
   'CoolStage1Output': 1,
   'CoolingPlantFanDefaultSpeed': 1,
   'CoolingPlantFanEnable': 1,
   'CoolingPlantFanSpeedControlEnable': 1,
   'CoolingPlantFanSpeeds': 1,
   'HeatingPlantFanDefaultSpeed': 1,
   'HeatingPlantFanSpeeds': 1,
   'InternalRelay1GroupNumber': 1,
   'InternalRelay3GroupNumber': 3},
  [(255, 'Unused'), (1, '[CG07] Y (cool)'), (3, '[CG07] G (cool fan)')],
  [('CoolActivationOutputGroup', 255),
   ('CoolStage1OutputGroup', 1),
   ('CoolStage2OutputGroup', 255),
   ('CoolStage3OutputGroup', 255),
   ('CoolFanLowOutputGroup', 3),
   ('CoolFanMediumOutputGroup', 255),
   ('CoolFanHighOutputGroup', 255),
   ('HeatActivationOutputGroup', 255),
   ('HeatStage1OutputGroup', 255),
   ('HeatStage2OutputGroup', 255),
   ('HeatStage3OutputGroup', 255),
   ('HeatFanLowOutputGroup', 255),
   ('HeatFanMediumOutputGroup', 255),
   ('HeatFanHighOutputGroup', 255),
   ('InternalRelay1Group', 1),
   ('InternalRelay2Group', 255),
   ('InternalRelay3Group', 3),
   ('InternalRelay4Group', 255),
   ('InternalRelay5Group', 255),
   ('CoolingPlantFanSpeedControlEnable', 1),
   ('CoolingPlantFanSpeeds', 1),
   ('CoolingPlantFanDefaultSpeed', 1),
   ('CoolingPlantFanEnable', 1),
   ('HeatingPlantFanSpeedControlEnable', 0),
   ('HeatingPlantFanSpeeds', 1),
   ('HeatingPlantFanDefaultSpeed', 1),
   ('HeatingPlantFanEnable', 0)],
  [('create', 1, None, '[CG07] Y (cool)'), ('create', 3, None, '[CG07] G (cool fan)')]),
 ('plant5-retained-prefix-collision-nil',
  5,
  None,
  [(255, 'Unused'),
   (0, 'Opaque zero'),
   (1, 'User Y'),
   (3, 'User G'),
   (5, 'User W'),
   (20, '[CG07] Previous twenty'),
   (40, '[CG07] Previous forty')],
  {'CoolFanLowOutput': 42,
   'CoolStage1Output': 41,
   'CoolingPlantFanDefaultSpeed': 1,
   'CoolingPlantFanEnable': 1,
   'CoolingPlantFanSpeedControlEnable': 1,
   'CoolingPlantFanSpeeds': 1,
   'HeatingPlantFanDefaultSpeed': 1,
   'HeatingPlantFanSpeeds': 1,
   'InternalRelay1GroupNumber': 41,
   'InternalRelay3GroupNumber': 42},
  [(255, 'Unused'),
   (0, 'Opaque zero'),
   (1, 'User Y'),
   (3, 'User G'),
   (5, 'User W'),
   (20, '[CG07] Previous twenty'),
   (40, '[CG07] Previous forty'),
   (41, '[CG07] Y (cool)'),
   (42, '[CG07] G (cool fan)')],
  [('CoolActivationOutputGroup', 255),
   ('CoolStage1OutputGroup', 41),
   ('CoolStage2OutputGroup', 255),
   ('CoolStage3OutputGroup', 255),
   ('CoolFanLowOutputGroup', 42),
   ('CoolFanMediumOutputGroup', 255),
   ('CoolFanHighOutputGroup', 255),
   ('HeatActivationOutputGroup', 255),
   ('HeatStage1OutputGroup', 255),
   ('HeatStage2OutputGroup', 255),
   ('HeatStage3OutputGroup', 255),
   ('HeatFanLowOutputGroup', 255),
   ('HeatFanMediumOutputGroup', 255),
   ('HeatFanHighOutputGroup', 255),
   ('InternalRelay1Group', 41),
   ('InternalRelay2Group', 255),
   ('InternalRelay3Group', 42),
   ('InternalRelay4Group', 255),
   ('InternalRelay5Group', 255),
   ('CoolingPlantFanSpeedControlEnable', 1),
   ('CoolingPlantFanSpeeds', 1),
   ('CoolingPlantFanDefaultSpeed', 1),
   ('CoolingPlantFanEnable', 1),
   ('HeatingPlantFanSpeedControlEnable', 0),
   ('HeatingPlantFanSpeeds', 1),
   ('HeatingPlantFanDefaultSpeed', 1),
   ('HeatingPlantFanEnable', 0)],
  [('create', 41, None, '[CG07] Y (cool)'),
   ('ChangeTagName', 41, '[CG07] Y (cool)', '[CG07] Y (cool)'),
   ('create', 42, None, '[CG07] G (cool fan)'),
   ('ChangeTagName', 42, '[CG07] G (cool fan)', '[CG07] G (cool fan)')]),
 ('plant6-unused-only-nil',
  6,
  None,
  [(255, 'Unused')],
  {'CoolFanHighOutput': 14,
   'CoolFanLowOutput': 12,
   'CoolFanMediumOutput': 13,
   'CoolStage1Output': 10,
   'CoolStage2Output': 11,
   'CoolingPlantFanDefaultSpeed': 1,
   'CoolingPlantFanEnable': 1,
   'CoolingPlantFanSpeedControlEnable': 1,
   'CoolingPlantFanSpeeds': 3,
   'HeatFanLowOutput': 3,
   'HeatFanMediumOutput': 4,
   'HeatStage1Output': 5,
   'HeatingPlantFanDefaultSpeed': 1,
   'HeatingPlantFanEnable': 1,
   'HeatingPlantFanSpeedControlEnable': 1,
   'HeatingPlantFanSpeeds': 2,
   'InternalRelay3GroupNumber': 3,
   'InternalRelay4GroupNumber': 4,
   'InternalRelay5GroupNumber': 5},
  [(255, 'Unused'),
   (10, '[CG07] pump'),
   (11, '[CG07] dump'),
   (12, '[CG07] cool fan speed 1'),
   (13, '[CG07] cool fan speed 2'),
   (14, '[CG07] cool fan speed 3'),
   (5, '[CG07] W (heat)'),
   (3, '[CG07] G1 (heat fan speed 1)'),
   (4, '[CG07] G2 (heat fan speed 2)')],
  [('CoolActivationOutputGroup', 255),
   ('CoolStage1OutputGroup', 10),
   ('CoolStage2OutputGroup', 11),
   ('CoolStage3OutputGroup', 255),
   ('CoolFanLowOutputGroup', 12),
   ('CoolFanMediumOutputGroup', 13),
   ('CoolFanHighOutputGroup', 14),
   ('HeatActivationOutputGroup', 255),
   ('HeatStage1OutputGroup', 5),
   ('HeatStage2OutputGroup', 255),
   ('HeatStage3OutputGroup', 255),
   ('HeatFanLowOutputGroup', 3),
   ('HeatFanMediumOutputGroup', 4),
   ('HeatFanHighOutputGroup', 255),
   ('InternalRelay1Group', 255),
   ('InternalRelay2Group', 255),
   ('InternalRelay3Group', 3),
   ('InternalRelay4Group', 4),
   ('InternalRelay5Group', 5),
   ('CoolingPlantFanSpeedControlEnable', 1),
   ('CoolingPlantFanSpeeds', 3),
   ('CoolingPlantFanDefaultSpeed', 1),
   ('CoolingPlantFanEnable', 1),
   ('HeatingPlantFanSpeedControlEnable', 1),
   ('HeatingPlantFanSpeeds', 2),
   ('HeatingPlantFanDefaultSpeed', 1),
   ('HeatingPlantFanEnable', 1)],
  [('create', 10, None, '[CG07] pump'),
   ('create', 11, None, '[CG07] dump'),
   ('create', 12, None, '[CG07] cool fan speed 1'),
   ('create', 13, None, '[CG07] cool fan speed 2'),
   ('create', 14, None, '[CG07] cool fan speed 3'),
   ('create', 5, None, '[CG07] W (heat)'),
   ('create', 3, None, '[CG07] G1 (heat fan speed 1)'),
   ('create', 4, None, '[CG07] G2 (heat fan speed 2)')]),
 ('plant6-retained-prefix-collision-nil',
  6,
  None,
  [(255, 'Unused'),
   (0, 'Opaque zero'),
   (1, 'User Y'),
   (3, 'User G'),
   (5, 'User W'),
   (20, '[CG07] Previous twenty'),
   (40, '[CG07] Previous forty')],
  {'CoolFanHighOutput': 14,
   'CoolFanLowOutput': 12,
   'CoolFanMediumOutput': 13,
   'CoolStage1Output': 10,
   'CoolStage2Output': 11,
   'CoolingPlantFanDefaultSpeed': 1,
   'CoolingPlantFanEnable': 1,
   'CoolingPlantFanSpeedControlEnable': 1,
   'CoolingPlantFanSpeeds': 3,
   'HeatFanLowOutput': 42,
   'HeatFanMediumOutput': 4,
   'HeatStage1Output': 41,
   'HeatingPlantFanDefaultSpeed': 1,
   'HeatingPlantFanEnable': 1,
   'HeatingPlantFanSpeedControlEnable': 1,
   'HeatingPlantFanSpeeds': 2,
   'InternalRelay3GroupNumber': 42,
   'InternalRelay4GroupNumber': 4,
   'InternalRelay5GroupNumber': 41},
  [(255, 'Unused'),
   (0, 'Opaque zero'),
   (1, 'User Y'),
   (3, 'User G'),
   (5, 'User W'),
   (20, '[CG07] Previous twenty'),
   (40, '[CG07] Previous forty'),
   (10, '[CG07] pump'),
   (11, '[CG07] dump'),
   (12, '[CG07] cool fan speed 1'),
   (13, '[CG07] cool fan speed 2'),
   (14, '[CG07] cool fan speed 3'),
   (41, '[CG07] W (heat)'),
   (42, '[CG07] G1 (heat fan speed 1)'),
   (4, '[CG07] G2 (heat fan speed 2)')],
  [('CoolActivationOutputGroup', 255),
   ('CoolStage1OutputGroup', 10),
   ('CoolStage2OutputGroup', 11),
   ('CoolStage3OutputGroup', 255),
   ('CoolFanLowOutputGroup', 12),
   ('CoolFanMediumOutputGroup', 13),
   ('CoolFanHighOutputGroup', 14),
   ('HeatActivationOutputGroup', 255),
   ('HeatStage1OutputGroup', 41),
   ('HeatStage2OutputGroup', 255),
   ('HeatStage3OutputGroup', 255),
   ('HeatFanLowOutputGroup', 42),
   ('HeatFanMediumOutputGroup', 4),
   ('HeatFanHighOutputGroup', 255),
   ('InternalRelay1Group', 255),
   ('InternalRelay2Group', 255),
   ('InternalRelay3Group', 42),
   ('InternalRelay4Group', 4),
   ('InternalRelay5Group', 41),
   ('CoolingPlantFanSpeedControlEnable', 1),
   ('CoolingPlantFanSpeeds', 3),
   ('CoolingPlantFanDefaultSpeed', 1),
   ('CoolingPlantFanEnable', 1),
   ('HeatingPlantFanSpeedControlEnable', 1),
   ('HeatingPlantFanSpeeds', 2),
   ('HeatingPlantFanDefaultSpeed', 1),
   ('HeatingPlantFanEnable', 1)],
  [('create', 10, None, '[CG07] pump'),
   ('create', 11, None, '[CG07] dump'),
   ('create', 12, None, '[CG07] cool fan speed 1'),
   ('create', 13, None, '[CG07] cool fan speed 2'),
   ('create', 14, None, '[CG07] cool fan speed 3'),
   ('create', 41, None, '[CG07] W (heat)'),
   ('ChangeTagName', 41, '[CG07] W (heat)', '[CG07] W (heat)'),
   ('create', 42, None, '[CG07] G1 (heat fan speed 1)'),
   ('ChangeTagName', 42, '[CG07] G1 (heat fan speed 1)', '[CG07] G1 (heat fan speed 1)'),
   ('create', 4, None, '[CG07] G2 (heat fan speed 2)')]),
 ('plant7-unused-only-nil',
  7,
  None,
  [(255, 'Unused')],
  {'CoolFanLowOutput': 3,
   'CoolStage1Output': 1,
   'CoolingPlantFanDefaultSpeed': 1,
   'CoolingPlantFanEnable': 1,
   'CoolingPlantFanSpeedControlEnable': 1,
   'CoolingPlantFanSpeeds': 1,
   'HeatFanLowOutput': 4,
   'HeatStage1Output': 5,
   'HeatingPlantFanDefaultSpeed': 1,
   'HeatingPlantFanEnable': 1,
   'HeatingPlantFanSpeedControlEnable': 1,
   'HeatingPlantFanSpeeds': 1,
   'InternalRelay1GroupNumber': 1,
   'InternalRelay3GroupNumber': 3,
   'InternalRelay4GroupNumber': 4,
   'InternalRelay5GroupNumber': 5},
  [(255, 'Unused'),
   (1, '[CG07] Y (cool)'),
   (3, '[CG07] G (cool fan)'),
   (5, '[CG07] W (heat)'),
   (4, '[CG07] G (heat fan)')],
  [('CoolActivationOutputGroup', 255),
   ('CoolStage1OutputGroup', 1),
   ('CoolStage2OutputGroup', 255),
   ('CoolStage3OutputGroup', 255),
   ('CoolFanLowOutputGroup', 3),
   ('CoolFanMediumOutputGroup', 255),
   ('CoolFanHighOutputGroup', 255),
   ('HeatActivationOutputGroup', 255),
   ('HeatStage1OutputGroup', 5),
   ('HeatStage2OutputGroup', 255),
   ('HeatStage3OutputGroup', 255),
   ('HeatFanLowOutputGroup', 4),
   ('HeatFanMediumOutputGroup', 255),
   ('HeatFanHighOutputGroup', 255),
   ('InternalRelay1Group', 1),
   ('InternalRelay2Group', 255),
   ('InternalRelay3Group', 3),
   ('InternalRelay4Group', 4),
   ('InternalRelay5Group', 5),
   ('CoolingPlantFanSpeedControlEnable', 1),
   ('CoolingPlantFanSpeeds', 1),
   ('CoolingPlantFanDefaultSpeed', 1),
   ('CoolingPlantFanEnable', 1),
   ('HeatingPlantFanSpeedControlEnable', 1),
   ('HeatingPlantFanSpeeds', 1),
   ('HeatingPlantFanDefaultSpeed', 1),
   ('HeatingPlantFanEnable', 1)],
  [('create', 1, None, '[CG07] Y (cool)'),
   ('create', 3, None, '[CG07] G (cool fan)'),
   ('create', 5, None, '[CG07] W (heat)'),
   ('create', 4, None, '[CG07] G (heat fan)')]),
 ('plant7-retained-prefix-collision-nil',
  7,
  None,
  [(255, 'Unused'),
   (0, 'Opaque zero'),
   (1, 'User Y'),
   (3, 'User G'),
   (5, 'User W'),
   (20, '[CG07] Previous twenty'),
   (40, '[CG07] Previous forty')],
  {'CoolFanLowOutput': 42,
   'CoolStage1Output': 41,
   'CoolingPlantFanDefaultSpeed': 1,
   'CoolingPlantFanEnable': 1,
   'CoolingPlantFanSpeedControlEnable': 1,
   'CoolingPlantFanSpeeds': 1,
   'HeatFanLowOutput': 4,
   'HeatStage1Output': 43,
   'HeatingPlantFanDefaultSpeed': 1,
   'HeatingPlantFanEnable': 1,
   'HeatingPlantFanSpeedControlEnable': 1,
   'HeatingPlantFanSpeeds': 1,
   'InternalRelay1GroupNumber': 41,
   'InternalRelay3GroupNumber': 42,
   'InternalRelay4GroupNumber': 4,
   'InternalRelay5GroupNumber': 43},
  [(255, 'Unused'),
   (0, 'Opaque zero'),
   (1, 'User Y'),
   (3, 'User G'),
   (5, 'User W'),
   (20, '[CG07] Previous twenty'),
   (40, '[CG07] Previous forty'),
   (41, '[CG07] Y (cool)'),
   (42, '[CG07] G (cool fan)'),
   (43, '[CG07] W (heat)'),
   (4, '[CG07] G (heat fan)')],
  [('CoolActivationOutputGroup', 255),
   ('CoolStage1OutputGroup', 41),
   ('CoolStage2OutputGroup', 255),
   ('CoolStage3OutputGroup', 255),
   ('CoolFanLowOutputGroup', 42),
   ('CoolFanMediumOutputGroup', 255),
   ('CoolFanHighOutputGroup', 255),
   ('HeatActivationOutputGroup', 255),
   ('HeatStage1OutputGroup', 43),
   ('HeatStage2OutputGroup', 255),
   ('HeatStage3OutputGroup', 255),
   ('HeatFanLowOutputGroup', 4),
   ('HeatFanMediumOutputGroup', 255),
   ('HeatFanHighOutputGroup', 255),
   ('InternalRelay1Group', 41),
   ('InternalRelay2Group', 255),
   ('InternalRelay3Group', 42),
   ('InternalRelay4Group', 4),
   ('InternalRelay5Group', 43),
   ('CoolingPlantFanSpeedControlEnable', 1),
   ('CoolingPlantFanSpeeds', 1),
   ('CoolingPlantFanDefaultSpeed', 1),
   ('CoolingPlantFanEnable', 1),
   ('HeatingPlantFanSpeedControlEnable', 1),
   ('HeatingPlantFanSpeeds', 1),
   ('HeatingPlantFanDefaultSpeed', 1),
   ('HeatingPlantFanEnable', 1)],
  [('create', 41, None, '[CG07] Y (cool)'),
   ('ChangeTagName', 41, '[CG07] Y (cool)', '[CG07] Y (cool)'),
   ('create', 42, None, '[CG07] G (cool fan)'),
   ('ChangeTagName', 42, '[CG07] G (cool fan)', '[CG07] G (cool fan)'),
   ('create', 43, None, '[CG07] W (heat)'),
   ('ChangeTagName', 43, '[CG07] W (heat)', '[CG07] W (heat)'),
   ('create', 4, None, '[CG07] G (heat fan)')]),
 ('plant8-unused-only-nil',
  8,
  None,
  [(255, 'Unused')],
  {'CoolingPlantFanDefaultSpeed': 1,
   'CoolingPlantFanSpeeds': 1,
   'HeatStage1Output': 5,
   'HeatingPlantFanDefaultSpeed': 1,
   'HeatingPlantFanEnable': 1,
   'HeatingPlantFanSpeeds': 1,
   'InternalRelay5GroupNumber': 5},
  [(255, 'Unused'), (5, '[CG07] W (heat)')],
  [('CoolActivationOutputGroup', 255),
   ('CoolStage1OutputGroup', 255),
   ('CoolStage2OutputGroup', 255),
   ('CoolStage3OutputGroup', 255),
   ('CoolFanLowOutputGroup', 255),
   ('CoolFanMediumOutputGroup', 255),
   ('CoolFanHighOutputGroup', 255),
   ('HeatActivationOutputGroup', 255),
   ('HeatStage1OutputGroup', 5),
   ('HeatStage2OutputGroup', 255),
   ('HeatStage3OutputGroup', 255),
   ('HeatFanLowOutputGroup', 255),
   ('HeatFanMediumOutputGroup', 255),
   ('HeatFanHighOutputGroup', 255),
   ('InternalRelay1Group', 255),
   ('InternalRelay2Group', 255),
   ('InternalRelay3Group', 255),
   ('InternalRelay4Group', 255),
   ('InternalRelay5Group', 5),
   ('DamperZone1OutputGroup', 255),
   ('DamperZone2OutputGroup', 255),
   ('DamperZone3OutputGroup', 255),
   ('DamperZone4OutputGroup', 255),
   ('CoolingPlantFanSpeedControlEnable', 0),
   ('CoolingPlantFanSpeeds', 1),
   ('CoolingPlantFanDefaultSpeed', 1),
   ('CoolingPlantFanEnable', 0),
   ('HeatingPlantFanSpeedControlEnable', 0),
   ('HeatingPlantFanSpeeds', 1),
   ('HeatingPlantFanDefaultSpeed', 1),
   ('HeatingPlantFanEnable', 1)],
  [('create', 5, None, '[CG07] W (heat)')]),
 ('plant8-retained-prefix-collision-nil',
  8,
  None,
  [(255, 'Unused'),
   (0, 'Opaque zero'),
   (1, 'User Y'),
   (3, 'User G'),
   (5, 'User W'),
   (20, '[CG07] Previous twenty'),
   (40, '[CG07] Previous forty')],
  {'CoolingPlantFanDefaultSpeed': 1,
   'CoolingPlantFanSpeeds': 1,
   'HeatStage1Output': 41,
   'HeatingPlantFanDefaultSpeed': 1,
   'HeatingPlantFanEnable': 1,
   'HeatingPlantFanSpeeds': 1,
   'InternalRelay5GroupNumber': 41},
  [(255, 'Unused'),
   (0, 'Opaque zero'),
   (1, 'User Y'),
   (3, 'User G'),
   (5, 'User W'),
   (20, '[CG07] Previous twenty'),
   (40, '[CG07] Previous forty'),
   (41, '[CG07] W (heat)')],
  [('CoolActivationOutputGroup', 255),
   ('CoolStage1OutputGroup', 255),
   ('CoolStage2OutputGroup', 255),
   ('CoolStage3OutputGroup', 255),
   ('CoolFanLowOutputGroup', 255),
   ('CoolFanMediumOutputGroup', 255),
   ('CoolFanHighOutputGroup', 255),
   ('HeatActivationOutputGroup', 255),
   ('HeatStage1OutputGroup', 41),
   ('HeatStage2OutputGroup', 255),
   ('HeatStage3OutputGroup', 255),
   ('HeatFanLowOutputGroup', 255),
   ('HeatFanMediumOutputGroup', 255),
   ('HeatFanHighOutputGroup', 255),
   ('InternalRelay1Group', 255),
   ('InternalRelay2Group', 255),
   ('InternalRelay3Group', 255),
   ('InternalRelay4Group', 255),
   ('InternalRelay5Group', 41),
   ('DamperZone1OutputGroup', 255),
   ('DamperZone2OutputGroup', 255),
   ('DamperZone3OutputGroup', 255),
   ('DamperZone4OutputGroup', 255),
   ('CoolingPlantFanSpeedControlEnable', 0),
   ('CoolingPlantFanSpeeds', 1),
   ('CoolingPlantFanDefaultSpeed', 1),
   ('CoolingPlantFanEnable', 0),
   ('HeatingPlantFanSpeedControlEnable', 0),
   ('HeatingPlantFanSpeeds', 1),
   ('HeatingPlantFanDefaultSpeed', 1),
   ('HeatingPlantFanEnable', 1)],
  [('create', 41, None, '[CG07] W (heat)'), ('ChangeTagName', 41, '[CG07] W (heat)', '[CG07] W (heat)')]),
 ('plant9-unused-only-nil',
  9,
  None,
  [(255, 'Unused')],
  {'CoolFanLowOutput': 3,
   'CoolStage1Output': 1,
   'CoolingPlantFanDefaultSpeed': 1,
   'CoolingPlantFanEnable': 1,
   'CoolingPlantFanSpeedControlEnable': 1,
   'CoolingPlantFanSpeeds': 1,
   'HeatStage1Output': 5,
   'HeatingPlantFanDefaultSpeed': 1,
   'HeatingPlantFanSpeeds': 1,
   'InternalRelay1GroupNumber': 1,
   'InternalRelay3GroupNumber': 3,
   'InternalRelay5GroupNumber': 5},
  [(255, 'Unused'), (1, '[CG07] Y (cool)'), (3, '[CG07] G (fan)'), (5, '[CG07] W (heat)')],
  [('CoolActivationOutputGroup', 255),
   ('CoolStage1OutputGroup', 1),
   ('CoolStage2OutputGroup', 255),
   ('CoolStage3OutputGroup', 255),
   ('CoolFanLowOutputGroup', 3),
   ('CoolFanMediumOutputGroup', 255),
   ('CoolFanHighOutputGroup', 255),
   ('HeatActivationOutputGroup', 255),
   ('HeatStage1OutputGroup', 5),
   ('HeatStage2OutputGroup', 255),
   ('HeatStage3OutputGroup', 255),
   ('HeatFanLowOutputGroup', 255),
   ('HeatFanMediumOutputGroup', 255),
   ('HeatFanHighOutputGroup', 255),
   ('InternalRelay1Group', 1),
   ('InternalRelay2Group', 255),
   ('InternalRelay3Group', 3),
   ('InternalRelay4Group', 255),
   ('InternalRelay5Group', 5),
   ('CoolingPlantFanSpeedControlEnable', 1),
   ('CoolingPlantFanSpeeds', 1),
   ('CoolingPlantFanDefaultSpeed', 1),
   ('CoolingPlantFanEnable', 1),
   ('HeatingPlantFanSpeedControlEnable', 0),
   ('HeatingPlantFanSpeeds', 1),
   ('HeatingPlantFanDefaultSpeed', 1),
   ('HeatingPlantFanEnable', 0)],
  [('create', 1, None, '[CG07] Y (cool)'),
   ('create', 3, None, '[CG07] G (fan)'),
   ('create', 5, None, '[CG07] W (heat)')]),
 ('plant9-retained-prefix-collision-nil',
  9,
  None,
  [(255, 'Unused'),
   (0, 'Opaque zero'),
   (1, 'User Y'),
   (3, 'User G'),
   (5, 'User W'),
   (20, '[CG07] Previous twenty'),
   (40, '[CG07] Previous forty')],
  {'CoolFanLowOutput': 42,
   'CoolStage1Output': 41,
   'CoolingPlantFanDefaultSpeed': 1,
   'CoolingPlantFanEnable': 1,
   'CoolingPlantFanSpeedControlEnable': 1,
   'CoolingPlantFanSpeeds': 1,
   'HeatStage1Output': 43,
   'HeatingPlantFanDefaultSpeed': 1,
   'HeatingPlantFanSpeeds': 1,
   'InternalRelay1GroupNumber': 41,
   'InternalRelay3GroupNumber': 42,
   'InternalRelay5GroupNumber': 43},
  [(255, 'Unused'),
   (0, 'Opaque zero'),
   (1, 'User Y'),
   (3, 'User G'),
   (5, 'User W'),
   (20, '[CG07] Previous twenty'),
   (40, '[CG07] Previous forty'),
   (41, '[CG07] Y (cool)'),
   (42, '[CG07] G (fan)'),
   (43, '[CG07] W (heat)')],
  [('CoolActivationOutputGroup', 255),
   ('CoolStage1OutputGroup', 41),
   ('CoolStage2OutputGroup', 255),
   ('CoolStage3OutputGroup', 255),
   ('CoolFanLowOutputGroup', 42),
   ('CoolFanMediumOutputGroup', 255),
   ('CoolFanHighOutputGroup', 255),
   ('HeatActivationOutputGroup', 255),
   ('HeatStage1OutputGroup', 43),
   ('HeatStage2OutputGroup', 255),
   ('HeatStage3OutputGroup', 255),
   ('HeatFanLowOutputGroup', 255),
   ('HeatFanMediumOutputGroup', 255),
   ('HeatFanHighOutputGroup', 255),
   ('InternalRelay1Group', 41),
   ('InternalRelay2Group', 255),
   ('InternalRelay3Group', 42),
   ('InternalRelay4Group', 255),
   ('InternalRelay5Group', 43),
   ('CoolingPlantFanSpeedControlEnable', 1),
   ('CoolingPlantFanSpeeds', 1),
   ('CoolingPlantFanDefaultSpeed', 1),
   ('CoolingPlantFanEnable', 1),
   ('HeatingPlantFanSpeedControlEnable', 0),
   ('HeatingPlantFanSpeeds', 1),
   ('HeatingPlantFanDefaultSpeed', 1),
   ('HeatingPlantFanEnable', 0)],
  [('create', 41, None, '[CG07] Y (cool)'),
   ('ChangeTagName', 41, '[CG07] Y (cool)', '[CG07] Y (cool)'),
   ('create', 42, None, '[CG07] G (fan)'),
   ('ChangeTagName', 42, '[CG07] G (fan)', '[CG07] G (fan)'),
   ('create', 43, None, '[CG07] W (heat)'),
   ('ChangeTagName', 43, '[CG07] W (heat)', '[CG07] W (heat)')]),
 ('plant9-unused-only-Zoned 2 Stage Reverse Cycle System',
  9,
  'Zoned 2 Stage Reverse Cycle System',
  [(255, 'Unused')],
  {'CoolFanLowOutput': 3,
   'CoolStage1Output': 1,
   'CoolingPlantFanDefaultSpeed': 1,
   'CoolingPlantFanEnable': 1,
   'CoolingPlantFanSpeedControlEnable': 1,
   'CoolingPlantFanSpeeds': 1,
   'HeatStage1Output': 5,
   'HeatingPlantFanDefaultSpeed': 1,
   'HeatingPlantFanSpeeds': 1,
   'InternalRelay1GroupNumber': 1,
   'InternalRelay3GroupNumber': 3,
   'InternalRelay5GroupNumber': 5},
  [(255, 'Unused'), (1, '[CG07] Y (cool)'), (3, '[CG07] G (fan)'), (5, '[CG07] W (heat)')],
  [('CoolActivationOutputGroup', 255),
   ('CoolStage1OutputGroup', 1),
   ('CoolStage2OutputGroup', 255),
   ('CoolStage3OutputGroup', 255),
   ('CoolFanLowOutputGroup', 3),
   ('CoolFanMediumOutputGroup', 255),
   ('CoolFanHighOutputGroup', 255),
   ('HeatActivationOutputGroup', 255),
   ('HeatStage1OutputGroup', 5),
   ('HeatStage2OutputGroup', 255),
   ('HeatStage3OutputGroup', 255),
   ('HeatFanLowOutputGroup', 255),
   ('HeatFanMediumOutputGroup', 255),
   ('HeatFanHighOutputGroup', 255),
   ('InternalRelay1Group', 1),
   ('InternalRelay2Group', 255),
   ('InternalRelay3Group', 3),
   ('InternalRelay4Group', 255),
   ('InternalRelay5Group', 5),
   ('CoolingPlantFanSpeedControlEnable', 1),
   ('CoolingPlantFanSpeeds', 1),
   ('CoolingPlantFanDefaultSpeed', 1),
   ('CoolingPlantFanEnable', 1),
   ('HeatingPlantFanSpeedControlEnable', 0),
   ('HeatingPlantFanSpeeds', 1),
   ('HeatingPlantFanDefaultSpeed', 1),
   ('HeatingPlantFanEnable', 0)],
  [('create', 1, None, '[CG07] Y (cool)'),
   ('create', 3, None, '[CG07] G (fan)'),
   ('create', 5, None, '[CG07] W (heat)')]),
 ('plant9-retained-prefix-collision-Zoned 2 Stage Reverse Cycle System',
  9,
  'Zoned 2 Stage Reverse Cycle System',
  [(255, 'Unused'),
   (0, 'Opaque zero'),
   (1, 'User Y'),
   (3, 'User G'),
   (5, 'User W'),
   (20, '[CG07] Previous twenty'),
   (40, '[CG07] Previous forty')],
  {'CoolFanLowOutput': 42,
   'CoolStage1Output': 41,
   'CoolingPlantFanDefaultSpeed': 1,
   'CoolingPlantFanEnable': 1,
   'CoolingPlantFanSpeedControlEnable': 1,
   'CoolingPlantFanSpeeds': 1,
   'HeatStage1Output': 43,
   'HeatingPlantFanDefaultSpeed': 1,
   'HeatingPlantFanSpeeds': 1,
   'InternalRelay1GroupNumber': 41,
   'InternalRelay3GroupNumber': 42,
   'InternalRelay5GroupNumber': 43},
  [(255, 'Unused'),
   (0, 'Opaque zero'),
   (1, 'User Y'),
   (3, 'User G'),
   (5, 'User W'),
   (20, '[CG07] Previous twenty'),
   (40, '[CG07] Previous forty'),
   (41, '[CG07] Y (cool)'),
   (42, '[CG07] G (fan)'),
   (43, '[CG07] W (heat)')],
  [('CoolActivationOutputGroup', 255),
   ('CoolStage1OutputGroup', 41),
   ('CoolStage2OutputGroup', 255),
   ('CoolStage3OutputGroup', 255),
   ('CoolFanLowOutputGroup', 42),
   ('CoolFanMediumOutputGroup', 255),
   ('CoolFanHighOutputGroup', 255),
   ('HeatActivationOutputGroup', 255),
   ('HeatStage1OutputGroup', 43),
   ('HeatStage2OutputGroup', 255),
   ('HeatStage3OutputGroup', 255),
   ('HeatFanLowOutputGroup', 255),
   ('HeatFanMediumOutputGroup', 255),
   ('HeatFanHighOutputGroup', 255),
   ('InternalRelay1Group', 41),
   ('InternalRelay2Group', 255),
   ('InternalRelay3Group', 42),
   ('InternalRelay4Group', 255),
   ('InternalRelay5Group', 43),
   ('CoolingPlantFanSpeedControlEnable', 1),
   ('CoolingPlantFanSpeeds', 1),
   ('CoolingPlantFanDefaultSpeed', 1),
   ('CoolingPlantFanEnable', 1),
   ('HeatingPlantFanSpeedControlEnable', 0),
   ('HeatingPlantFanSpeeds', 1),
   ('HeatingPlantFanDefaultSpeed', 1),
   ('HeatingPlantFanEnable', 0)],
  [('create', 41, None, '[CG07] Y (cool)'),
   ('ChangeTagName', 41, '[CG07] Y (cool)', '[CG07] Y (cool)'),
   ('create', 42, None, '[CG07] G (fan)'),
   ('ChangeTagName', 42, '[CG07] G (fan)', '[CG07] G (fan)'),
   ('create', 43, None, '[CG07] W (heat)'),
   ('ChangeTagName', 43, '[CG07] W (heat)', '[CG07] W (heat)')]),
 ('plant9-unused-only-Conventional 2 Stage Heat/Cool USA System',
  9,
  'Conventional 2 Stage Heat/Cool USA System',
  [(255, 'Unused')],
  {'CoolFanLowOutput': 3,
   'CoolStage1Output': 1,
   'CoolStage2Output': 2,
   'CoolingPlantFanDefaultSpeed': 1,
   'CoolingPlantFanEnable': 1,
   'CoolingPlantFanSpeedControlEnable': 1,
   'CoolingPlantFanSpeeds': 1,
   'HeatFanLowOutput': 3,
   'HeatStage1Output': 4,
   'HeatStage2Output': 5,
   'HeatingPlantFanDefaultSpeed': 1,
   'HeatingPlantFanEnable': 1,
   'HeatingPlantFanSpeedControlEnable': 1,
   'HeatingPlantFanSpeeds': 1,
   'InternalRelay1GroupNumber': 1,
   'InternalRelay2GroupNumber': 2,
   'InternalRelay3GroupNumber': 3,
   'InternalRelay4GroupNumber': 4,
   'InternalRelay5GroupNumber': 5},
  [(255, 'Unused'),
   (1, '[CG07] Y (cool)'),
   (2, '[CG07] Y2 (cool)'),
   (3, '[CG07] G (fan)'),
   (4, '[CG07] W (heat)'),
   (5, '[CG07] W2 (heat)')],
  [('CoolActivationOutputGroup', 255),
   ('CoolStage1OutputGroup', 1),
   ('CoolStage2OutputGroup', 2),
   ('CoolStage3OutputGroup', 255),
   ('CoolFanLowOutputGroup', 3),
   ('CoolFanMediumOutputGroup', 255),
   ('CoolFanHighOutputGroup', 255),
   ('HeatActivationOutputGroup', 255),
   ('HeatStage1OutputGroup', 4),
   ('HeatStage2OutputGroup', 5),
   ('HeatStage3OutputGroup', 255),
   ('HeatFanLowOutputGroup', 3),
   ('HeatFanMediumOutputGroup', 255),
   ('HeatFanHighOutputGroup', 255),
   ('InternalRelay1Group', 1),
   ('InternalRelay2Group', 2),
   ('InternalRelay3Group', 3),
   ('InternalRelay4Group', 4),
   ('InternalRelay5Group', 5),
   ('CoolingPlantFanSpeedControlEnable', 1),
   ('CoolingPlantFanSpeeds', 1),
   ('CoolingPlantFanDefaultSpeed', 1),
   ('CoolingPlantFanEnable', 1),
   ('HeatingPlantFanSpeedControlEnable', 1),
   ('HeatingPlantFanSpeeds', 1),
   ('HeatingPlantFanDefaultSpeed', 1),
   ('HeatingPlantFanEnable', 1)],
  [('create', 1, None, '[CG07] Y (cool)'),
   ('create', 2, None, '[CG07] Y2 (cool)'),
   ('create', 3, None, '[CG07] G (fan)'),
   ('create', 4, None, '[CG07] W (heat)'),
   ('create', 5, None, '[CG07] W2 (heat)')]),
 ('plant9-retained-prefix-collision-Conventional 2 Stage Heat/Cool USA System',
  9,
  'Conventional 2 Stage Heat/Cool USA System',
  [(255, 'Unused'),
   (0, 'Opaque zero'),
   (1, 'User Y'),
   (3, 'User G'),
   (5, 'User W'),
   (20, '[CG07] Previous twenty'),
   (40, '[CG07] Previous forty')],
  {'CoolFanLowOutput': 42,
   'CoolStage1Output': 41,
   'CoolStage2Output': 2,
   'CoolingPlantFanDefaultSpeed': 1,
   'CoolingPlantFanEnable': 1,
   'CoolingPlantFanSpeedControlEnable': 1,
   'CoolingPlantFanSpeeds': 1,
   'HeatFanLowOutput': 42,
   'HeatStage1Output': 4,
   'HeatStage2Output': 43,
   'HeatingPlantFanDefaultSpeed': 1,
   'HeatingPlantFanEnable': 1,
   'HeatingPlantFanSpeedControlEnable': 1,
   'HeatingPlantFanSpeeds': 1,
   'InternalRelay1GroupNumber': 41,
   'InternalRelay2GroupNumber': 2,
   'InternalRelay3GroupNumber': 42,
   'InternalRelay4GroupNumber': 4,
   'InternalRelay5GroupNumber': 43},
  [(255, 'Unused'),
   (0, 'Opaque zero'),
   (1, 'User Y'),
   (3, 'User G'),
   (5, 'User W'),
   (20, '[CG07] Previous twenty'),
   (40, '[CG07] Previous forty'),
   (41, '[CG07] Y (cool)'),
   (2, '[CG07] Y2 (cool)'),
   (42, '[CG07] G (fan)'),
   (4, '[CG07] W (heat)'),
   (43, '[CG07] W2 (heat)')],
  [('CoolActivationOutputGroup', 255),
   ('CoolStage1OutputGroup', 41),
   ('CoolStage2OutputGroup', 2),
   ('CoolStage3OutputGroup', 255),
   ('CoolFanLowOutputGroup', 42),
   ('CoolFanMediumOutputGroup', 255),
   ('CoolFanHighOutputGroup', 255),
   ('HeatActivationOutputGroup', 255),
   ('HeatStage1OutputGroup', 4),
   ('HeatStage2OutputGroup', 43),
   ('HeatStage3OutputGroup', 255),
   ('HeatFanLowOutputGroup', 42),
   ('HeatFanMediumOutputGroup', 255),
   ('HeatFanHighOutputGroup', 255),
   ('InternalRelay1Group', 41),
   ('InternalRelay2Group', 2),
   ('InternalRelay3Group', 42),
   ('InternalRelay4Group', 4),
   ('InternalRelay5Group', 43),
   ('CoolingPlantFanSpeedControlEnable', 1),
   ('CoolingPlantFanSpeeds', 1),
   ('CoolingPlantFanDefaultSpeed', 1),
   ('CoolingPlantFanEnable', 1),
   ('HeatingPlantFanSpeedControlEnable', 1),
   ('HeatingPlantFanSpeeds', 1),
   ('HeatingPlantFanDefaultSpeed', 1),
   ('HeatingPlantFanEnable', 1)],
  [('create', 41, None, '[CG07] Y (cool)'),
   ('ChangeTagName', 41, '[CG07] Y (cool)', '[CG07] Y (cool)'),
   ('create', 2, None, '[CG07] Y2 (cool)'),
   ('create', 42, None, '[CG07] G (fan)'),
   ('ChangeTagName', 42, '[CG07] G (fan)', '[CG07] G (fan)'),
   ('create', 4, None, '[CG07] W (heat)'),
   ('create', 43, None, '[CG07] W2 (heat)'),
   ('ChangeTagName', 43, '[CG07] W2 (heat)', '[CG07] W2 (heat)')]),
 ('plant9-unused-only-Conventional Single Stage Heat/Cool USA System',
  9,
  'Conventional Single Stage Heat/Cool USA System',
  [(255, 'Unused')],
  {'CoolFanLowOutput': 3,
   'CoolStage1Output': 1,
   'CoolingPlantFanDefaultSpeed': 1,
   'CoolingPlantFanEnable': 1,
   'CoolingPlantFanSpeedControlEnable': 1,
   'CoolingPlantFanSpeeds': 1,
   'HeatFanLowOutput': 3,
   'HeatStage1Output': 5,
   'HeatingPlantFanDefaultSpeed': 1,
   'HeatingPlantFanEnable': 1,
   'HeatingPlantFanSpeedControlEnable': 1,
   'HeatingPlantFanSpeeds': 1,
   'InternalRelay1GroupNumber': 1,
   'InternalRelay3GroupNumber': 3,
   'InternalRelay5GroupNumber': 5},
  [(255, 'Unused'), (1, '[CG07] Y (cool)'), (3, '[CG07] G (fan)'), (5, '[CG07] W (heat)')],
  [('CoolActivationOutputGroup', 255),
   ('CoolStage1OutputGroup', 1),
   ('CoolStage2OutputGroup', 255),
   ('CoolStage3OutputGroup', 255),
   ('CoolFanLowOutputGroup', 3),
   ('CoolFanMediumOutputGroup', 255),
   ('CoolFanHighOutputGroup', 255),
   ('HeatActivationOutputGroup', 255),
   ('HeatStage1OutputGroup', 5),
   ('HeatStage2OutputGroup', 255),
   ('HeatStage3OutputGroup', 255),
   ('HeatFanLowOutputGroup', 3),
   ('HeatFanMediumOutputGroup', 255),
   ('HeatFanHighOutputGroup', 255),
   ('InternalRelay1Group', 1),
   ('InternalRelay2Group', 255),
   ('InternalRelay3Group', 3),
   ('InternalRelay4Group', 255),
   ('InternalRelay5Group', 5),
   ('CoolingPlantFanSpeedControlEnable', 1),
   ('CoolingPlantFanSpeeds', 1),
   ('CoolingPlantFanDefaultSpeed', 1),
   ('CoolingPlantFanEnable', 1),
   ('HeatingPlantFanSpeedControlEnable', 1),
   ('HeatingPlantFanSpeeds', 1),
   ('HeatingPlantFanDefaultSpeed', 1),
   ('HeatingPlantFanEnable', 1)],
  [('create', 1, None, '[CG07] Y (cool)'),
   ('create', 3, None, '[CG07] G (fan)'),
   ('create', 5, None, '[CG07] W (heat)')]),
 ('plant9-retained-prefix-collision-Conventional Single Stage Heat/Cool USA System',
  9,
  'Conventional Single Stage Heat/Cool USA System',
  [(255, 'Unused'),
   (0, 'Opaque zero'),
   (1, 'User Y'),
   (3, 'User G'),
   (5, 'User W'),
   (20, '[CG07] Previous twenty'),
   (40, '[CG07] Previous forty')],
  {'CoolFanLowOutput': 42,
   'CoolStage1Output': 41,
   'CoolingPlantFanDefaultSpeed': 1,
   'CoolingPlantFanEnable': 1,
   'CoolingPlantFanSpeedControlEnable': 1,
   'CoolingPlantFanSpeeds': 1,
   'HeatFanLowOutput': 42,
   'HeatStage1Output': 43,
   'HeatingPlantFanDefaultSpeed': 1,
   'HeatingPlantFanEnable': 1,
   'HeatingPlantFanSpeedControlEnable': 1,
   'HeatingPlantFanSpeeds': 1,
   'InternalRelay1GroupNumber': 41,
   'InternalRelay3GroupNumber': 42,
   'InternalRelay5GroupNumber': 43},
  [(255, 'Unused'),
   (0, 'Opaque zero'),
   (1, 'User Y'),
   (3, 'User G'),
   (5, 'User W'),
   (20, '[CG07] Previous twenty'),
   (40, '[CG07] Previous forty'),
   (41, '[CG07] Y (cool)'),
   (42, '[CG07] G (fan)'),
   (43, '[CG07] W (heat)')],
  [('CoolActivationOutputGroup', 255),
   ('CoolStage1OutputGroup', 41),
   ('CoolStage2OutputGroup', 255),
   ('CoolStage3OutputGroup', 255),
   ('CoolFanLowOutputGroup', 42),
   ('CoolFanMediumOutputGroup', 255),
   ('CoolFanHighOutputGroup', 255),
   ('HeatActivationOutputGroup', 255),
   ('HeatStage1OutputGroup', 43),
   ('HeatStage2OutputGroup', 255),
   ('HeatStage3OutputGroup', 255),
   ('HeatFanLowOutputGroup', 42),
   ('HeatFanMediumOutputGroup', 255),
   ('HeatFanHighOutputGroup', 255),
   ('InternalRelay1Group', 41),
   ('InternalRelay2Group', 255),
   ('InternalRelay3Group', 42),
   ('InternalRelay4Group', 255),
   ('InternalRelay5Group', 43),
   ('CoolingPlantFanSpeedControlEnable', 1),
   ('CoolingPlantFanSpeeds', 1),
   ('CoolingPlantFanDefaultSpeed', 1),
   ('CoolingPlantFanEnable', 1),
   ('HeatingPlantFanSpeedControlEnable', 1),
   ('HeatingPlantFanSpeeds', 1),
   ('HeatingPlantFanDefaultSpeed', 1),
   ('HeatingPlantFanEnable', 1)],
  [('create', 41, None, '[CG07] Y (cool)'),
   ('ChangeTagName', 41, '[CG07] Y (cool)', '[CG07] Y (cool)'),
   ('create', 42, None, '[CG07] G (fan)'),
   ('ChangeTagName', 42, '[CG07] G (fan)', '[CG07] G (fan)'),
   ('create', 43, None, '[CG07] W (heat)'),
   ('ChangeTagName', 43, '[CG07] W (heat)', '[CG07] W (heat)')]),
 ('plant9-unused-only-Unmatched retained name',
  9,
  'Unmatched retained name',
  [(255, 'Unused')],
  {'CoolFanLowOutput': 3,
   'CoolStage1Output': 1,
   'CoolingPlantFanDefaultSpeed': 1,
   'CoolingPlantFanEnable': 1,
   'CoolingPlantFanSpeedControlEnable': 1,
   'CoolingPlantFanSpeeds': 1,
   'HeatStage1Output': 5,
   'HeatingPlantFanDefaultSpeed': 1,
   'HeatingPlantFanSpeeds': 1,
   'InternalRelay1GroupNumber': 1,
   'InternalRelay3GroupNumber': 3,
   'InternalRelay5GroupNumber': 5},
  [(255, 'Unused'), (1, '[CG07] Y (cool)'), (3, '[CG07] G (fan)'), (5, '[CG07] W (heat)')],
  [('CoolActivationOutputGroup', 255),
   ('CoolStage1OutputGroup', 1),
   ('CoolStage2OutputGroup', 255),
   ('CoolStage3OutputGroup', 255),
   ('CoolFanLowOutputGroup', 3),
   ('CoolFanMediumOutputGroup', 255),
   ('CoolFanHighOutputGroup', 255),
   ('HeatActivationOutputGroup', 255),
   ('HeatStage1OutputGroup', 5),
   ('HeatStage2OutputGroup', 255),
   ('HeatStage3OutputGroup', 255),
   ('HeatFanLowOutputGroup', 255),
   ('HeatFanMediumOutputGroup', 255),
   ('HeatFanHighOutputGroup', 255),
   ('InternalRelay1Group', 1),
   ('InternalRelay2Group', 255),
   ('InternalRelay3Group', 3),
   ('InternalRelay4Group', 255),
   ('InternalRelay5Group', 5),
   ('CoolingPlantFanSpeedControlEnable', 1),
   ('CoolingPlantFanSpeeds', 1),
   ('CoolingPlantFanDefaultSpeed', 1),
   ('CoolingPlantFanEnable', 1),
   ('HeatingPlantFanSpeedControlEnable', 0),
   ('HeatingPlantFanSpeeds', 1),
   ('HeatingPlantFanDefaultSpeed', 1),
   ('HeatingPlantFanEnable', 0)],
  [('create', 1, None, '[CG07] Y (cool)'),
   ('create', 3, None, '[CG07] G (fan)'),
   ('create', 5, None, '[CG07] W (heat)')]),
 ('plant9-retained-prefix-collision-Unmatched retained name',
  9,
  'Unmatched retained name',
  [(255, 'Unused'),
   (0, 'Opaque zero'),
   (1, 'User Y'),
   (3, 'User G'),
   (5, 'User W'),
   (20, '[CG07] Previous twenty'),
   (40, '[CG07] Previous forty')],
  {'CoolFanLowOutput': 42,
   'CoolStage1Output': 41,
   'CoolingPlantFanDefaultSpeed': 1,
   'CoolingPlantFanEnable': 1,
   'CoolingPlantFanSpeedControlEnable': 1,
   'CoolingPlantFanSpeeds': 1,
   'HeatStage1Output': 43,
   'HeatingPlantFanDefaultSpeed': 1,
   'HeatingPlantFanSpeeds': 1,
   'InternalRelay1GroupNumber': 41,
   'InternalRelay3GroupNumber': 42,
   'InternalRelay5GroupNumber': 43},
  [(255, 'Unused'),
   (0, 'Opaque zero'),
   (1, 'User Y'),
   (3, 'User G'),
   (5, 'User W'),
   (20, '[CG07] Previous twenty'),
   (40, '[CG07] Previous forty'),
   (41, '[CG07] Y (cool)'),
   (42, '[CG07] G (fan)'),
   (43, '[CG07] W (heat)')],
  [('CoolActivationOutputGroup', 255),
   ('CoolStage1OutputGroup', 41),
   ('CoolStage2OutputGroup', 255),
   ('CoolStage3OutputGroup', 255),
   ('CoolFanLowOutputGroup', 42),
   ('CoolFanMediumOutputGroup', 255),
   ('CoolFanHighOutputGroup', 255),
   ('HeatActivationOutputGroup', 255),
   ('HeatStage1OutputGroup', 43),
   ('HeatStage2OutputGroup', 255),
   ('HeatStage3OutputGroup', 255),
   ('HeatFanLowOutputGroup', 255),
   ('HeatFanMediumOutputGroup', 255),
   ('HeatFanHighOutputGroup', 255),
   ('InternalRelay1Group', 41),
   ('InternalRelay2Group', 255),
   ('InternalRelay3Group', 42),
   ('InternalRelay4Group', 255),
   ('InternalRelay5Group', 43),
   ('CoolingPlantFanSpeedControlEnable', 1),
   ('CoolingPlantFanSpeeds', 1),
   ('CoolingPlantFanDefaultSpeed', 1),
   ('CoolingPlantFanEnable', 1),
   ('HeatingPlantFanSpeedControlEnable', 0),
   ('HeatingPlantFanSpeeds', 1),
   ('HeatingPlantFanDefaultSpeed', 1),
   ('HeatingPlantFanEnable', 0)],
  [('create', 41, None, '[CG07] Y (cool)'),
   ('ChangeTagName', 41, '[CG07] Y (cool)', '[CG07] Y (cool)'),
   ('create', 42, None, '[CG07] G (fan)'),
   ('ChangeTagName', 42, '[CG07] G (fan)', '[CG07] G (fan)'),
   ('create', 43, None, '[CG07] W (heat)'),
   ('ChangeTagName', 43, '[CG07] W (heat)', '[CG07] W (heat)')]),
 ('plant10-unused-only-nil',
  10,
  None,
  [(255, 'Unused')],
  {'CoolFanLowOutput': 3,
   'CoolFanMediumOutput': 4,
   'CoolStage1Output': 1,
   'CoolStage3Output': 2,
   'CoolingPlantFanDefaultSpeed': 1,
   'CoolingPlantFanEnable': 1,
   'CoolingPlantFanSpeedControlEnable': 1,
   'CoolingPlantFanSpeeds': 2,
   'HeatStage1Output': 5,
   'HeatingPlantFanDefaultSpeed': 1,
   'HeatingPlantFanSpeeds': 2,
   'InternalRelay1GroupNumber': 1,
   'InternalRelay2GroupNumber': 2,
   'InternalRelay3GroupNumber': 3,
   'InternalRelay4GroupNumber': 4,
   'InternalRelay5GroupNumber': 5},
  [(255, 'Unused'),
   (1, '[CG07] pump'),
   (2, '[CG07] fill'),
   (3, '[CG07] cool fan speed 1'),
   (4, '[CG07] cool fan speed 2'),
   (5, '[CG07] W (heat)')],
  [('CoolActivationOutputGroup', 255),
   ('CoolStage1OutputGroup', 1),
   ('CoolStage2OutputGroup', 255),
   ('CoolStage3OutputGroup', 2),
   ('CoolFanLowOutputGroup', 3),
   ('CoolFanMediumOutputGroup', 4),
   ('CoolFanHighOutputGroup', 255),
   ('HeatActivationOutputGroup', 255),
   ('HeatStage1OutputGroup', 5),
   ('HeatStage2OutputGroup', 255),
   ('HeatStage3OutputGroup', 255),
   ('HeatFanLowOutputGroup', 255),
   ('HeatFanMediumOutputGroup', 255),
   ('HeatFanHighOutputGroup', 255),
   ('InternalRelay1Group', 1),
   ('InternalRelay2Group', 2),
   ('InternalRelay3Group', 3),
   ('InternalRelay4Group', 4),
   ('InternalRelay5Group', 5),
   ('CoolingPlantFanSpeedControlEnable', 1),
   ('CoolingPlantFanSpeeds', 2),
   ('CoolingPlantFanDefaultSpeed', 1),
   ('CoolingPlantFanEnable', 1),
   ('HeatingPlantFanSpeedControlEnable', 0),
   ('HeatingPlantFanSpeeds', 2),
   ('HeatingPlantFanDefaultSpeed', 1),
   ('HeatingPlantFanEnable', 0)],
  [('create', 1, None, '[CG07] pump'),
   ('create', 2, None, '[CG07] fill'),
   ('create', 3, None, '[CG07] cool fan speed 1'),
   ('create', 4, None, '[CG07] cool fan speed 2'),
   ('create', 5, None, '[CG07] W (heat)')]),
 ('plant10-retained-prefix-collision-nil',
  10,
  None,
  [(255, 'Unused'),
   (0, 'Opaque zero'),
   (1, 'User Y'),
   (3, 'User G'),
   (5, 'User W'),
   (20, '[CG07] Previous twenty'),
   (40, '[CG07] Previous forty')],
  {'CoolFanLowOutput': 42,
   'CoolFanMediumOutput': 4,
   'CoolStage1Output': 41,
   'CoolStage3Output': 2,
   'CoolingPlantFanDefaultSpeed': 1,
   'CoolingPlantFanEnable': 1,
   'CoolingPlantFanSpeedControlEnable': 1,
   'CoolingPlantFanSpeeds': 2,
   'HeatStage1Output': 43,
   'HeatingPlantFanDefaultSpeed': 1,
   'HeatingPlantFanSpeeds': 2,
   'InternalRelay1GroupNumber': 41,
   'InternalRelay2GroupNumber': 2,
   'InternalRelay3GroupNumber': 42,
   'InternalRelay4GroupNumber': 4,
   'InternalRelay5GroupNumber': 43},
  [(255, 'Unused'),
   (0, 'Opaque zero'),
   (1, 'User Y'),
   (3, 'User G'),
   (5, 'User W'),
   (20, '[CG07] Previous twenty'),
   (40, '[CG07] Previous forty'),
   (41, '[CG07] pump'),
   (2, '[CG07] fill'),
   (42, '[CG07] cool fan speed 1'),
   (4, '[CG07] cool fan speed 2'),
   (43, '[CG07] W (heat)')],
  [('CoolActivationOutputGroup', 255),
   ('CoolStage1OutputGroup', 41),
   ('CoolStage2OutputGroup', 255),
   ('CoolStage3OutputGroup', 2),
   ('CoolFanLowOutputGroup', 42),
   ('CoolFanMediumOutputGroup', 4),
   ('CoolFanHighOutputGroup', 255),
   ('HeatActivationOutputGroup', 255),
   ('HeatStage1OutputGroup', 43),
   ('HeatStage2OutputGroup', 255),
   ('HeatStage3OutputGroup', 255),
   ('HeatFanLowOutputGroup', 255),
   ('HeatFanMediumOutputGroup', 255),
   ('HeatFanHighOutputGroup', 255),
   ('InternalRelay1Group', 41),
   ('InternalRelay2Group', 2),
   ('InternalRelay3Group', 42),
   ('InternalRelay4Group', 4),
   ('InternalRelay5Group', 43),
   ('CoolingPlantFanSpeedControlEnable', 1),
   ('CoolingPlantFanSpeeds', 2),
   ('CoolingPlantFanDefaultSpeed', 1),
   ('CoolingPlantFanEnable', 1),
   ('HeatingPlantFanSpeedControlEnable', 0),
   ('HeatingPlantFanSpeeds', 2),
   ('HeatingPlantFanDefaultSpeed', 1),
   ('HeatingPlantFanEnable', 0)],
  [('create', 41, None, '[CG07] pump'),
   ('ChangeTagName', 41, '[CG07] pump', '[CG07] pump'),
   ('create', 2, None, '[CG07] fill'),
   ('create', 42, None, '[CG07] cool fan speed 1'),
   ('ChangeTagName', 42, '[CG07] cool fan speed 1', '[CG07] cool fan speed 1'),
   ('create', 4, None, '[CG07] cool fan speed 2'),
   ('create', 43, None, '[CG07] W (heat)'),
   ('ChangeTagName', 43, '[CG07] W (heat)', '[CG07] W (heat)')]),
 ('plant11-unused-only-nil',
  11,
  None,
  [(255, 'Unused')],
  {'CoolFanLowOutput': 3,
   'CoolFanMediumOutput': 4,
   'CoolStage1Output': 1,
   'CoolStage2Output': 2,
   'CoolStage3Output': 5,
   'CoolingPlantFanDefaultSpeed': 1,
   'CoolingPlantFanEnable': 1,
   'CoolingPlantFanSpeedControlEnable': 1,
   'CoolingPlantFanSpeeds': 2,
   'HeatingPlantFanDefaultSpeed': 1,
   'HeatingPlantFanSpeeds': 2,
   'InternalRelay1GroupNumber': 1,
   'InternalRelay2GroupNumber': 2,
   'InternalRelay3GroupNumber': 3,
   'InternalRelay4GroupNumber': 4,
   'InternalRelay5GroupNumber': 5},
  [(255, 'Unused'),
   (1, '[CG07] Y (cool)'),
   (2, '[CG07] Open'),
   (5, '[CG07] Close'),
   (3, '[CG07] G1 (fan speed 1)'),
   (4, '[CG07] G2 (fan speed 2)')],
  [('CoolActivationOutputGroup', 255),
   ('CoolStage1OutputGroup', 1),
   ('CoolStage2OutputGroup', 2),
   ('CoolStage3OutputGroup', 5),
   ('CoolFanLowOutputGroup', 3),
   ('CoolFanMediumOutputGroup', 4),
   ('CoolFanHighOutputGroup', 255),
   ('HeatActivationOutputGroup', 255),
   ('HeatStage1OutputGroup', 255),
   ('HeatStage2OutputGroup', 255),
   ('HeatStage3OutputGroup', 255),
   ('HeatFanLowOutputGroup', 255),
   ('HeatFanMediumOutputGroup', 255),
   ('HeatFanHighOutputGroup', 255),
   ('InternalRelay1Group', 1),
   ('InternalRelay2Group', 2),
   ('InternalRelay3Group', 3),
   ('InternalRelay4Group', 4),
   ('InternalRelay5Group', 5),
   ('CoolingPlantFanSpeedControlEnable', 1),
   ('CoolingPlantFanSpeeds', 2),
   ('CoolingPlantFanDefaultSpeed', 1),
   ('CoolingPlantFanEnable', 1),
   ('HeatingPlantFanSpeedControlEnable', 0),
   ('HeatingPlantFanSpeeds', 2),
   ('HeatingPlantFanDefaultSpeed', 1),
   ('HeatingPlantFanEnable', 0)],
  [('create', 1, None, '[CG07] Y (cool)'),
   ('create', 2, None, '[CG07] Open'),
   ('create', 5, None, '[CG07] Close'),
   ('create', 3, None, '[CG07] G1 (fan speed 1)'),
   ('create', 4, None, '[CG07] G2 (fan speed 2)')]),
 ('plant11-retained-prefix-collision-nil',
  11,
  None,
  [(255, 'Unused'),
   (0, 'Opaque zero'),
   (1, 'User Y'),
   (3, 'User G'),
   (5, 'User W'),
   (20, '[CG07] Previous twenty'),
   (40, '[CG07] Previous forty')],
  {'CoolFanLowOutput': 43,
   'CoolFanMediumOutput': 4,
   'CoolStage1Output': 41,
   'CoolStage2Output': 2,
   'CoolStage3Output': 42,
   'CoolingPlantFanDefaultSpeed': 1,
   'CoolingPlantFanEnable': 1,
   'CoolingPlantFanSpeedControlEnable': 1,
   'CoolingPlantFanSpeeds': 2,
   'HeatingPlantFanDefaultSpeed': 1,
   'HeatingPlantFanSpeeds': 2,
   'InternalRelay1GroupNumber': 41,
   'InternalRelay2GroupNumber': 2,
   'InternalRelay3GroupNumber': 43,
   'InternalRelay4GroupNumber': 4,
   'InternalRelay5GroupNumber': 42},
  [(255, 'Unused'),
   (0, 'Opaque zero'),
   (1, 'User Y'),
   (3, 'User G'),
   (5, 'User W'),
   (20, '[CG07] Previous twenty'),
   (40, '[CG07] Previous forty'),
   (41, '[CG07] Y (cool)'),
   (2, '[CG07] Open'),
   (42, '[CG07] Close'),
   (43, '[CG07] G1 (fan speed 1)'),
   (4, '[CG07] G2 (fan speed 2)')],
  [('CoolActivationOutputGroup', 255),
   ('CoolStage1OutputGroup', 41),
   ('CoolStage2OutputGroup', 2),
   ('CoolStage3OutputGroup', 42),
   ('CoolFanLowOutputGroup', 43),
   ('CoolFanMediumOutputGroup', 4),
   ('CoolFanHighOutputGroup', 255),
   ('HeatActivationOutputGroup', 255),
   ('HeatStage1OutputGroup', 255),
   ('HeatStage2OutputGroup', 255),
   ('HeatStage3OutputGroup', 255),
   ('HeatFanLowOutputGroup', 255),
   ('HeatFanMediumOutputGroup', 255),
   ('HeatFanHighOutputGroup', 255),
   ('InternalRelay1Group', 41),
   ('InternalRelay2Group', 2),
   ('InternalRelay3Group', 43),
   ('InternalRelay4Group', 4),
   ('InternalRelay5Group', 42),
   ('CoolingPlantFanSpeedControlEnable', 1),
   ('CoolingPlantFanSpeeds', 2),
   ('CoolingPlantFanDefaultSpeed', 1),
   ('CoolingPlantFanEnable', 1),
   ('HeatingPlantFanSpeedControlEnable', 0),
   ('HeatingPlantFanSpeeds', 2),
   ('HeatingPlantFanDefaultSpeed', 1),
   ('HeatingPlantFanEnable', 0)],
  [('create', 41, None, '[CG07] Y (cool)'),
   ('ChangeTagName', 41, '[CG07] Y (cool)', '[CG07] Y (cool)'),
   ('create', 2, None, '[CG07] Open'),
   ('create', 42, None, '[CG07] Close'),
   ('ChangeTagName', 42, '[CG07] Close', '[CG07] Close'),
   ('create', 43, None, '[CG07] G1 (fan speed 1)'),
   ('ChangeTagName', 43, '[CG07] G1 (fan speed 1)', '[CG07] G1 (fan speed 1)'),
   ('create', 4, None, '[CG07] G2 (fan speed 2)')]))

ALLOCATOR_CASES = (('exact-generated-name-wins-over-requested',
  [(255, 'Unused'), (5, 'User'), (70, '[cg07] Target')],
  {},
  5,
  'Target',
  'attribute:CoolStage1',
  70,
  [(255, 'Unused'), (5, 'User'), (70, '[cg07] Target')],
  []),
 ('exact-name-at255-is-not-usable-allocation',
  [(255, '[CG07] Target'), (5, 'User')],
  {},
  5,
  'Target',
  'attribute:CoolStage1',
  255,
  [(255, '[CG07] Target'), (5, 'User')],
  []),
 ('own-attribute-exclusion-allows-retained-rename',
  [(255, 'Unused'), (5, '[CG07] Old')],
  {'CoolStage1': 5},
  5,
  'Target',
  'attribute:CoolStage1',
  5,
  [(255, 'Unused'), (5, '[CG07] Target')],
  [('ChangeTagName', 5, '[CG07] Old', '[CG07] Target')]),
 ('foreign-attribute-does-not-exclude-own-role',
  [(255, 'Unused'), (5, '[CG07] Old')],
  {'CoolStage1': 5},
  5,
  'Target',
  'foreign-attribute',
  6,
  [(255, 'Unused'), (5, '[CG07] Old'), (6, '[CG07] Target')],
  [('create', 6, None, '[CG07] Target'), ('ChangeTagName', 6, '[CG07] Target', '[CG07] Target')]),
 ('relay-alias-not-an-excluded-output-role',
  [(255, 'Unused'), (5, '[CG07] Old')],
  {'CoolStage1': 5, 'InternalRelay1': 5},
  5,
  'Target',
  'attribute:CoolStage1',
  5,
  [(255, 'Unused'), (5, '[CG07] Target')],
  [('ChangeTagName', 5, '[CG07] Old', '[CG07] Target')]),
 ('other-output-role-prevents-retained-rename',
  [(255, 'Unused'), (5, '[CG07] Old')],
  {'CoolStage1': 5, 'HeatFanLow': 5},
  5,
  'Target',
  'attribute:CoolStage1',
  6,
  [(255, 'Unused'), (5, '[CG07] Old'), (6, '[CG07] Target')],
  [('create', 6, None, '[CG07] Target'), ('ChangeTagName', 6, '[CG07] Target', '[CG07] Target')]),
 ('missing-requested-address-created-direct',
  [(255, 'Unused'), (20, '[CG07] Anchor')],
  {},
  5,
  'Target',
  'attribute:CoolStage1',
  5,
  [(255, 'Unused'), (20, '[CG07] Anchor'), (5, '[CG07] Target')],
  [('create', 5, None, '[CG07] Target')]),
 ('case-sensitive-prefix-rejects-nonmatching-ordinary-name',
  [(255, 'Unused'), (5, '[cg07] Old'), (20, '[CG07] Anchor')],
  {},
  5,
  'Target',
  'attribute:CoolStage1',
  21,
  [(255, 'Unused'), (5, '[cg07] Old'), (20, '[CG07] Anchor'), (21, '[CG07] Target')],
  [('create', 21, None, '[CG07] Target'), ('ChangeTagName', 21, '[CG07] Target', '[CG07] Target')]),
 ('highest-address-prefix-anchor-precedes-lower-hole',
  [(255, 'Unused'), (0, 'User'), (5, 'User'), (20, '[CG07] Anchor'), (40, '[CG07] Anchor40')],
  {},
  5,
  'Target',
  'attribute:CoolStage1',
  41,
  [(255, 'Unused'),
   (0, 'User'),
   (5, 'User'),
   (20, '[CG07] Anchor'),
   (40, '[CG07] Anchor40'),
   (41, '[CG07] Target')],
  [('create', 41, None, '[CG07] Target'), ('ChangeTagName', 41, '[CG07] Target', '[CG07] Target')]),
 ('ascii-only-case-fold-retains-nonascii-difference',
  [(255, 'Unused'), (5, '[CG07] Ü')],
  {},
  5,
  'ü',
  'attribute:CoolStage1',
  5,
  [(255, 'Unused'), (5, '[CG07] ü')],
  [('ChangeTagName', 5, '[CG07] Ü', '[CG07] ü')]),
 ('lowest-free-fallback-can-create-zero',
  [(255, 'Unused'), (5, 'User')],
  {},
  5,
  'Target',
  'attribute:CoolStage1',
  0,
  [(255, 'Unused'), (5, 'User'), (0, '[CG07] Target')],
  [('create', 0, None, '[CG07] Target'), ('ChangeTagName', 0, '[CG07] Target', '[CG07] Target')]),
 ('duplicate-name-at255-wins-address-sorted-forward-manager',
  [(20, '[CG07] Target'), (255, '[CG07] Target'), (5, 'User')],
  {},
  5,
  'Target',
  'attribute:CoolStage1',
  255,
  [(20, '[CG07] Target'), (255, '[CG07] Target'), (5, 'User')],
  []))

def pp_name(role):
    return role + ('GroupNumber' if role.startswith('InternalRelay') else 'Output')


def base_pp(plant):
    result = dict.fromkeys(PP_NAMES, 0)
    for role in ROLES:
        result[pp_name(role)] = 255
    result.update(ApplicationNumber=56, Application=49, ZoneGroup=7,
        InternalPlantType=plant, InternalPlantModes=31, InternalPlantZones=30,
        InstalledZones=30, ControlledZones=30, CoolingPlantInstalledZones=30,
        HeatingPlantInstalledZones=30, VentingPlantInstalledZones=30,
        MeasuredZones=1, UIAllocatedZones=2, UnrelatedParameter=173,
        InstallationCode=0, EvapProgramEnabled=1, NonEvapProgramEnabled=1)
    return result


def retained(address, name, application=56):
    level = RemoteLevel(7, 'oops', f'retained-level:{application}:{address}:7',
        'Retained Level Ω', '<Level><Address>7</Address><Value>oops</Value></Level>')
    return RemoteGroup(application, address, f'retained:{application}:{address}', name,
        'Group', json.dumps({'keep': 'exact & Ω', 'address': address}), (level,))


def owner(plant=3, groups=((255, 'Unused'),), refs=None, installation=None, **kwargs):
    values = base_pp(plant)
    rows = tuple(retained(n, name) for n, name in groups)
    zone = retained(7, 'Zone communication', 172)
    other = retained(1, 'Unrelated Group', 202)
    apps = (RemoteApplication(56, 'application56', 'Lighting', rows, '<Opaque>keep</Opaque>'),
            RemoteApplication(172, 'application172', 'Air Conditioning', (zone,), ''),
            RemoteApplication(202, 'application202', 'Unrelated', (other,), '<Opaque>Ω</Opaque>'))
    graph = ProjectGraphSnapshot('QZOWNED', 11, 20, '//QZOWNED/11/20', (), apps, (),
        'sealed source shape', 'synthetic source hash')
    resolver = _GraphResolver(graph)
    references = {role: resolver.live.get((56, (refs or {}).get(role, 255))) for role in ROLES}
    for role, group in references.items():
        values[pp_name(role)] = 255 if group is None else group.address
    model = PlantTypeModel(values, references, resolver,
        zone_group=lambda: zone, current_installation=lambda: installation,
        plant_type=kwargs.pop('plant_type', lambda: plant), **kwargs)
    project = {'project': {'address': 'QZOWNED', 'identity': 'owned-project',
        'opaque': {'keep': 'exact'}, 'networks': [
            {'address': 11, 'identity': 'network11', 'interface': {'kind': 'synthetic-no-live-endpoint'},
             'applications': [{'address': 56, 'identity': 'application56', 'groups': list(rows)},
                              {'address': 202, 'identity': 'application202', 'groups': [other]},
                              {'address': 172, 'identity': 'application172', 'groups': [zone]}],
             'units': [{'address': 20, 'identity': 'selected-unit', 'parameters': deepcopy(values)},
                       {'address': 21, 'identity': 'unrelated-unit', 'parameters': {'OpaqueSetting': 'unchanged & Ω'}}]},
            {'address': 12, 'identity': 'network12', 'opaque': {'tail': 'unchanged'}}]}}
    return model, project


def current_project(model, original):
    project = deepcopy(original)
    network = project['project']['networks'][0]
    network['units'][0]['parameters'] = deepcopy(model.values)
    assert set(model.resolver.apps) == {a['address'] for a in network['applications']}
    for application in network['applications']:
        application['groups'] = [g for (app, _), g in model.resolver.live.items() if app == application['address']]
    return project


def expected_project(original, values, groups):
    result = deepcopy(original)
    network = result['project']['networks'][0]
    network['units'][0]['parameters'] = values
    retained_by_address = {g.address: g for g in network['applications'][0]['groups']}
    network['applications'][0]['groups'] = [
        replace(retained_by_address[n], name=name) if n in retained_by_address
        else RemoteGroup(56, n, f'planned-group:56:{n}', name, 'Group', '')
        for n, name in groups]
    return result


def ledger(model):
    return [(('create' if row['call'] == 'CreateGroup' else 'ChangeTagName'),
        row.get('address', int(row['identity'].rsplit(':', 1)[1])),
        row.get('previous_name'), row['name']) for row in model.journal
        if row['call'] in ('CreateGroup', 'ChangeTagName')]


@pytest.mark.parametrize('case', PLANT_CASES, ids=[case[0] for case in PLANT_CASES])
def test_complete_direct_plant_full_pp_and_project(case):
    _, plant, installation, before_groups, changes, after_groups, assignments, expected_ledger = case
    model, before = owner(plant, before_groups, installation=installation)
    expected_values = deepcopy(model.values)
    expected_values.update(changes)
    receipt = model.update_parameters()
    assert len(model.values) == 109
    assert model.values == expected_values
    assert current_project(model, before) == expected_project(before, expected_values, after_groups)
    actual = [(row['property'], (model.resolver.live[56,
        int(row['after_identity'].rsplit(':', 1)[1])].address if row.get('after_identity') else row.get('after')))
        for row in receipt['journal'] if row['call'] == 'assign']
    assert actual == assignments
    assert ledger(model) == expected_ledger
    assert receipt['full_quick_zone_lifecycle'] is False
    assert receipt['save_executed'] is False
    for group in model.resolver.live.values():
        if group.identity.startswith('retained:'):
            assert group.levels[0].value == 'oops'


@pytest.mark.parametrize('case', ALLOCATOR_CASES, ids=[case[0] for case in ALLOCATOR_CASES])
def test_complete_allocator_identity_levels_and_whole_graph(case):
    _, groups, refs, requested, label, excluded, address, after_groups, expected_ledger = case
    model, before = owner(groups=groups, refs=refs)
    token = model.attribute(excluded.split(':', 1)[1]) if excluded.startswith('attribute:') else object()
    chosen = model.get_group(requested, label, token)
    assert chosen.address == address
    assert current_project(model, before) == expected_project(before, deepcopy(model.values), after_groups)
    assert ledger(model) == expected_ledger


def test_capacity_preserves_prior_name_mutation_and_every_level():
    groups = [(n, '[CG07] Old' if n == 254 else 'User ' + str(n)) for n in range(256)]
    model, before = owner(groups=groups)
    model.get_group(254, 'Earlier successful mutation', model.attribute('CoolStage1'))
    with pytest.raises(PlantGroupCapacityError, match='application is full'):
        model.get_group(5, 'Target', model.attribute('CoolStage1'))
    expected_groups = [(n, '[CG07] Earlier successful mutation' if n == 254 else name)
                       for n, name in groups]
    assert current_project(model, before) == expected_project(before, deepcopy(model.values), expected_groups)
    assert len(model.resolver.operations) == 1
    assert model.resolver.operations[0].action == 'rename'


def test_reserved255_cannot_be_automatic_allocation_when_missing():
    model, before = owner(groups=[(n, 'User ' + str(n)) for n in range(255)])
    assert model.get_new_group('Target') is None
    assert (56, 255) not in model.resolver.live
    assert current_project(model, before) == before


def test_mixed_nil_then_named_live_probes_are_not_collapsed():
    name = 'Conventional Single Stage Heat/Cool USA System'
    readings = iter((None, name, name, name, name, name))
    seen = []
    model, _ = owner(9)
    def installation():
        value = next(readings)
        seen.append((value, model.references['CoolStage1'].address))
        return value
    model.current_installation = installation
    model.update_parameters()
    # The source CFG performs these sequential live probes before setters.
    assert seen[:3] == [(None, 255), (name, 255), (name, 255)]
    matching = next(c for c in PLANT_CASES if c[1] == 9 and c[2] == name and c[0].startswith('plant9-unused-only'))
    expected = base_pp(9)
    expected.update(matching[4])
    assert model.values == expected


def test_fan_tail_reloads_live_model_type_after_parameter_assignments():
    types = iter((1, 2))
    model, _ = owner(1, plant_type=lambda: next(types))
    model.update_parameters()
    assert model.values['HeatStage1Output'] == 5
    assert model.values['CoolStage1Output'] == 255
    assert model.values['CoolingPlantFanEnable'] == 1
    assert model.values['HeatingPlantFanEnable'] == 0


def test_both_switches_mask_live_high_bit():
    model, _ = owner(1, plant_type=lambda: 0x81)
    model.update_parameters()
    expected = base_pp(1)
    expected.update(next(c[4] for c in PLANT_CASES if c[0] == 'plant1-unused-only-nil'))
    assert model.values == expected
    assert [r['plant_type'] for r in model.journal if 'plant_type' in r] == [1, 1]


def test_unknown_type_retains_pp_but_source_unused_getter_still_creates():
    model, before = owner(0, groups=[], plant_type=lambda: 127)
    model.update_parameters()
    assert model.values == before['project']['networks'][0]['units'][0]['parameters']
    assert model.resolver.live[56, 255].name == '<Unused>'
    assert [r for r in model.journal if r['call'] == 'assign'] == []


def test_equal_reference_and_scalar_values_do_not_publish_changed_hooks():
    changes = []
    model, _ = owner(0, reference_assigned=lambda *a: changes.append(a),
        scalar_assigned=lambda *a: changes.append(a))
    model.update_parameters()
    assert changes == []


def test_name_probe_nil_is_not_collapsed_to_general_default():
    values = iter(('Unmatched retained name', None))
    model, before = owner(9)
    model.current_installation = lambda: next(values)
    with pytest.raises(ThermostatTemplateError, match='nil after a nonnil probe'):
        model.update_parameters()
    assert model.values == before['project']['networks'][0]['units'][0]['parameters']
    assert not isinstance(ThermostatTemplateError(), PlantGroupCapacityError)


def test_foreign_role_token_excludes_no_shared_identity():
    left, _ = owner(groups=[(255, 'Unused'), (5, '[CG07] Old')], refs={'CoolStage1': 5})
    right, _ = owner()
    assert left.group_used_excluding_attribute(left.references['CoolStage1'], right.attribute('CoolStage1')) is True
    assert left.group_used_excluding_attribute(left.references['CoolStage1'], left.attribute('CoolStage1')) is False


def test_stale_group_and_wrong_sort_refuse_before_mutation():
    model, before = owner(groups=[(255, 'Unused'), (5, '[CG07] Old')], refs={'CoolStage1': 5})
    model.references['CoolStage1'] = replace(model.references['CoolStage1'], identity='foreign')
    with pytest.raises(ThermostatTemplateError, match='identity changed'):
        model.get_group(5, 'Target', object())
    assert current_project(model, before) == before
    with pytest.raises(ThermostatTemplateError, match='address-ascending'):
        owner(group_sort='tag-name')


def test_receipt_journal_is_detached_data():
    model, _ = owner(0)
    receipt = model.update_parameters()
    receipt['journal'][0]['plant_type'] = 255
    assert model.journal[0]['plant_type'] == 0
