//! Generates the test suites of this crate:
//!
//! * `golden_generated.rs` — one named `#[test]` per committed golden
//!   vector in `rust-migration-harness/vectors/*.jsonl`. The tests load
//!   the vectors from the harness directory at run time; this script only
//!   assigns stable, meaningful names (from the vector ids) and line
//!   indices, so every vector is individually reported by `cargo test`.
//!
//! * `domain_generated.rs` — exhaustive enumerations of meaningful input
//!   domains (every ramp-rate code, every checksum byte, every group
//!   address, the whole confirmation alphabet, every manchester level,
//!   every daemon status-request frame, every frame-split offset of
//!   representative wire traffic). Expected values are computed *here*,
//!   with independent mini-implementations, so the generated literals act
//!   as a second oracle against the production code.

use serde_json::Value;
use std::collections::HashSet;
use std::fmt::Write as _;
use std::path::{Path, PathBuf};

fn main() {
    let manifest = PathBuf::from(std::env::var("CARGO_MANIFEST_DIR").unwrap());
    let vectors = manifest.join("../../rust-migration-harness/vectors");
    let out = PathBuf::from(std::env::var("OUT_DIR").unwrap());
    println!("cargo:rerun-if-changed={}", vectors.display());
    println!("cargo:rerun-if-changed=build.rs");

    std::fs::write(out.join("golden_generated.rs"), generate_golden(&vectors))
        .expect("write golden_generated.rs");
    std::fs::write(out.join("domain_generated.rs"), generate_domain())
        .expect("write domain_generated.rs");
}

// ------------------------------------------------------------ shared utils

/// Turn a vector id (or any label) into a valid snake_case identifier tail.
fn sanitize(s: &str) -> String {
    let mut out = String::with_capacity(s.len());
    for c in s.chars() {
        if c.is_ascii_alphanumeric() {
            out.push(c.to_ascii_lowercase());
        } else if !out.ends_with('_') {
            out.push('_');
        }
    }
    out.trim_matches('_').to_string()
}

/// Independent C-Bus checksum (two's complement of the byte sum). Kept
/// separate from `cbus_protocol::common::cbus_checksum` on purpose: the
/// generated expectations must not be derived from the code under test.
fn ref_checksum(data: &[u8]) -> u8 {
    let sum: u32 = data.iter().map(|&b| b as u32).sum();
    (sum.wrapping_neg() & 0xff) as u8
}

fn hex_upper(data: &[u8]) -> String {
    data.iter().map(|b| format!("{b:02X}")).collect()
}

/// Frame body -> the uppercase-hex wire string with checksum appended.
fn framed_hex(body: &[u8]) -> String {
    let mut with_ck = body.to_vec();
    with_ck.push(ref_checksum(body));
    hex_upper(&with_ck)
}

struct TestWriter {
    out: String,
    names: HashSet<String>,
    count: usize,
}

impl TestWriter {
    fn new(header: &str) -> TestWriter {
        TestWriter {
            out: format!("// @generated by build.rs — do not edit.\n// {header}\n\n"),
            names: HashSet::new(),
            count: 0,
        }
    }

    /// Emit one `#[test]` with a unique name, doc comment and body.
    fn test(&mut self, name: &str, doc: &str, body: &str) {
        let mut name = name.to_string();
        let mut n = 2;
        while !self.names.insert(name.clone()) {
            name = format!("{name}_{n}");
            n += 1;
        }
        if !doc.is_empty() {
            writeln!(self.out, "#[doc = {doc:?}]").unwrap();
        }
        writeln!(self.out, "#[test]\nfn {name}() {{\n{body}\n}}\n").unwrap();
        self.count += 1;
    }
}

// ------------------------------------------------------- golden vectors

const VECTOR_FILES: &[(&str, &str, &str)] = &[
    // (file, test-name stem, id prefix to strip)
    ("decode_from_pci.jsonl", "decode_from_pci", "fp-"),
    ("decode_to_pci.jsonl", "decode_to_pci", "tp-"),
    ("encode.jsonl", "encode", "en-"),
    ("checksum.jsonl", "checksum", "ck-"),
    ("ramp_rates.jsonl", "ramp_rates", "rr-"),
    ("mqtt_topics.jsonl", "mqtt_topics", "mt-"),
    ("ha_discovery.jsonl", "ha_discovery", "ha-"),
];

fn generate_golden(vectors_dir: &Path) -> String {
    let mut w = TestWriter::new("One test per golden vector; see cbus_golden_tests::run_vector.");
    for &(fname, stem, prefix) in VECTOR_FILES {
        let path = vectors_dir.join(fname);
        let content = std::fs::read_to_string(&path)
            .unwrap_or_else(|e| panic!("cannot read {}: {e}", path.display()));
        for (index, line) in content.lines().filter(|l| !l.trim().is_empty()).enumerate() {
            let v: Value = serde_json::from_str(line)
                .unwrap_or_else(|e| panic!("{fname}:{index}: bad JSON: {e}"));
            let id = v
                .get("id")
                .and_then(Value::as_str)
                .unwrap_or_else(|| panic!("{fname}:{index}: vector has no id"))
                .to_string();
            let tail = sanitize(id.strip_prefix(prefix).unwrap_or(&id));
            let name = format!("{stem}_{tail}");
            let doc = vector_doc(fname, &id, &v);
            let body = format!("    support::run_vector({fname:?}, {index}, {id:?});");
            w.test(&name, &doc, &body);
        }
    }
    w.out
}

/// A human-readable one-liner describing the vector, for the test's docs.
fn vector_doc(fname: &str, id: &str, v: &Value) -> String {
    let note = v.get("note").and_then(Value::as_str).unwrap_or("");
    match fname {
        "ramp_rates.jsonl" => {
            let kind = v.get("kind").and_then(Value::as_str).unwrap_or("?");
            let input = v.get("in").and_then(Value::as_u64).unwrap_or(0);
            let expect = v.get("expect").and_then(Value::as_u64).unwrap_or(0);
            format!("{id}: {kind}({input}) == {expect}")
        }
        "checksum.jsonl" => {
            let data = v.get("data_hex").and_then(Value::as_str).unwrap_or("");
            let expect = v
                .get("expect_checksum")
                .and_then(Value::as_u64)
                .unwrap_or(0);
            format!("{id}: checksum(0x{data}) == {expect}")
        }
        _ if note.is_empty() => id.to_string(),
        _ => format!("{id}: {note}"),
    }
}

// ---------------------------------------------------- domain enumerations

/// The 16-entry ramp-rate table from the C-Bus lighting application docs
/// (independent copy; also pinned by the ramp_rates golden vectors).
const RAMP_TABLE: &[(u8, u32)] = &[
    (0x02, 0),
    (0x0a, 4),
    (0x12, 8),
    (0x1a, 12),
    (0x22, 20),
    (0x2a, 30),
    (0x32, 40),
    (0x3a, 60),
    (0x42, 90),
    (0x4a, 120),
    (0x52, 180),
    (0x5a, 300),
    (0x62, 420),
    (0x6a, 600),
    (0x72, 900),
    (0x7a, 1020),
];

const CONFIRMATION_ALPHABET: &[u8] = b"hijklmnopqrstuvwxyzg";

/// Independent manchester encoding (report.py nibble table).
fn ref_manchester(v: u8) -> [u8; 2] {
    const NIBBLES: [u8; 4] = [0b1010, 0b1001, 0b0110, 0b0101];
    [
        NIBBLES[(v & 0x3) as usize] | (NIBBLES[((v >> 2) & 0x3) as usize] << 4),
        NIBBLES[((v >> 4) & 0x3) as usize] | (NIBBLES[((v >> 6) & 0x3) as usize] << 4),
    ]
}

fn generate_domain() -> String {
    let mut w =
        TestWriter::new("Exhaustive domain enumerations with independently computed expectations.");
    ramp_code_tests(&mut w);
    checksum_byte_tests(&mut w);
    topic_roundtrip_tests(&mut w);
    app_form_tests(&mut w);
    confirmation_tests(&mut w);
    lighting_wire_tests(&mut w);
    event_decode_tests(&mut w);
    temperature_tests(&mut w);
    manchester_tests(&mut w);
    status_request_tests(&mut w);
    discovery_identity_tests(&mut w);
    split_tests(&mut w);
    w.out
}

/// All 256 ramp-rate command codes: the 16 valid codes map to their exact
/// durations, the other 240 are rejected.
fn ramp_code_tests(w: &mut TestWriter) {
    for code in 0u16..=255 {
        let code = code as u8;
        match RAMP_TABLE.iter().find(|&&(c, _)| c == code) {
            Some(&(_, secs)) => w.test(
                &format!("ramp_rate_code_0x{code:02x}_is_{secs}s"),
                &format!("ramp-rate code {code:#04x} maps to exactly {secs} s"),
                &format!("    assert_eq!(ramp_rate_to_duration({code:#04x}), Some({secs}));"),
            ),
            None => w.test(
                &format!("ramp_rate_code_0x{code:02x}_is_invalid"),
                &format!("{code:#04x} is not one of the 16 valid ramp-rate codes"),
                &format!("    assert_eq!(ramp_rate_to_duration({code:#04x}), None);"),
            ),
        }
    }
}

/// Every single-byte input: checksum is the two's complement of the byte,
/// and appending it validates.
fn checksum_byte_tests(w: &mut TestWriter) {
    for b in 0u16..=255 {
        let b = b as u8;
        let ck = ref_checksum(&[b]);
        w.test(
            &format!("checksum_single_byte_0x{b:02x}"),
            &format!("checksum([{b:#04x}]) == {ck:#04x} (two's complement), and validates"),
            &format!(
                "    assert_eq!(cbus_checksum(&[{b:#04x}]), {ck:#04x});\n    \
                 assert!(validate_cbus_checksum(&[{b:#04x}, {ck:#04x}]));"
            ),
        );
    }
}

/// Every group address: format the /set + /state topics for the default
/// lighting app (bare group number) and for app 48 (app_ga form), then
/// parse the set topic back to the same (group, app).
fn topic_roundtrip_tests(w: &mut TestWriter) {
    for ga in 0u16..=255 {
        let set = format!("homeassistant/light/cbus_{ga}/set");
        let state = format!("homeassistant/light/cbus_{ga}/state");
        w.test(
            &format!("topic_roundtrip_default_app_group_{ga:03}"),
            &format!("group {ga} on the default lighting app (56) uses the bare group number"),
            &format!(
                "    let set = set_topic({ga}, 56);\n    \
                 assert_eq!(set, {set:?});\n    \
                 assert_eq!(state_topic({ga}, 56), {state:?});\n    \
                 assert_eq!(topic_group_address(&set), Ok(({ga}, 56)));"
            ),
        );
    }
    for ga in 0u16..=255 {
        let set = format!("homeassistant/light/cbus_048_{ga:03}/set");
        let state = format!("homeassistant/light/cbus_048_{ga:03}/state");
        w.test(
            &format!("topic_roundtrip_app048_group_{ga:03}"),
            &format!("group {ga} on lighting app 48 uses the zero-padded app_ga form"),
            &format!(
                "    let set = set_topic({ga}, 48);\n    \
                 assert_eq!(set, {set:?});\n    \
                 assert_eq!(state_topic({ga}, 48), {state:?});\n    \
                 assert_eq!(topic_group_address(&set), Ok(({ga}, 48)));"
            ),
        );
    }
}

/// Every lighting application address (0x30..=0x5F): only 56 keeps the
/// historic bare-group topic; all others get `<app:03>_<ga:03>`.
fn app_form_tests(w: &mut TestWriter) {
    for app in 0x30i64..=0x5f {
        let seg = if app == 56 {
            "cbus_7".to_string()
        } else {
            format!("cbus_{app:03}_007")
        };
        let set = format!("homeassistant/light/{seg}/set");
        w.test(
            &format!("topic_form_app_{app:03}_group_007"),
            &format!("lighting app {app} formats group 7 as {seg:?} and parses back"),
            &format!(
                "    let set = set_topic(7, {app});\n    \
                 assert_eq!(set, {set:?});\n    \
                 assert_eq!(topic_group_address(&set), Ok((7, {app})));"
            ),
        );
    }
}

/// The whole confirmation-code alphabet, success and failure: encode to
/// `<code>.` / `<code>#` and decode the same two bytes back.
fn confirmation_tests(w: &mut TestWriter) {
    for &code in CONFIRMATION_ALPHABET {
        let c = code as char;
        for (success, mark) in [(true, '.'), (false, '#')] {
            let wire = format!("{c}{mark}");
            let label = if success { "success" } else { "failure" };
            w.test(
                &format!("confirmation_code_{c}_{label}_roundtrip"),
                &format!("confirmation {wire:?} encodes and decodes for pool code {c:?}"),
                &format!(
                    "    let p = Packet::Confirmation {{ code: b'{c}', success: {success} }};\n    \
                     assert_eq!(p.encode_packet().unwrap(), b{wire:?});\n    \
                     assert_eq!(\n        decode_packet(b{wire:?}, true, true, true),\n        \
                     (Some(p), 2)\n    );"
                ),
            );
        }
    }
}

/// Client->PCI lighting frames for every group address (on and off) and
/// every ramp level: `encode_packet()` must equal the independently
/// assembled uppercase-hex frame including its checksum.
fn lighting_wire_tests(w: &mut TestWriter) {
    for ga in 0u16..=255 {
        let ga = ga as u8;
        for (variant, cmd, sal) in [("on", 0x79u8, "LightingOn"), ("off", 0x01, "LightingOff")] {
            let expect = framed_hex(&[0x05, 0x38, 0x00, cmd, ga]);
            w.test(
                &format!("lighting_{variant}_group_{ga:03}_wire"),
                &format!("lighting {variant} for group {ga} encodes to {expect}"),
                &format!(
                    "    let p = Packet::PointToMultipoint {{\n        \
                     meta: Meta::new(true, 0),\n        application: 0x38,\n        \
                     sals: vec![Sal::{sal} {{ application: 0x38, group_address: {ga} }}],\n    \
                     }};\n    \
                     assert_eq!(p.encode_packet().unwrap(), b{expect:?});"
                ),
            );
        }
    }
    // ramp to every level: 4 s duration snaps to rate code 0x0A
    for level in 0u16..=255 {
        let level = level as u8;
        let expect = framed_hex(&[0x05, 0x38, 0x00, 0x0a, 22, level]);
        w.test(
            &format!("lighting_ramp_4s_group_022_level_{level:03}_wire"),
            &format!("4 s ramp of group 22 to level {level} encodes to {expect}"),
            &format!(
                "    let p = Packet::PointToMultipoint {{\n        \
                 meta: Meta::new(true, 0),\n        application: 0x38,\n        \
                 sals: vec![Sal::LightingRamp {{\n            application: 0x38,\n            \
                 group_address: 22,\n            duration: 4,\n            level: {level},\n        \
                 }}],\n    }};\n    \
                 assert_eq!(p.encode_packet().unwrap(), b{expect:?});"
            ),
        );
    }
}

/// PCI->client "lighting on" event frames for every group address: the
/// wire (assembled here, incl. source address and checksum) must decode to
/// exactly one LightingOn SAL with the right group and source.
fn event_decode_tests(w: &mut TestWriter) {
    for ga in 0u16..=255 {
        let ga = ga as u8;
        let wire = format!("{}\r\n", framed_hex(&[0x05, 0x0b, 0x38, 0x00, 0x79, ga]));
        let len = wire.len();
        w.test(
            &format!("event_lighting_on_group_{ga:03}_decodes"),
            &format!("from-PCI lighting-on event for group {ga} (source 11) decodes exactly"),
            &format!(
                "    let expected = Packet::PointToMultipoint {{\n        \
                 meta: Meta {{\n            checksum: true,\n            priority_class: 0,\n            \
                 source_address: Some(11),\n            confirmation: None,\n        }},\n        \
                 application: 0x38,\n        \
                 sals: vec![Sal::LightingOn {{ application: 0x38, group_address: {ga} }}],\n    \
                 }};\n    \
                 assert_eq!(\n        decode_packet(b{wire:?}, true, true, true),\n        \
                 (Some(expected), {len})\n    );"
            ),
        );
    }
}

/// Every temperature byte: decodes to byte/4.0 °C and (being an exact
/// quarter) encodes back to the identical SAL bytes.
fn temperature_tests(w: &mut TestWriter) {
    for b in 0u16..=255 {
        let b = b as u8;
        let temp = b as f64 / 4.0;
        let temp_lit = format!("{temp:?}");
        // encode clamps at 63.75 max: all byte values are within range
        w.test(
            &format!("temperature_byte_{b:03}_is_{}c", sanitize(&temp_lit)),
            &format!("temperature byte {b} == {temp_lit} °C, decode and re-encode"),
            &format!(
                "    let sals = decode_sals(0x19, &[0x02, 5, {b}]).unwrap();\n    \
                 let expected = Sal::TemperatureBroadcast {{\n        group_address: 5,\n        \
                 temperature: {temp_lit},\n    }};\n    \
                 assert_eq!(sals, vec![expected.clone()]);\n    \
                 assert_eq!(expected.encode().unwrap(), vec![0x02, 5, {b}]);"
            ),
        );
    }
}

/// Every level value: the manchester pair computed here must match
/// `manchester_encode`, and decode back to the level.
fn manchester_tests(w: &mut TestWriter) {
    for v in 0u16..=255 {
        let v = v as u8;
        let [b0, b1] = ref_manchester(v);
        w.test(
            &format!("manchester_level_{v:03}_roundtrip"),
            &format!("level {v} manchester-encodes to [{b0:#04x}, {b1:#04x}] and back"),
            &format!(
                "    assert_eq!(manchester_encode(Some({v})), [{b0:#04x}, {b1:#04x}]);\n    \
                 assert_eq!(manchester_decode(&[{b0:#04x}, {b1:#04x}]), Some({v}));"
            ),
        );
    }
}

/// Every level status-request frame cmqttd can send: 48 lighting apps x 8
/// block starts, each against an independently assembled wire string.
fn status_request_tests(w: &mut TestWriter) {
    for app in 0x30u8..=0x5f {
        for block in (0u16..256).step_by(32) {
            let block = block as u8;
            let expect = framed_hex(&[0x05, 0xff, 0x00, 0x73, 0x07, app, block]);
            w.test(
                &format!("status_request_app_0x{app:02x}_block_{block:03}_wire"),
                &format!("level status request app {app:#04x} block {block} encodes to {expect}"),
                &format!(
                    "    let p = Packet::PointToMultipoint {{\n        \
                     meta: Meta::new(true, 0),\n        application: 0xff,\n        \
                     sals: vec![Sal::StatusRequest {{\n            level_request: true,\n            \
                     group_address: {block},\n            child_application: {app:#04x},\n        \
                     }}],\n    }};\n    \
                     assert_eq!(p.encode_packet().unwrap(), b{expect:?});"
                ),
            );
        }
    }
}

/// Every group address: the HA discovery payload identity fields (unique
/// ids, display name padding, all four topics) for the default app.
fn discovery_identity_tests(w: &mut TestWriter) {
    for ga in 0u16..=255 {
        let uid = format!("cbus_light_{ga}");
        let sensor_uid = format!("cbus_bin_sensor_{ga}");
        let name = format!("C-Bus Light {ga:03}");
        let set = format!("homeassistant/light/cbus_{ga}/set");
        let state = format!("homeassistant/light/cbus_{ga}/state");
        let sensor_state = format!("homeassistant/binary_sensor/cbus_{ga}/state");
        let conf = format!("homeassistant/light/cbus_{ga}/config");
        w.test(
            &format!("discovery_identity_group_{ga:03}"),
            &format!("discovery payload identity for unlabelled group {ga} on app 56"),
            &format!(
                "    let d = light_discovery({ga}, 56, None);\n    \
                 assert_eq!(d.light_config[\"unique_id\"], {uid:?});\n    \
                 assert_eq!(d.light_config[\"name\"], {name:?});\n    \
                 assert_eq!(d.light_config[\"cmd_t\"], {set:?});\n    \
                 assert_eq!(d.light_config[\"stat_t\"], {state:?});\n    \
                 assert_eq!(d.sensor_config[\"unique_id\"], {sensor_uid:?});\n    \
                 assert_eq!(d.sensor_config[\"stat_t\"], {sensor_state:?});\n    \
                 assert_eq!(d.subscribe_topic, {set:?});\n    \
                 assert_eq!(d.light_config_topic, {conf:?});\n    \
                 assert_eq!(d.light_config[\"device\"][\"connections\"][0][1], {:?});",
                ga.to_string()
            ),
        );
    }
}

/// Representative wire streams split at every byte boundary: the frame
/// buffer must produce identical packets no matter where the read
/// boundary falls. The whole-stream decodes are pinned by golden vectors;
/// these pin that chunking is transparent at *every* offset.
fn split_tests(w: &mut TestWriter) {
    // (name, latin-1 wire string, server_side)
    let frames: &[(&str, String, bool)] = &[
        ("pm_light_on_event", "05013800790148\r\n".to_string(), false),
        (
            "confirmation_then_event",
            "h.05013800790148\r\n".to_string(),
            false,
        ),
        ("direct_cal_reply", "8221104D\r\n".to_string(), false),
        (
            // fp-0381: extended status level report, 64 bytes
            "level_report",
            "86FFFF00F90738000000AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA00000000A4\r\n".to_string(),
            false,
        ),
        (
            "client_init_sequence",
            "~\r~\r~\r|\rA32100FFh\r".to_string(),
            true,
        ),
    ];
    for (name, wire, server_side) in frames {
        for at in 1..wire.len() {
            w.test(
                &format!("split_{name}_at_{at:02}"),
                &format!("{name} split after byte {at} decodes identically to one feed"),
                &format!("    assert_split_transparent(b{wire:?}, {at}, {server_side});"),
            );
        }
    }
}
