name: Docker Build

on:
  push:
    branches: [ master ]
    paths:
      - 'Dockerfile'
      - 'docker-compose.yml'
      - '.env.example'
      - 'entrypoint-cmqttd.sh'
  pull_request:
    branches: [ master ]
    paths:
      - 'Dockerfile'
      - 'docker-compose.yml'
      - '.env.example'
      - 'entrypoint-cmqttd.sh'
  workflow_dispatch:

jobs:
  docker:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
      
    - name: Copy example env file
      run: |
        cp .env.example .env
        
    - name: Build Docker image
      uses: docker/build-push-action@v4
      with:
        context: .
        file: ./Dockerfile
        push: false
        load: true
        tags: cmqttd:test
        
    - name: Test docker-compose
      run: |
        docker-compose up -d
        docker-compose ps
        sleep 10  # Give the container time to start up
        docker-compose logs
        docker-compose down
        
    - name: Verify no runtime errors
      run: |
        if docker-compose logs | grep -i "error"; then
          echo "Found errors in container logs"
          exit 1
        else
          echo "No errors found in container logs"
        fi 