name: Test and Push Changes

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:
    inputs:
      branch_name:
        description: 'Target branch name'
        required: true
        default: 'automated-update'

jobs:
  test-and-push:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        if [ -f requirements-tests.txt ]; then pip install -r requirements-tests.txt; fi
        
    - name: Run tests
      run: |
        python -m unittest
        
    - name: Set target branch name
      id: set_branch
      run: |
        if [ "${{ github.event_name }}" == "workflow_dispatch" ]; then
          echo "BRANCH_NAME=${{ github.event.inputs.branch_name }}" >> $GITHUB_ENV
        else
          echo "BRANCH_NAME=automated-update-$(date +'%Y%m%d-%H%M%S')" >> $GITHUB_ENV
        fi
        
    - name: Configure Git
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        
    - name: Create and checkout branch
      run: |
        git checkout -b ${{ env.BRANCH_NAME }}
        
    - name: Check for changes
      id: git_status
      run: |
        if [[ -n $(git status --porcelain) ]]; then
          echo "changes=true" >> $GITHUB_OUTPUT
        else
          echo "changes=false" >> $GITHUB_OUTPUT
        fi
        
    - name: Commit changes
      if: steps.git_status.outputs.changes == 'true'
      run: |
        git add .
        git commit -m "Automated update from GitHub Actions"
        
    - name: Push changes
      if: steps.git_status.outputs.changes == 'true'
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: ${{ env.BRANCH_NAME }}
        
    - name: Create Pull Request
      if: steps.git_status.outputs.changes == 'true'
      uses: peter-evans/create-pull-request@v5
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        base: master
        branch: ${{ env.BRANCH_NAME }}
        title: "Automated updates from GitHub Actions"
        body: |
          This PR was automatically created by the GitHub Actions workflow.
          
          The changes passed all tests and are ready for review. 